/**
 * Companies Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the companies entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const companiesFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Company Name',
      description: 'Company display name',
      placeholder: 'Enter company name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'legalName',
    type: 'text',
    required: false,
    display: {
      label: 'Legal Name',
      description: 'Legal registered company name',
      placeholder: 'Enter legal name...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'taxId',
    type: 'text',
    required: false,
    display: {
      label: 'Tax ID',
      description: 'Tax identification number',
      placeholder: 'Enter tax ID...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'website',
    type: 'url',
    required: false,
    display: {
      label: 'Website',
      description: 'Company website URL',
      placeholder: 'https://example.com',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'email',
    type: 'email',
    required: false,
    display: {
      label: 'Email',
      description: 'General company email',
      placeholder: 'info@company.com',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'phone',
    type: 'text',
    required: false,
    display: {
      label: 'Phone',
      description: 'Main company phone number',
      placeholder: 'Enter phone number...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'industry',
    type: 'text',
    required: false,
    display: {
      label: 'Industry',
      description: 'Industry sector',
      placeholder: 'Enter industry...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'type',
    type: 'select',
    required: false,
    options: [
      { value: 'prospect', label: 'Prospect' },
      { value: 'customer', label: 'Customer' },
      { value: 'partner', label: 'Partner' },
      { value: 'competitor', label: 'Competitor' },
      { value: 'vendor', label: 'Vendor' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Company Type',
      description: 'Type of company relationship',
      placeholder: 'Select type...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'size',
    type: 'select',
    required: false,
    options: [
      { value: '1-10', label: '1-10 employees' },
      { value: '11-50', label: '11-50 employees' },
      { value: '51-200', label: '51-200 employees' },
      { value: '201-500', label: '201-500 employees' },
      { value: '500+', label: '500+ employees' },
    ],
    display: {
      label: 'Company Size',
      description: 'Company size by employees',
      placeholder: 'Select size...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'annualRevenue',
    type: 'number',
    required: false,
    display: {
      label: 'Annual Revenue',
      description: 'Annual revenue in currency',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'address',
    type: 'textarea',
    required: false,
    display: {
      label: 'Address',
      description: 'Street address',
      placeholder: 'Enter address...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'city',
    type: 'text',
    required: false,
    display: {
      label: 'City',
      description: 'City',
      placeholder: 'Enter city...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 3,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'state',
    type: 'text',
    required: false,
    display: {
      label: 'State',
      description: 'State or province',
      placeholder: 'Enter state...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 3,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'country',
    type: 'text',
    required: false,
    display: {
      label: 'Country',
      description: 'Country',
      placeholder: 'US',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 3,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'postalCode',
    type: 'text',
    required: false,
    display: {
      label: 'Postal Code',
      description: 'Postal or ZIP code',
      placeholder: 'Enter postal code...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 15,
      columnWidth: 3,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'logo',
    type: 'url',
    required: false,
    display: {
      label: 'Logo',
      description: 'Company logo URL',
      placeholder: 'https://example.com/logo.png',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 16,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'rating',
    type: 'select',
    required: false,
    options: [
      { value: 'hot', label: 'Hot' },
      { value: 'warm', label: 'Warm' },
      { value: 'cold', label: 'Cold' },
    ],
    display: {
      label: 'Rating',
      description: 'Sales rating',
      placeholder: 'Select rating...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 17,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'assignedTo',
    type: 'user',
    required: false,
    display: {
      label: 'Assigned To',
      description: 'Account manager assigned',
      placeholder: 'Select user...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 18,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the company was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the company was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]