// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.
// Source: @/entities/customers/customers.config

import { z } from 'zod'
import type { EntityConfig } from '../schema/types'
import { generateEntitySchemas } from '../schema/schema-generator'
import { childrenResponseSchema, metasResponseSchema } from '../schema/response-shape'

export const customersApiPath = '/api/v1/customers'

/** The entity as the server sees it: the request schemas below are generated from it by the server's own generator. */
export const customerEntity = {
  slug: 'customers',
  names: { singular: 'customer' },
  fields: [
    { name: 'name', type: 'text', required: true, display: { label: 'Name' }, api: { readOnly: false } },
    { name: 'account', type: 'number', required: true, display: { label: 'Account Number' }, api: { readOnly: false } },
    { name: 'office', type: 'text', required: true, display: { label: 'Office' }, api: { readOnly: false } },
    { name: 'phone', type: 'text', required: false, display: { label: 'Phone' }, api: { readOnly: false } },
    { name: 'salesRep', type: 'text', required: false, display: { label: 'Sales Representative' }, api: { readOnly: false } },
    { name: 'visitDays', type: 'multiselect', required: false, options: [{ value: 'lun', label: 'Lunes' }, { value: 'mar', label: 'Martes' }, { value: 'mie', label: 'Miércoles' }, { value: 'jue', label: 'Jueves' }, { value: 'vie', label: 'Viernes' }], display: { label: 'Visit Days' }, api: { readOnly: false } },
    { name: 'contactDays', type: 'multiselect', required: false, options: [{ value: 'lun', label: 'Lunes' }, { value: 'mar', label: 'Martes' }, { value: 'mie', label: 'Miércoles' }, { value: 'jue', label: 'Jueves' }, { value: 'vie', label: 'Viernes' }], display: { label: 'Contact Days' }, api: { readOnly: false } },
  ],
} satisfies EntityConfig

const customerSchemas = generateEntitySchemas(customerEntity)

export const customerVisitDaysOptionSchema = z.enum(['lun', 'mar', 'mie', 'jue', 'vie'])
export type CustomerVisitDaysOption = z.infer<typeof customerVisitDaysOptionSchema>

export const customerContactDaysOptionSchema = z.enum(['lun', 'mar', 'mie', 'jue', 'vie'])
export type CustomerContactDaysOption = z.infer<typeof customerContactDaysOptionSchema>

export const customerSchema = z.object({
  id: z.string(),
  userId: z.string(),
  teamId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  name: z.string(),
  account: z.number(),
  office: z.string(),
  phone: z.string().nullish(),
  salesRep: z.string().nullish(),
  visitDays: z.array(customerVisitDaysOptionSchema).nullish(),
  contactDays: z.array(customerContactDaysOptionSchema).nullish(),
  metas: metasResponseSchema.optional(),
  children: childrenResponseSchema.optional(),
})
export type Customer = z.infer<typeof customerSchema>

// Types only: what a client should send. The schemas exported below are the server's, which also accept what it normalizes
// (numeric strings, empty values) and, on update, the read-only columns of a row fetched earlier.
const customerCreateShape = z.object({
  name: z.string(),
  account: z.union([z.number(), z.string()]),
  office: z.string(),
  phone: z.string().nullish(),
  salesRep: z.string().nullish(),
  visitDays: z.array(customerVisitDaysOptionSchema).nullish(),
  contactDays: z.array(customerContactDaysOptionSchema).nullish(),
})
const customerUpdateShape = z.object({
  name: z.string().optional(),
  account: z.union([z.number(), z.string()]).optional(),
  office: z.string().optional(),
  phone: z.string().nullish(),
  salesRep: z.string().nullish(),
  visitDays: z.array(customerVisitDaysOptionSchema).nullish(),
  contactDays: z.array(customerContactDaysOptionSchema).nullish(),
})

export type CreateCustomerInput = z.input<typeof customerCreateShape>
export const createCustomerInputSchema = customerSchemas.create as unknown as z.ZodType<CreateCustomerInput>

export type UpdateCustomerInput = z.input<typeof customerUpdateShape>
export const updateCustomerInputSchema = customerSchemas.update as unknown as z.ZodType<UpdateCustomerInput>
