// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.
// Source: @/entities/pages/pages.config

import * as z from 'zod'
import type { EntityConfig } from '../schema/types'
import { generateEntitySchemas } from '../schema/schema-generator'
import { builderBlockSchema, childrenResponseSchema, metasResponseSchema } from '../schema/response-shape'

export const pagesApiPath = '/api/v1/pages'

/** The entity as the server sees it: the request schemas below are generated from it by the server's own generator. */
export const pageEntity = {
  slug: 'pages',
  names: { singular: 'page' },
  fields: [
    { name: 'title', type: 'text', required: true, display: { label: 'Title' }, api: { readOnly: false } },
    { name: 'slug', type: 'text', required: true, display: { label: 'Slug' }, api: { readOnly: false } },
    { name: 'status', type: 'select', required: true, defaultValue: 'draft', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }, { value: 'scheduled', label: 'Scheduled' }, { value: 'archived', label: 'Archived' }], display: { label: 'Status' }, api: { readOnly: false } },
    { name: 'locale', type: 'select', required: true, defaultValue: 'en', options: [{ value: 'en', label: 'English' }, { value: 'es', label: 'Español' }], display: { label: 'Locale' }, api: { readOnly: false } },
  ],
  builder: { enabled: true },
} satisfies EntityConfig

const pageSchemas = generateEntitySchemas(pageEntity)

export const pageStatusSchema = z.enum(['draft', 'published', 'scheduled', 'archived'])
export type PageStatus = z.infer<typeof pageStatusSchema>

export const pageLocaleSchema = z.enum(['en', 'es'])
export type PageLocale = z.infer<typeof pageLocaleSchema>

export const pageSchema = z.object({
  id: z.string(),
  userId: z.string(),
  teamId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  blocks: z.array(builderBlockSchema).nullish(),
  title: z.string(),
  slug: z.string(),
  status: pageStatusSchema,
  locale: pageLocaleSchema,
  metas: metasResponseSchema.optional(),
  children: childrenResponseSchema.optional(),
})
export type Page = z.infer<typeof pageSchema>

// Types only: what a client should send. The schemas exported below are the server's, which also accept what it normalizes
// (numeric strings, empty values) and, on update, the read-only columns of a row fetched earlier.
const pageCreateShape = z.object({
  title: z.string(),
  slug: z.string(),
  status: pageStatusSchema.nullish(),
  locale: pageLocaleSchema.nullish(),
  blocks: z.unknown().optional(),
  settings: z.unknown().optional(),
})
const pageUpdateShape = z.object({
  title: z.string().optional(),
  slug: z.string().optional(),
  status: pageStatusSchema.optional(),
  locale: pageLocaleSchema.optional(),
  blocks: z.unknown().optional(),
  settings: z.unknown().optional(),
})

export type CreatePageInput = z.input<typeof pageCreateShape>
export const createPageInputSchema = pageSchemas.create as unknown as z.ZodType<CreatePageInput>

export type UpdatePageInput = z.input<typeof pageUpdateShape>
export const updatePageInputSchema = pageSchemas.update as unknown as z.ZodType<UpdatePageInput>
