// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.
// Source: @/entities/posts/posts.config

import * as z from 'zod'
import type { EntityConfig } from '../schema/types'
import { generateEntitySchemas } from '../schema/schema-generator'
import { builderBlockSchema, childrenResponseSchema, metasResponseSchema, taxonomyTermSchema } from '../schema/response-shape'
import { fileObjectSchema } from '../fields'

export const postsApiPath = '/api/v1/posts'

/** The entity as the server sees it: the request schemas below are generated from it by the server's own generator. */
export const postEntity = {
  slug: 'posts',
  names: { singular: 'post' },
  fields: [
    { name: 'title', type: 'text', required: true, display: { label: 'Title' }, api: { readOnly: false } },
    { name: 'slug', type: 'text', required: true, display: { label: 'Slug' }, api: { readOnly: false } },
    { name: 'status', type: 'select', required: true, defaultValue: 'draft', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }, { value: 'scheduled', label: 'Scheduled' }, { value: 'archived', label: 'Archived' }], display: { label: 'Status' }, api: { readOnly: false } },
    { name: 'excerpt', type: 'textarea', required: false, display: { label: 'Excerpt' }, api: { readOnly: false } },
    { name: 'featuredImage', type: 'image', required: false, display: { label: 'Featured Image' }, api: { readOnly: false } },
  ],
  builder: { enabled: true },
  taxonomies: { enabled: true, types: [{ type: 'post_category', field: 'categories' }] },
} satisfies EntityConfig

const postSchemas = generateEntitySchemas(postEntity)

export const postStatusSchema = z.enum(['draft', 'published', 'scheduled', 'archived'])
export type PostStatus = z.infer<typeof postStatusSchema>

export const postSchema = z.object({
  id: z.string(),
  userId: z.string(),
  teamId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  blocks: z.array(builderBlockSchema).nullish(),
  title: z.string(),
  slug: z.string(),
  status: postStatusSchema,
  excerpt: z.string().nullish(),
  featuredImage: z.union([z.string(), z.array(fileObjectSchema)]).nullish(),
  categories: z.array(taxonomyTermSchema),
  metas: metasResponseSchema.optional(),
  children: childrenResponseSchema.optional(),
})
export type Post = z.infer<typeof postSchema>

// Types only: what a client should send. The schemas exported below are the server's, which also accept what it normalizes
// (numeric strings, empty values) and, on update, the read-only columns of a row fetched earlier.
const postCreateShape = z.object({
  title: z.string(),
  slug: z.string(),
  status: postStatusSchema.nullish(),
  excerpt: z.string().nullish(),
  featuredImage: z.union([z.string(), z.array(fileObjectSchema)]).nullish(),
  blocks: z.unknown().optional(),
  settings: z.unknown().optional(),
})
const postUpdateShape = z.object({
  title: z.string().optional(),
  slug: z.string().optional(),
  status: postStatusSchema.optional(),
  excerpt: z.string().nullish(),
  featuredImage: z.union([z.string(), z.array(fileObjectSchema)]).nullish(),
  blocks: z.unknown().optional(),
  settings: z.unknown().optional(),
})

export type CreatePostInput = z.input<typeof postCreateShape>
export const createPostInputSchema = postSchemas.create as unknown as z.ZodType<CreatePostInput>

export type UpdatePostInput = z.input<typeof postUpdateShape>
export const updatePostInputSchema = postSchemas.update as unknown as z.ZodType<UpdatePostInput>
