// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.
// Source: @/entities/tasks/tasks.config

import * as z from 'zod'
import type { EntityConfig } from '../schema/types'
import { generateEntitySchemas } from '../schema/schema-generator'
import { childrenResponseSchema, metasResponseSchema } from '../schema/response-shape'

export const tasksApiPath = '/api/v1/tasks'

/** The entity as the server sees it: the request schemas below are generated from it by the server's own generator. */
export const taskEntity = {
  slug: 'tasks',
  names: { singular: 'task' },
  fields: [
    { name: 'title', type: 'text', required: true, display: { label: 'Title' }, api: { readOnly: false } },
    { name: 'description', type: 'textarea', required: false, display: { label: 'Description' }, api: { readOnly: false } },
    { name: 'status', type: 'select', required: false, defaultValue: 'todo', options: [{ value: 'todo', label: 'To Do' }, { value: 'in-progress', label: 'In Progress' }, { value: 'review', label: 'In Review' }, { value: 'done', label: 'Done' }, { value: 'blocked', label: 'Blocked' }], display: { label: 'Status' }, api: { readOnly: false } },
    { name: 'priority', type: 'select', required: false, defaultValue: 'medium', options: [{ value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'urgent', label: 'Urgent' }], display: { label: 'Priority' }, api: { readOnly: false } },
    { name: 'tags', type: 'tags', required: false, display: { label: 'Tags' }, api: { readOnly: false } },
    { name: 'dueDate', type: 'date', required: false, display: { label: 'Due Date' }, api: { readOnly: false } },
    { name: 'estimatedHours', type: 'number', required: false, display: { label: 'Estimated Hours' }, api: { readOnly: false } },
    { name: 'completed', type: 'boolean', required: false, defaultValue: false, display: { label: 'Completed' }, api: { readOnly: false } },
  ],
} satisfies EntityConfig

const taskSchemas = generateEntitySchemas(taskEntity)

export const taskStatusSchema = z.enum(['todo', 'in-progress', 'review', 'done', 'blocked'])
export type TaskStatus = z.infer<typeof taskStatusSchema>

export const taskPrioritySchema = z.enum(['low', 'medium', 'high', 'urgent'])
export type TaskPriority = z.infer<typeof taskPrioritySchema>

export const taskSchema = z.object({
  id: z.string(),
  userId: z.string(),
  teamId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  title: z.string(),
  description: z.string().nullish(),
  status: taskStatusSchema,
  priority: taskPrioritySchema,
  tags: z.array(z.string()).nullish(),
  dueDate: z.string().nullish(),
  estimatedHours: z.string().nullish(),
  completed: z.boolean(),
  metas: metasResponseSchema.optional(),
  children: childrenResponseSchema.optional(),
})
export type Task = z.infer<typeof taskSchema>

// Types only: what a client should send. The schemas exported below are the server's, which also accept what it normalizes
// (numeric strings, empty values) and, on update, the read-only columns of a row fetched earlier.
const taskCreateShape = z.object({
  title: z.string(),
  description: z.string().nullish(),
  status: taskStatusSchema.nullish(),
  priority: taskPrioritySchema.nullish(),
  tags: z.array(z.string()).nullish(),
  dueDate: z.string().nullish(),
  estimatedHours: z.union([z.number(), z.string()]).nullish(),
  completed: z.boolean().nullish(),
})
const taskUpdateShape = z.object({
  title: z.string().optional(),
  description: z.string().nullish(),
  status: taskStatusSchema.nullish(),
  priority: taskPrioritySchema.nullish(),
  tags: z.array(z.string()).nullish(),
  dueDate: z.string().nullish(),
  estimatedHours: z.union([z.number(), z.string()]).nullish(),
  completed: z.boolean().nullish(),
})

export type CreateTaskInput = z.input<typeof taskCreateShape>
export const createTaskInputSchema = taskSchemas.create as unknown as z.ZodType<CreateTaskInput>

export type UpdateTaskInput = z.input<typeof taskUpdateShape>
export const updateTaskInputSchema = taskSchemas.update as unknown as z.ZodType<UpdateTaskInput>
