-- ============================================================================
-- Sample data for activities table - CRM Theme
-- Aligned with schema in 001_activities_table.sql
-- Uses users from 999_theme_sample_data.sql
-- References leads, contacts, companies, opportunities from their sample data
-- ============================================================================

-- Clean existing activities data
DELETE FROM "activities" WHERE "teamId" = 'team-crm-company';

INSERT INTO "activities" (
  id,
  type,
  subject,
  description,
  status,
  priority,
  "dueDate",
  "completedAt",
  duration,
  outcome,
  location,
  "contactId",
  "companyId",
  "opportunityId",
  "assignedTo",
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Call Activities
(
  'act-crm-001',
  'call',
  'Initial Discovery Call with Amanda Davis',
  'First contact call to understand CEO needs at TechnoSoft Solutions. Discussed current pain points with their existing system and timeline for new CRM implementation.',
  'completed',
  'high',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days',
  45,
  'Successful - Very interested in enterprise solution',
  NULL,
  'contact-crm-001',
  'company-crm-001',
  NULL,
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '3 days'
),
(
  'act-crm-002',
  'call',
  'Technical Requirements Call with Dr. Martinez',
  'Detailed discussion about HIPAA compliance requirements and data security measures needed for healthcare implementation.',
  'completed',
  'high',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day',
  75,
  'Successful - Needs security documentation',
  NULL,
  'contact-crm-006',
  'company-crm-003',
  NULL,
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-003',
  'call',
  'Startup Package Discussion with StartupTech',
  'Discuss startup-friendly pricing and phased implementation approach for growing company needs.',
  'scheduled',
  'high',
  NOW() + INTERVAL '1 day',
  NULL,
  45,
  NULL,
  NULL,
  'contact-crm-014',
  'company-crm-007',
  NULL,
  'usr-crm-sales-rep',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),

-- Email Activities
(
  'act-crm-004',
  'email',
  'Follow-up Email to John Patterson',
  'Sent detailed proposal and pricing information for enterprise CRM solution. Included case studies from similar manufacturing companies.',
  'completed',
  'high',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day',
  30,
  'Successful - Proposal received positively',
  NULL,
  'contact-crm-004',
  'company-crm-002',
  'opp-crm-003',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-005',
  'email',
  'Security Assessment Results to Elizabeth Taylor',
  'Shared comprehensive security assessment results and compliance documentation required for FinanceFirst implementation.',
  'completed',
  'high',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days',
  45,
  'Successful - Moved to technical review',
  NULL,
  'contact-crm-008',
  'company-crm-004',
  'opp-crm-007',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '5 days'
),

-- Meeting Activities
(
  'act-crm-006',
  'meeting',
  'Quarterly Business Review with Amanda Davis',
  'Regular QBR to discuss CRM performance, new feature requests, and expansion opportunities at TechnoSoft Solutions.',
  'completed',
  'medium',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '7 days',
  90,
  'Successful - Expansion opportunity identified',
  'TechnoSoft HQ, San Francisco',
  'contact-crm-001',
  'company-crm-001',
  NULL,
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '7 days'
),
(
  'act-crm-007',
  'meeting',
  'Implementation Kickoff with Global Manufacturing',
  'Project kickoff meeting to establish timeline, roles, and data migration plan for enterprise CRM implementation.',
  'completed',
  'high',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '10 days',
  120,
  'Successful - Project plan approved',
  'Global Manufacturing HQ, Detroit',
  'contact-crm-004',
  'company-crm-002',
  'opp-crm-003',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '10 days'
),
(
  'act-crm-008',
  'meeting',
  'Training Session Planning for FinanceFirst',
  'Planning session for comprehensive user training program including role-based training modules and certification process.',
  'scheduled',
  'medium',
  NOW() + INTERVAL '7 days',
  NULL,
  120,
  NULL,
  'FinanceFirst Tower, New York',
  'contact-crm-008',
  'company-crm-004',
  'opp-crm-007',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),

-- Demo Activities
(
  'act-crm-009',
  'demo',
  'Demo Presentation for Patricia Martinez',
  'Scheduled product demonstration focusing on healthcare compliance features and integration capabilities with existing systems.',
  'scheduled',
  'high',
  NOW() + INTERVAL '2 days',
  NULL,
  60,
  NULL,
  'Virtual - Zoom',
  'contact-crm-006',
  'company-crm-003',
  'opp-crm-005',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-010',
  'demo',
  'Product Demo for Maria Gonzalez',
  'Customized demo focusing on educational features, student data management, and parent communication tools.',
  'scheduled',
  'medium',
  NOW() + INTERVAL '1 day',
  NULL,
  60,
  NULL,
  'Virtual - Teams',
  'contact-crm-010',
  'company-crm-005',
  'opp-crm-008',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-011',
  'demo',
  'Educational CRM Demo for EduTech',
  'Customized demonstration showing student lifecycle management, parent communication, and academic tracking features.',
  'scheduled',
  'medium',
  NOW() + INTERVAL '3 days',
  NULL,
  90,
  NULL,
  'Virtual - Google Meet',
  'contact-crm-010',
  'company-crm-005',
  'opp-crm-008',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),

-- Task Activities
(
  'act-crm-012',
  'task',
  'Prepare Custom Proposal for Healthcare Innovations',
  'Create customized proposal addressing healthcare specific needs including HIPAA compliance and EMR integration.',
  'in_progress',
  'high',
  NOW() + INTERVAL '3 days',
  NULL,
  120,
  NULL,
  NULL,
  NULL,
  'company-crm-003',
  'opp-crm-005',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-013',
  'task',
  'Contract Renewal Preparation for TechnoSoft',
  'Prepare renewal proposal with additional modules and expansion options based on current usage and growth projections.',
  'in_progress',
  'high',
  NOW() + INTERVAL '15 days',
  NULL,
  180,
  NULL,
  NULL,
  NULL,
  'company-crm-001',
  'opp-crm-001',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '2 days'
),
(
  'act-crm-014',
  'task',
  'RetailMax Integration Documentation',
  'Prepare integration documentation for connecting CRM with existing POS and inventory management systems.',
  'in_progress',
  'medium',
  NOW() + INTERVAL '10 days',
  NULL,
  300,
  NULL,
  NULL,
  'contact-crm-012',
  'company-crm-006',
  'opp-crm-009',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '2 days'
),
(
  'act-crm-015',
  'task',
  'Healthcare ROI Analysis Preparation',
  'Prepare detailed ROI analysis showing cost savings and efficiency gains from CRM implementation in healthcare setting.',
  'in_progress',
  'medium',
  NOW() + INTERVAL '5 days',
  NULL,
  180,
  NULL,
  NULL,
  NULL,
  'company-crm-003',
  'opp-crm-005',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),

-- Follow-up Activities
(
  'act-crm-016',
  'follow_up',
  'Healthcare Compliance Follow-up',
  'Follow-up on compliance questions raised during initial presentation. Research additional healthcare-specific features.',
  'completed',
  'medium',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days',
  60,
  'Partially successful - Additional docs needed',
  NULL,
  'contact-crm-006',
  'company-crm-003',
  'opp-crm-005',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '2 days'
),
(
  'act-crm-017',
  'follow_up',
  'EduTech Implementation Status Check',
  'Regular check-in to monitor implementation progress and address any technical challenges or user adoption issues.',
  'scheduled',
  'medium',
  NOW() + INTERVAL '14 days',
  NULL,
  45,
  NULL,
  NULL,
  'contact-crm-010',
  'company-crm-005',
  'opp-crm-008',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '1 day'
),
(
  'act-crm-018',
  'follow_up',
  'Startup Growth Strategy Call',
  'Strategic call to discuss how CRM can support rapid growth phase and scaling challenges at StartupTech.',
  'scheduled',
  'high',
  NOW() + INTERVAL '4 days',
  NULL,
  60,
  NULL,
  NULL,
  'contact-crm-014',
  'company-crm-007',
  'opp-crm-010',
  'usr-crm-sales-rep',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
);
