/**
 * Leads Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the leads entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const leadsFields: EntityField[] = [
  {
    name: 'companyName',
    type: 'text',
    required: true,
    display: {
      label: 'Company Name',
      description: 'Name of the prospect company',
      placeholder: 'Enter company name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'contactName',
    type: 'text',
    required: true,
    display: {
      label: 'Contact Name',
      description: 'Name of the contact person',
      placeholder: 'Enter contact name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'email',
    type: 'email',
    required: true,
    display: {
      label: 'Email',
      description: 'Email address',
      placeholder: 'Enter email address...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'phone',
    type: 'text',
    required: false,
    display: {
      label: 'Phone',
      description: 'Phone number',
      placeholder: 'Enter phone number...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'website',
    type: 'url',
    required: false,
    display: {
      label: 'Website',
      description: 'Company website',
      placeholder: 'https://example.com',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'source',
    type: 'select',
    required: false,
    options: [
      { value: 'web', label: 'Website' },
      { value: 'referral', label: 'Referral' },
      { value: 'cold_call', label: 'Cold Call' },
      { value: 'trade_show', label: 'Trade Show' },
      { value: 'social_media', label: 'Social Media' },
      { value: 'email', label: 'Email' },
      { value: 'advertising', label: 'Advertising' },
      { value: 'partner', label: 'Partner' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Lead Source',
      description: 'How this lead was acquired',
      placeholder: 'Select source...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'status',
    type: 'select',
    required: false,
    options: [
      { value: 'new', label: 'New' },
      { value: 'contacted', label: 'Contacted' },
      { value: 'qualified', label: 'Qualified' },
      { value: 'proposal', label: 'Proposal' },
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'converted', label: 'Converted' },
      { value: 'lost', label: 'Lost' },
    ],
    display: {
      label: 'Status',
      description: 'Current lead status',
      placeholder: 'Select status...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'score',
    type: 'number',
    required: false,
    display: {
      label: 'Lead Score',
      description: 'Lead score from 0 to 100',
      placeholder: '0',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'industry',
    type: 'text',
    required: false,
    display: {
      label: 'Industry',
      description: 'Industry sector',
      placeholder: 'Enter industry...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'companySize',
    type: 'select',
    required: false,
    options: [
      { value: '1-10', label: '1-10 employees' },
      { value: '11-50', label: '11-50 employees' },
      { value: '51-200', label: '51-200 employees' },
      { value: '201-500', label: '201-500 employees' },
      { value: '500+', label: '500+ employees' },
    ],
    display: {
      label: 'Company Size',
      description: 'Number of employees',
      placeholder: 'Select company size...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'budget',
    type: 'number',
    required: false,
    display: {
      label: 'Estimated Budget',
      description: 'Estimated budget amount',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'assignedTo',
    type: 'user',
    required: false,
    display: {
      label: 'Assigned To',
      description: 'Sales rep assigned to this lead',
      placeholder: 'Select user...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'notes',
    type: 'textarea',
    required: false,
    display: {
      label: 'Notes',
      description: 'Internal notes about the lead',
      placeholder: 'Enter notes...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 12,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the lead was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the lead was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]