/**
 * Settings Selectors
 *
 * Selectors for the settings area:
 * - Layout and sidebar
 * - Profile settings
 * - Password settings
 * - Team settings
 * - Members management
 * - Billing
 * - API Keys
 * - Notifications
 */

export const SETTINGS_SELECTORS = {
  layout: {
    main: 'settings-layout-main',
    nav: 'settings-layout-nav',
    backToDashboard: 'settings-layout-back-to-dashboard',
    header: 'settings-layout-header',
    contentArea: 'settings-layout-content-area',
    sidebar: 'settings-layout-sidebar',
    pageContent: 'settings-layout-page-content',
  },
  sidebar: {
    main: 'settings-sidebar-main',
    header: 'settings-sidebar-header',
    navItems: 'settings-sidebar-nav-items',
    navItem: 'settings-sidebar-nav-{section}',
  },
  overview: {
    container: 'settings-overview',
    item: 'settings-overview-{key}',
  },
  profile: {
    container: 'settings-profile',
    form: 'profile-form',
    avatar: 'profile-avatar',
    avatarUpload: 'profile-avatar-upload',
    firstName: 'profile-first-name',
    lastName: 'profile-last-name',
    email: 'profile-email',
    submitButton: 'profile-submit',
    successMessage: 'profile-success',
  },
  password: {
    container: 'settings-password',
    form: 'password-form',
    currentPassword: 'password-current',
    newPassword: 'password-new',
    confirmPassword: 'password-confirm',
    submitButton: 'password-submit',
    successMessage: 'password-success',
  },
  team: {
    container: 'settings-team',
    name: 'team-name',
    slug: 'team-slug',
    description: 'team-description',
    avatar: 'team-avatar',
    avatarUpload: 'team-avatar-upload',
    submitButton: 'team-submit',
    deleteButton: 'team-delete',
    deleteDialog: 'team-delete-dialog',
    deleteConfirm: 'team-delete-confirm',
  },
  members: {
    container: 'settings-members',
    inviteButton: 'members-invite',
    inviteDialog: 'members-invite-dialog',
    inviteEmail: 'members-invite-email',
    inviteRole: 'members-invite-role',
    inviteSubmit: 'members-invite-submit',
    memberRow: 'member-row-{id}',
    memberRole: 'member-role-{id}',
    memberRemove: 'member-remove-{id}',
    pendingInvites: 'members-pending-invites',
    pendingInvite: 'pending-invite-{id}',
    cancelInvite: 'cancel-invite-{id}',
  },
  billing: {
    container: 'settings-billing',
    main: 'billing-main',
    header: 'billing-header',
    currentPlan: 'billing-current-plan',
    upgradeButton: 'billing-upgrade',
    upgradePlan: 'billing-upgrade-plan',
    cancelButton: 'billing-cancel',
    addPayment: 'billing-add-payment',
    invoicesTable: 'billing-invoices',
    invoicesTableAlt: 'invoices-table',
    invoiceRow: 'invoice-row-{id}',
    invoicesRow: 'invoices-row',
    invoiceDownload: 'invoice-download-{id}',
    invoicesLoadMore: 'invoices-load-more',
    invoiceStatusBadge: 'invoice-status-badge',
    paymentMethod: 'billing-payment-method',
    paymentMethodAlt: 'payment-method',
    updatePayment: 'billing-update-payment',
    usage: 'billing-usage',
    usageDashboard: 'usage-dashboard',
  },
  pricing: {
    table: 'pricing-table',
    settingsTable: 'pricing-settings-table',
  },
  features: {
    placeholder: 'feature-placeholder-{feature}',
    content: '{feature}-content',
    placeholderUpgradeBtn: 'placeholder-upgrade-btn',
  },
  apiKeys: {
    page: 'api-keys-page',
    title: 'api-keys-title',
    container: 'settings-api-keys',
    createButton: 'api-keys-create-button',
    createDialog: 'api-keys-create-dialog',
    list: 'api-keys-list',
    skeleton: 'api-keys-skeleton',
    empty: 'api-keys-empty',
    emptyCreateButton: 'api-keys-empty-create-button',
    keyName: 'api-key-name',
    keyScopes: 'api-key-scopes',
    scopeOption: 'api-key-scope-{scope}',
    createSubmit: 'api-key-create-submit',
    keyRow: 'api-key-row-{id}',
    keyName_: 'api-keys-name-{id}',
    keyPrefix: 'api-keys-prefix-{id}',
    copyPrefix: 'api-keys-copy-prefix-{id}',
    keyStatus: 'api-keys-status-{id}',
    statusBadge: 'api-keys-status-badge-{id}',
    menuTrigger: 'api-keys-menu-trigger-{id}',
    menu: 'api-keys-menu-{id}',
    viewDetails: 'api-keys-view-details-{id}',
    toggle: 'api-keys-toggle-{id}',
    revoke: 'api-keys-revoke-{id}',
    scopes: 'api-keys-scopes-{id}',
    scope: 'api-keys-scope-{id}-{scope}',
    stats: 'api-keys-stats-{id}',
    totalRequests: 'api-keys-total-requests-{id}',
    last24h: 'api-keys-last-24h-{id}',
    avgTime: 'api-keys-avg-time-{id}',
    metadata: 'api-keys-metadata-{id}',
    createdAt: 'api-keys-created-at-{id}',
    lastUsed: 'api-keys-last-used-{id}',
    expiresAt: 'api-keys-expires-at-{id}',
    detailsDialog: 'api-keys-details-dialog',
    detailsTitle: 'api-keys-details-title',
    detailsLoading: 'api-keys-details-loading',
    detailsContent: 'api-keys-details-content',
    detailsBasicInfo: 'api-keys-details-basic-info',
    detailsName: 'api-keys-details-name',
    detailsStatus: 'api-keys-details-status',
    detailsStats: 'api-keys-details-stats',
    detailsTotalRequests: 'api-keys-details-total-requests',
    detailsLast24h: 'api-keys-details-last-24h',
    detailsLast7d: 'api-keys-details-last-7d',
    detailsLast30d: 'api-keys-details-last-30d',
    detailsAvgTime: 'api-keys-details-avg-time',
    detailsSuccessRate: 'api-keys-details-success-rate',
    keyReveal: 'api-key-reveal-{id}',
    keyRevoke: 'api-key-revoke-{id}',
    revokeDialog: 'api-key-revoke-dialog',
    revokeConfirm: 'api-key-revoke-confirm',
    newKeyDisplay: 'api-key-new-display',
    copyKey: 'api-key-copy',
    dialogFooter: 'api-keys-dialog-footer',
  },
  notifications: {
    container: 'settings-notifications',
    emailToggle: 'notifications-email',
    pushToggle: 'notifications-push',
    category: 'notifications-{category}',
    submitButton: 'notifications-submit',
  },
  teams: {
    main: 'teams-settings-main',
    header: 'teams-settings-header',
    loading: 'teams-settings-loading',
    singleUser: 'teams-settings-single-user',
    teamsList: 'teams-settings-teams-list',
    teamDetails: 'teams-settings-team-details',
  },
  plans: {
    main: 'plans-settings-main',
    header: 'plans-settings-header',
    table: 'plans-settings-table',
  },
} as const

export type SettingsSelectorsType = typeof SETTINGS_SELECTORS
