import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import chalk from 'chalk';
import ora from 'ora';
import { runWizard } from '../wizard/index.js';
import type { CLIOptions, WizardMode, PresetName, ThemeOption, PluginOption, ProjectType } from '../wizard/types.js';

interface InitOptions {
  force?: boolean;
  wizard?: boolean;
  quick?: boolean;
  expert?: boolean;
  preset?: string;
  theme?: string;
  plugins?: string;
  yes?: boolean;
  registriesOnly?: boolean;
  name?: string;
  slug?: string;
  description?: string;
  type?: string;
}

/**
 * Determine wizard mode from options
 */
function getWizardMode(options: InitOptions): WizardMode {
  if (options.quick) return 'quick';
  if (options.expert) return 'expert';
  return 'interactive';
}

/**
 * Parse plugins from comma-separated string
 */
function parsePlugins(pluginsStr: string | undefined): PluginOption[] | undefined {
  if (!pluginsStr) return undefined;
  return pluginsStr.split(',').map(p => p.trim()) as PluginOption[];
}

/**
 * Check if this is an existing NextSpark project
 */
function hasExistingProject(): boolean {
  const projectRoot = process.cwd();
  // Check for contents/ directory or .nextspark/ directory
  return existsSync(join(projectRoot, 'contents')) ||
         existsSync(join(projectRoot, '.nextspark'));
}

/**
 * Generate initial empty registries with valid structure
 */
function generateInitialRegistries(registriesDir: string): void {
  // Block Registry
  writeFileSync(join(registriesDir, 'block-registry.ts'), `// Auto-generated by nextspark init
import type { ComponentType } from 'react'

export const BLOCK_REGISTRY: Record<string, {
  name: string
  slug: string
  componentPath: string
  fields?: unknown[]
  examples?: unknown[]
}> = {}

export const BLOCK_COMPONENTS: Record<string, React.LazyExoticComponent<ComponentType<any>>> = {}
`);

  // Theme Registry
  writeFileSync(join(registriesDir, 'theme-registry.ts'), `// Auto-generated by nextspark init
export const THEME_REGISTRY: Record<string, unknown> = {}
`);

  // Entity Registry
  writeFileSync(join(registriesDir, 'entity-registry.ts'), `// Auto-generated by nextspark init
export const ENTITY_REGISTRY: Record<string, unknown> = {}
`);

  writeFileSync(join(registriesDir, 'entity-registry.client.ts'), `// Auto-generated by nextspark init
export const CLIENT_ENTITY_REGISTRY: Record<string, unknown> = {}
export function parseChildEntity(path: string) { return null }
export function getEntityApiPath(entity: string) { return \`/api/\${entity}\` }
export function clientMetaSystemAdapter() { return {} }
export type ClientEntityConfig = Record<string, unknown>
`);

  // Billing Registry
  writeFileSync(join(registriesDir, 'billing-registry.ts'), `// Auto-generated by nextspark init
export const BILLING_REGISTRY = { plans: [], features: [] }
`);

  // Plugin Registry
  writeFileSync(join(registriesDir, 'plugin-registry.ts'), `// Auto-generated by nextspark init
export const PLUGIN_REGISTRY: Record<string, unknown> = {}
`);

  // Testing Registry
  writeFileSync(join(registriesDir, 'testing-registry.ts'), `// Auto-generated by nextspark init
export const FLOW_REGISTRY: Record<string, unknown> = {}
export const FEATURE_REGISTRY: Record<string, unknown> = {}
export const TAGS_REGISTRY: Record<string, unknown> = {}
export const COVERAGE_SUMMARY = { total: 0, covered: 0 }
export type FlowEntry = unknown
export type FeatureEntry = unknown
`);

  // Docs Registry
  writeFileSync(join(registriesDir, 'docs-registry.ts'), `// Auto-generated by nextspark init
export const DOCS_REGISTRY = { sections: [], pages: [] }
export type DocSectionMeta = { title: string; slug: string }
`);

  // Index
  writeFileSync(join(registriesDir, 'index.ts'), `// Auto-generated by nextspark init
export * from './block-registry'
export * from './theme-registry'
export * from './entity-registry'
export * from './entity-registry.client'
export * from './billing-registry'
export * from './plugin-registry'
export * from './testing-registry'
export * from './docs-registry'
`);
}

/**
 * Simple init - only create registries
 */
async function simpleInit(options: InitOptions): Promise<void> {
  const spinner = ora('Initializing NextSpark project...').start();
  const projectRoot = process.cwd();

  try {
    // 1. Create .nextspark/registries directory
    const nextspark = join(projectRoot, '.nextspark');
    const registriesDir = join(nextspark, 'registries');

    if (!existsSync(registriesDir) || options.force) {
      mkdirSync(registriesDir, { recursive: true });
      spinner.text = 'Creating .nextspark/registries/';

      // 2. Generate initial registries
      generateInitialRegistries(registriesDir);
      spinner.text = 'Generated initial registries';
    }

    // 3. Create/update tsconfig.json paths
    const tsconfigPath = join(projectRoot, 'tsconfig.json');
    if (existsSync(tsconfigPath)) {
      spinner.text = 'Updating tsconfig.json paths...';
      const tsconfig = JSON.parse(readFileSync(tsconfigPath, 'utf-8'));
      tsconfig.compilerOptions = tsconfig.compilerOptions || {};
      tsconfig.compilerOptions.paths = {
        ...tsconfig.compilerOptions.paths,
        "@nextsparkjs/registries": ["./.nextspark/registries/index.ts"],
        "@nextsparkjs/registries/*": ["./.nextspark/registries/*"],
      };
      writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2));
    }

    // 4. Create .env.example if not exists
    const envExample = join(projectRoot, '.env.example');
    if (!existsSync(envExample)) {
      const envContent = `# NextSpark Configuration
DATABASE_URL="postgresql://user:password@localhost:5432/db"
BETTER_AUTH_SECRET="your-secret-here-min-32-chars"
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
`;
      writeFileSync(envExample, envContent);
      spinner.text = 'Created .env.example';
    }

    spinner.succeed('NextSpark initialized successfully!');

    console.log(chalk.blue('\nNext steps:'));
    console.log('  1. Copy .env.example to .env and configure');
    console.log('  2. Run: nextspark generate');
    console.log('  3. Run: nextspark dev');

  } catch (error) {
    spinner.fail('Initialization failed');
    if (error instanceof Error) {
      console.error(chalk.red(error.message));
    }
    process.exit(1);
  }
}

/**
 * Main init command handler
 */
export async function initCommand(options: InitOptions): Promise<void> {
  // If --registries-only or existing project without --wizard flag, do simple init
  if (options.registriesOnly) {
    await simpleInit(options);
    return;
  }

  // If existing project and not explicitly requesting wizard
  if (hasExistingProject() && !options.wizard && !options.preset && !options.theme) {
    console.log(chalk.yellow('Existing NextSpark project detected.'));
    console.log(chalk.gray('Use --wizard to run the full wizard, or --registries-only for just registries.'));
    await simpleInit(options);
    return;
  }

  // Run the full wizard
  const wizardOptions: CLIOptions = {
    mode: getWizardMode(options),
    preset: options.preset as PresetName | undefined,
    theme: options.theme as ThemeOption | undefined,
    plugins: parsePlugins(options.plugins),
    yes: options.yes,
    name: options.name,
    slug: options.slug,
    description: options.description,
    type: options.type as ProjectType | undefined,
  };

  await runWizard(wizardOptions);
}
