/**
 * Template page - directly imports from theme
 * Template: app/(public)/blog/[slug]/page.d.ts
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/(public)/blog/[slug]/page.d'

// Direct export of the theme template (no fallback)
export default TemplateComponent
