/**
 * Template page - directly imports from theme
 * Template: app/(public)/blog/[slug]/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/(public)/blog/[slug]/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent

// Re-export Next.js route-level exports from the theme template
export { generateMetadata, revalidate } from '@/contents/themes/default/templates/(public)/blog/[slug]/page'
