-- ============================================================================
-- Sample data for companies table - CRM Theme
-- Aligned with schema in 001_companies_table.sql
-- Uses users from 999_theme_sample_data.sql
-- ============================================================================

-- Clean existing companies data
DELETE FROM "companies" WHERE "teamId" = 'team-crm-company';

INSERT INTO "companies" (
  id,
  name,
  "legalName",
  "taxId",
  website,
  email,
  phone,
  industry,
  type,
  size,
  "annualRevenue",
  rating,
  address,
  city,
  state,
  country,
  "postalCode",
  logo,
  linkedin,
  "assignedTo",
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Technology Companies (Hot/Warm)
(
  'company-crm-001',
  'TechnoSoft Solutions',
  'TechnoSoft Solutions Inc.',
  'TS-2024-001',
  'https://technosoft.com',
  'info@technosoft.com',
  '+1-555-0101',
  'Software Development',
  'customer',
  '51-200',
  2500000.00,
  'hot',
  '123 Innovation Drive',
  'San Francisco',
  'CA',
  'US',
  '94105',
  'https://technosoft.com/logo.png',
  'https://linkedin.com/company/technosoft',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '45 days',
  NOW() - INTERVAL '3 days'
),
(
  'company-crm-002',
  'Global Manufacturing Corp',
  'Global Manufacturing Corporation',
  'GM-2024-002',
  'https://globalmanufacturing.com',
  'contact@globalmanufacturing.com',
  '+1-555-0102',
  'Manufacturing',
  'customer',
  '500+',
  15000000.00,
  'warm',
  '456 Industrial Blvd',
  'Detroit',
  'MI',
  'US',
  '48201',
  'https://globalmanufacturing.com/logo.png',
  'https://linkedin.com/company/global-manufacturing',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '10 days'
),
(
  'company-crm-003',
  'Healthcare Innovations Ltd',
  'Healthcare Innovations Limited',
  'HI-2024-003',
  'https://healthcareinnovations.com',
  'hello@healthcareinnovations.com',
  '+1-555-0103',
  'Healthcare',
  'prospect',
  '201-500',
  8500000.00,
  'hot',
  '789 Medical Center Dr',
  'Boston',
  'MA',
  'US',
  '02101',
  'https://healthcareinnovations.com/logo.png',
  'https://linkedin.com/company/healthcare-innovations',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '30 days',
  NOW() - INTERVAL '2 days'
),
(
  'company-crm-004',
  'FinanceFirst Bank',
  'FinanceFirst Banking Corporation',
  'FF-2024-004',
  'https://financefirst.com',
  'business@financefirst.com',
  '+1-555-0104',
  'Financial Services',
  'customer',
  '500+',
  45000000.00,
  'warm',
  '321 Financial Plaza',
  'New York',
  'NY',
  'US',
  '10001',
  'https://financefirst.com/logo.png',
  'https://linkedin.com/company/financefirst',
  'usr-crm-sales-rep',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '15 days'
),
(
  'company-crm-005',
  'EduTech Academy',
  'Educational Technology Academy Inc.',
  'ET-2024-005',
  'https://edutech-academy.com',
  'partnerships@edutech-academy.com',
  '+1-555-0105',
  'Education Technology',
  'prospect',
  '51-200',
  3200000.00,
  'hot',
  '654 Learning Way',
  'Austin',
  'TX',
  'US',
  '73301',
  'https://edutech-academy.com/logo.png',
  'https://linkedin.com/company/edutech-academy',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '1 day'
),
(
  'company-crm-006',
  'RetailMax Chain',
  'RetailMax Chain Stores LLC',
  'RM-2024-006',
  'https://retailmax.com',
  'corporate@retailmax.com',
  '+1-555-0106',
  'Retail',
  'partner',
  '500+',
  12000000.00,
  'warm',
  '987 Commerce Street',
  'Chicago',
  'IL',
  'US',
  '60601',
  'https://retailmax.com/logo.png',
  'https://linkedin.com/company/retailmax',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '90 days',
  NOW() - INTERVAL '7 days'
),

-- Smaller Companies (Prospects)
(
  'company-crm-007',
  'StartupTech Inc',
  'StartupTech Incorporated',
  'ST-2024-007',
  'https://startuptech.io',
  'founders@startuptech.io',
  '+1-555-0107',
  'Technology Startup',
  'prospect',
  '11-50',
  500000.00,
  'hot',
  '159 Startup Lane',
  'Palo Alto',
  'CA',
  'US',
  '94301',
  'https://startuptech.io/logo.png',
  'https://linkedin.com/company/startuptech',
  'usr-crm-sales-rep',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '1 day'
),
(
  'company-crm-008',
  'Local Consulting Group',
  'Local Consulting Group LLC',
  'LC-2024-008',
  'https://localconsulting.com',
  'info@localconsulting.com',
  '+1-555-0108',
  'Management Consulting',
  'prospect',
  '11-50',
  1200000.00,
  'warm',
  '753 Business Park Dr',
  'Seattle',
  'WA',
  'US',
  '98101',
  'https://localconsulting.com/logo.png',
  'https://linkedin.com/company/local-consulting',
  'usr-crm-sales-rep',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '40 days',
  NOW() - INTERVAL '5 days'
);
