/**
 * Template page - directly imports from theme
 * Template: app/dashboard/(main)/posts/create/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/blog/templates/dashboard/(main)/posts/create/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
