packages:
  - 'packages/*'
  - 'apps/dev'          # Explicit - only dev app
  - 'plugins/*'
  - 'themes/*'
  # apps/mobile is intentionally OUTSIDE the pnpm workspace
  # to avoid conflicts with Tailwind v4 and other web dependencies
