-- Starter Theme: Sample Users for Development
-- These users work with the DevKeyring for quick login during development

-- Note: Core users (superadmin, developer) are created by core migrations
-- This file creates theme-specific demo users

-- Insert sample users for the starter theme
-- Password: Test1234 (hashed)
INSERT INTO "user" (id, name, email, email_verified, created_at, updated_at)
VALUES
  ('starter-owner-001', 'Owner User', 'owner@starter.dev', true, NOW(), NOW()),
  ('starter-admin-001', 'Admin User', 'admin@starter.dev', true, NOW(), NOW()),
  ('starter-member-001', 'Member User', 'member@starter.dev', true, NOW(), NOW())
ON CONFLICT (email) DO NOTHING;

-- Note: Actual password hashes should be generated by the auth system
-- The DevKeyring handles authentication in development mode
