import type { BlockExample } from '@nextsparkjs/core/types/blocks'

export const examples: BlockExample[] = [
  {
    name: 'Standard',
    description: 'Three-tier pricing without highlight',
    props: {
      title: 'Simple, Transparent Pricing',
      content: 'Choose the plan that fits your needs. All plans include 14-day free trial.',
      backgroundColor: 'white',
      columns: '3',
      highlightPopular: false,
      plans: [
        {
          name: 'Starter',
          price: '$29',
          period: 'per month',
          description: 'Perfect for small teams',
          features: 'Up to 5 team members\n10GB storage\nEmail support\nBasic analytics',
          ctaText: 'Start Free Trial',
          ctaUrl: '/signup?plan=starter',
          isPopular: false,
          isDisabled: false,
        },
        {
          name: 'Professional',
          price: '$99',
          period: 'per month',
          description: 'For growing businesses',
          features: 'Up to 25 team members\n100GB storage\nPriority support\nAdvanced analytics\nCustom integrations',
          ctaText: 'Start Free Trial',
          ctaUrl: '/signup?plan=pro',
          isPopular: false,
          isDisabled: false,
        },
        {
          name: 'Enterprise',
          price: 'Custom',
          period: '',
          description: 'For large organizations',
          features: 'Unlimited team members\nUnlimited storage\n24/7 dedicated support\nCustom analytics\nAPI access\nSSO & SAML',
          ctaText: 'Contact Sales',
          ctaUrl: '/contact',
          isPopular: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: 'With Highlight',
    description: 'Pricing with highlighted popular plan',
    props: {
      title: 'Pricing That Grows With You',
      content: 'Start free, upgrade when you need more',
      backgroundColor: 'gray-50',
      columns: '3',
      highlightPopular: true,
      plans: [
        {
          name: 'Basic',
          price: '$0',
          period: 'forever free',
          description: 'Get started at no cost',
          features: 'Up to 3 team members\n5GB storage\nCommunity support\nBasic features',
          ctaText: 'Get Started',
          ctaUrl: '/signup?plan=basic',
          isPopular: false,
          isDisabled: false,
        },
        {
          name: 'Pro',
          price: '$49',
          period: 'per month',
          description: 'Most popular choice',
          features: 'Up to 15 team members\n50GB storage\nPriority support\nAll features\nAdvanced analytics\nIntegrations',
          ctaText: 'Start Free Trial',
          ctaUrl: '/signup?plan=pro',
          isPopular: true,
          isDisabled: false,
        },
        {
          name: 'Business',
          price: '$199',
          period: 'per month',
          description: 'For serious teams',
          features: 'Unlimited team members\n500GB storage\n24/7 support\nAll Pro features\nCustom workflows\nDedicated manager',
          ctaText: 'Start Free Trial',
          ctaUrl: '/signup?plan=business',
          isPopular: false,
          isDisabled: false,
        },
      ],
    },
  },
]
