-- ============================================================================
-- Sample data for campaigns table - CRM Theme
-- Aligned with schema in 001_campaigns_table.sql
-- Uses users from 999_theme_sample_data.sql
-- ============================================================================

-- Clean existing campaigns data
DELETE FROM "campaigns" WHERE "teamId" = 'team-crm-company';

INSERT INTO "campaigns" (
  id,
  name,
  type,
  status,
  objective,
  description,
  "startDate",
  "endDate",
  budget,
  "actualCost",
  "targetAudience",
  "targetLeads",
  "actualLeads",
  "targetRevenue",
  "actualRevenue",
  roi,
  channel,
  "assignedTo",
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Active Email Campaigns
(
  'camp-crm-001',
  'Q4 CRM Enterprise Outreach',
  'email',
  'active',
  'Generate enterprise leads through targeted email campaign',
  'Primary sales pipeline for all standard opportunities',
  DATE(NOW() - INTERVAL '30 days'),
  DATE(NOW() + INTERVAL '30 days'),
  15000.00,
  8500.00,
  'Enterprise CTOs and IT Directors in Technology and Healthcare sectors',
  100,
  45,
  250000.00,
  125000.00,
  15.5,
  'email',
  'usr-crm-marketing',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '35 days',
  NOW() - INTERVAL '2 days'
),
(
  'camp-crm-002',
  'Healthcare Digital Transformation Series',
  'email',
  'active',
  'Engage healthcare leaders with digital transformation content',
  'Email series targeting healthcare C-suite with digital transformation insights',
  DATE(NOW() - INTERVAL '20 days'),
  DATE(NOW() + INTERVAL '40 days'),
  12000.00,
  7200.00,
  'Healthcare C-Suite and IT Leaders looking for digital solutions',
  80,
  32,
  200000.00,
  85000.00,
  22.3,
  'email',
  'usr-crm-marketing',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '1 day'
),

-- Social Media Campaigns
(
  'camp-crm-003',
  'LinkedIn Manufacturing Leaders Campaign',
  'social',
  'active',
  'Build brand awareness among manufacturing decision makers',
  'LinkedIn sponsored content targeting manufacturing executives',
  DATE(NOW() - INTERVAL '15 days'),
  DATE(NOW() + INTERVAL '45 days'),
  8000.00,
  5200.00,
  'Manufacturing executives and operations managers',
  60,
  28,
  150000.00,
  75000.00,
  18.7,
  'social_media',
  'usr-crm-marketing',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '3 days'
),
(
  'camp-crm-004',
  'Startup Growth Solutions Campaign',
  'social',
  'active',
  'Engage startup founders with growth-focused messaging',
  'Social media campaign targeting startup founders and growth teams',
  DATE(NOW() - INTERVAL '10 days'),
  DATE(NOW() + INTERVAL '20 days'),
  5000.00,
  3800.00,
  'Startup founders and growth teams in technology sector',
  40,
  18,
  80000.00,
  35000.00,
  12.8,
  'social_media',
  'usr-crm-marketing',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '1 day'
),

-- Advertising Campaigns
(
  'camp-crm-005',
  'Google Ads CRM Software Campaign',
  'advertising',
  'active',
  'Capture high-intent CRM software searchers',
  'PPC campaign on Google targeting CRM-related search terms',
  DATE(NOW() - INTERVAL '25 days'),
  DATE(NOW() + INTERVAL '35 days'),
  20000.00,
  12500.00,
  'Business owners and managers searching for CRM solutions',
  150,
  85,
  350000.00,
  180000.00,
  28.5,
  'web',
  'usr-crm-marketing',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '30 days',
  NOW() - INTERVAL '2 days'
),

-- Webinar Campaigns
(
  'camp-crm-006',
  'CRM Best Practices Webinar Series',
  'webinar',
  'planned',
  'Educate prospects on CRM best practices',
  'Webinar series covering CRM implementation and optimization best practices',
  DATE(NOW() + INTERVAL '5 days'),
  DATE(NOW() + INTERVAL '65 days'),
  8500.00,
  2100.00,
  'Sales and marketing professionals interested in CRM optimization',
  75,
  0,
  150000.00,
  0.00,
  NULL,
  'web',
  'usr-crm-sales-mgr',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '1 day'
),

-- Content Marketing Campaigns
(
  'camp-crm-007',
  'Industry Insights Blog Series',
  'content',
  'active',
  'Establish thought leadership through valuable content',
  'Blog series with industry insights and best practices for CRM users',
  DATE(NOW() - INTERVAL '45 days'),
  DATE(NOW() + INTERVAL '15 days'),
  6000.00,
  3200.00,
  'Industry professionals seeking insights and best practices',
  50,
  55,
  100000.00,
  65000.00,
  35.2,
  'web',
  'usr-crm-marketing',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '50 days',
  NOW() - INTERVAL '3 days'
),

-- Event Campaigns
(
  'camp-crm-008',
  'TechCon 2024 Trade Show',
  'event',
  'completed',
  'Generate qualified leads at major industry event',
  'Booth presence and demos at TechCon 2024 trade show',
  DATE(NOW() - INTERVAL '90 days'),
  DATE(NOW() - INTERVAL '85 days'),
  25000.00,
  24800.00,
  'Technology executives and decision makers attending TechCon',
  50,
  45,
  500000.00,
  425000.00,
  42.5,
  'other',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '95 days',
  NOW() - INTERVAL '85 days'
),
(
  'camp-crm-009',
  'Healthcare Innovation Summit',
  'event',
  'completed',
  'Connect with healthcare innovation leaders',
  'Participation in Healthcare Innovation Summit with speaking session',
  DATE(NOW() - INTERVAL '60 days'),
  DATE(NOW() - INTERVAL '57 days'),
  18000.00,
  17200.00,
  'Healthcare innovation leaders and technology adopters',
  35,
  28,
  300000.00,
  215000.00,
  38.8,
  'other',
  'usr-crm-sales-mgr',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '65 days',
  NOW() - INTERVAL '55 days'
),

-- Retargeting Campaign (using 'other' type)
(
  'camp-crm-010',
  'Website Visitors Retargeting',
  'other',
  'active',
  'Re-engage website visitors who showed interest',
  'Retargeting campaign for website visitors who viewed pricing or demo pages',
  DATE(NOW() - INTERVAL '20 days'),
  DATE(NOW() + INTERVAL '25 days'),
  4500.00,
  2800.00,
  'Website visitors who viewed pricing or demo pages',
  30,
  22,
  75000.00,
  45000.00,
  25.4,
  'web',
  'usr-crm-marketing',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '2 days'
),

-- Referral Campaign
(
  'camp-crm-011',
  'Customer Referral Program Q4',
  'email',
  'active',
  'Drive referrals from existing customers',
  'Customer referral program with incentives for successful referrals',
  DATE(NOW() - INTERVAL '35 days'),
  DATE(NOW() + INTERVAL '25 days'),
  10000.00,
  3500.00,
  'Existing customers with successful CRM implementations',
  20,
  12,
  200000.00,
  125000.00,
  45.8,
  'email',
  'usr-crm-sales-rep',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '40 days',
  NOW() - INTERVAL '5 days'
),

-- Completed Campaign (Historical)
(
  'camp-crm-012',
  'Q3 Small Business Email Campaign',
  'email',
  'completed',
  'Target small businesses with affordable CRM options',
  'Email campaign targeting small business owners with value-focused messaging',
  DATE(NOW() - INTERVAL '120 days'),
  DATE(NOW() - INTERVAL '60 days'),
  7500.00,
  7200.00,
  'Small business owners looking for affordable CRM solutions',
  60,
  42,
  120000.00,
  85000.00,
  28.5,
  'email',
  'usr-crm-marketing',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '125 days',
  NOW() - INTERVAL '60 days'
),

-- Paused Campaign
(
  'camp-crm-013',
  'Winter Holiday Special Promotion',
  'email',
  'paused',
  'Holiday promotion for year-end budget spending',
  'Special holiday promotion targeting prospects with remaining Q4 budget',
  DATE(NOW() - INTERVAL '10 days'),
  DATE(NOW() + INTERVAL '20 days'),
  5000.00,
  1200.00,
  'Previous prospects and warm leads from Q3 campaigns',
  25,
  3,
  50000.00,
  8000.00,
  -15.2,
  'email',
  'usr-crm-marketing',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '8 days'
);
