/**
 * update-core.mjs's post-update step used to shell out to the removed
 * scripts/build/docs.mjs via a `pnpm docs:build` that no longer exists (exit
 * 254), and swallowed that failure in an empty catch. The docs registry is
 * generated by registry.mjs itself now, alongside every other registry, so
 * there is no separate docs build step left to run or to fail silently.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const UPDATE_CORE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../scripts/maintenance/update-core.mjs')
const source = fs.readFileSync(UPDATE_CORE, 'utf8')

test('does not shell out to the removed docs.mjs build step', () => {
  assert.doesNotMatch(source, /docs:build/)
  assert.doesNotMatch(source, /docs\.mjs/)
})

test('reports a registry rebuild failure instead of swallowing it', () => {
  const registryRebuild = source.match(/try\s*\{\s*execSync\('node core\/scripts\/build\/registry\.mjs --build'[\s\S]*?\}\s*catch[\s\S]*?\{[\s\S]*?\}/)
  assert.ok(registryRebuild, 'expected a try/catch around the registry rebuild (which now also regenerates the docs registry)')
  assert.match(registryRebuild[0], /catch \(error\)/)
  assert.match(registryRebuild[0], /console\.error/)
})
