/**
 * Contacts Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the contacts entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const contactsFields: EntityField[] = [
  {
    name: 'firstName',
    type: 'text',
    required: true,
    display: {
      label: 'First Name',
      description: 'Contact first name',
      placeholder: 'Enter first name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'lastName',
    type: 'text',
    required: true,
    display: {
      label: 'Last Name',
      description: 'Contact last name',
      placeholder: 'Enter last name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'email',
    type: 'email',
    required: true,
    display: {
      label: 'Email',
      description: 'Contact email address',
      placeholder: 'Enter email address...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'phone',
    type: 'text',
    required: false,
    display: {
      label: 'Phone',
      description: 'Office phone number',
      placeholder: 'Enter phone number...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'mobile',
    type: 'text',
    required: false,
    display: {
      label: 'Mobile',
      description: 'Mobile phone number',
      placeholder: 'Enter mobile number...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'companyId',
    type: 'relation',
    required: false,
    display: {
      label: 'Company',
      description: 'Associated company',
      placeholder: 'Select company...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
    relation: {
      entity: 'companies',
      titleField: 'name',
    },
  },
  {
    name: 'position',
    type: 'text',
    required: false,
    display: {
      label: 'Position',
      description: 'Job position or title',
      placeholder: 'Enter position...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'department',
    type: 'text',
    required: false,
    display: {
      label: 'Department',
      description: 'Department in company',
      placeholder: 'Enter department...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'isPrimary',
    type: 'boolean',
    required: false,
    display: {
      label: 'Primary Contact',
      description: 'Is primary contact for company',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'birthDate',
    type: 'date',
    required: false,
    display: {
      label: 'Birth Date',
      description: 'Contact birth date',
      placeholder: 'Select date...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'linkedin',
    type: 'url',
    required: false,
    display: {
      label: 'LinkedIn',
      description: 'LinkedIn profile URL',
      placeholder: 'https://linkedin.com/in/...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'twitter',
    type: 'text',
    required: false,
    display: {
      label: 'Twitter',
      description: 'Twitter/X handle',
      placeholder: '@username',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'preferredChannel',
    type: 'select',
    required: false,
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'whatsapp', label: 'WhatsApp' },
      { value: 'linkedin', label: 'LinkedIn' },
      { value: 'slack', label: 'Slack' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Preferred Channel',
      description: 'Preferred communication channel',
      placeholder: 'Select channel...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'timezone',
    type: 'text',
    required: false,
    display: {
      label: 'Timezone',
      description: 'Contact timezone',
      placeholder: 'UTC',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'lastContactedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Last Contacted',
      description: 'Last time this contact was reached',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 15,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the contact was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the contact was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]