/**
 * Generated by the NextSpark registry build: a copy of app/dashboard/layout.tsx, so theme
 * routes under src/app/(templates) render inside the same layout. Rewritten on every build.
 */
// Implementation: @nextsparkjs/core/routes/dashboard/layout (#203). The generated host emits this same facade.
export { default } from "@nextsparkjs/core/routes/dashboard/layout"
