/**
 * Template page - directly imports from theme
 * Template: app/dashboard/(main)/agent-multi/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/dashboard/(main)/agent-multi/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
