/**
 * Opportunities Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the opportunities entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const opportunitiesFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Opportunity Name',
      description: 'Opportunity name or title',
      placeholder: 'Enter opportunity name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'companyId',
    type: 'relation',
    required: true,
    relation: {
      entity: 'companies',
      titleField: 'name',
    },
    display: {
      label: 'Company',
      description: 'Company this opportunity belongs to',
      placeholder: 'Select company...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'contactId',
    type: 'relation',
    required: false,
    relation: {
      entity: 'contacts',
      titleField: 'firstName',
    },
    display: {
      label: 'Primary Contact',
      description: 'Primary contact for this opportunity',
      placeholder: 'Select contact...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'pipelineId',
    type: 'relation',
    required: true,
    relation: {
      entity: 'pipelines',
      titleField: 'name',
    },
    display: {
      label: 'Pipeline',
      description: 'Pipeline this opportunity is in',
      placeholder: 'Select pipeline...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'stageId',
    type: 'text',
    required: true,
    display: {
      label: 'Stage',
      description: 'Current stage in pipeline',
      placeholder: 'Stage ID from pipeline',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'amount',
    type: 'number',
    required: true,
    display: {
      label: 'Deal Amount',
      description: 'Deal amount value',
      placeholder: '0.00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'currency',
    type: 'select',
    required: false,
    options: [
      { value: 'USD', label: 'US Dollar' },
      { value: 'EUR', label: 'Euro' },
      { value: 'GBP', label: 'British Pound' },
      { value: 'MXN', label: 'Mexican Peso' },
      { value: 'CAD', label: 'Canadian Dollar' },
      { value: 'AUD', label: 'Australian Dollar' },
      { value: 'JPY', label: 'Japanese Yen' },
      { value: 'CNY', label: 'Chinese Yuan' },
      { value: 'INR', label: 'Indian Rupee' },
      { value: 'BRL', label: 'Brazilian Real' },
    ],
    display: {
      label: 'Currency',
      description: 'Currency code for amount',
      placeholder: 'Select currency...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'probability',
    type: 'number',
    required: false,
    display: {
      label: 'Win Probability (%)',
      description: 'Win probability percentage',
      placeholder: '0',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'expectedRevenue',
    type: 'number',
    required: false,
    display: {
      label: 'Expected Revenue',
      description: 'Calculated expected revenue',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'closeDate',
    type: 'date',
    required: true,
    display: {
      label: 'Expected Close Date',
      description: 'Expected or actual close date',
      placeholder: 'Select date...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'type',
    type: 'select',
    required: false,
    options: [
      { value: 'new_business', label: 'New Business' },
      { value: 'existing_business', label: 'Existing Business' },
      { value: 'renewal', label: 'Renewal' },
      { value: 'upgrade', label: 'Upgrade' },
      { value: 'downgrade', label: 'Downgrade' },
    ],
    display: {
      label: 'Opportunity Type',
      description: 'Type of opportunity',
      placeholder: 'Select type...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'source',
    type: 'select',
    required: false,
    options: [
      { value: 'web', label: 'Website' },
      { value: 'referral', label: 'Referral' },
      { value: 'cold_call', label: 'Cold Call' },
      { value: 'trade_show', label: 'Trade Show' },
      { value: 'social_media', label: 'Social Media' },
      { value: 'email', label: 'Email' },
      { value: 'advertising', label: 'Advertising' },
      { value: 'partner', label: 'Partner' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Source',
      description: 'Source of the opportunity',
      placeholder: 'Select source...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'competitor',
    type: 'text',
    required: false,
    display: {
      label: 'Main Competitor',
      description: 'Main competitor for this deal',
      placeholder: 'Enter competitor...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'status',
    type: 'select',
    required: false,
    options: [
      { value: 'open', label: 'Open' },
      { value: 'won', label: 'Won' },
      { value: 'lost', label: 'Lost' },
      { value: 'abandoned', label: 'Abandoned' },
    ],
    display: {
      label: 'Status',
      description: 'Current opportunity status',
      placeholder: 'Select status...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'lostReason',
    type: 'text',
    required: false,
    display: {
      label: 'Lost Reason',
      description: 'Reason if opportunity was lost',
      placeholder: 'Enter reason...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 15,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'assignedTo',
    type: 'user',
    required: false,
    display: {
      label: 'Assigned To',
      description: 'Sales rep assigned to opportunity',
      placeholder: 'Select user...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 16,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the opportunity was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the opportunity was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]