// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.

import { z } from 'zod'

/** `info` of every response: the timestamp, plus whatever the endpoint adds (pagination, `created`). */
export const apiInfoSchema = z.looseObject({ timestamp: z.string() })
export type ApiInfo = z.infer<typeof apiInfoSchema>

/** What a list endpoint adds to `info`. */
export const paginationInfoSchema = z.object({
  page: z.number(),
  limit: z.number(),
  total: z.number(),
  totalPages: z.number(),
  hasNextPage: z.boolean(),
  hasPrevPage: z.boolean(),
})
export type PaginationInfo = z.infer<typeof paginationInfoSchema>

export interface ApiSuccessResponse<T> {
  success: true
  data: T
  info: ApiInfo
}

export interface ApiListResponse<T> {
  success: true
  data: T[]
  info: ApiInfo & PaginationInfo
}

export interface ApiErrorResponse {
  success: false
  error: string
  code: string
  details?: unknown
  info?: ApiInfo
}

export type ApiResponse<T> = ApiSuccessResponse<T> | ApiErrorResponse

export function apiSuccessResponseSchema<T extends z.ZodType>(data: T) {
  return z.object({ success: z.literal(true), data, info: apiInfoSchema })
}

export function apiListResponseSchema<T extends z.ZodType>(item: T) {
  return z.object({ success: z.literal(true), data: z.array(item), info: apiInfoSchema.extend(paginationInfoSchema.shape) })
}

export const apiErrorResponseSchema = z.object({
  success: z.literal(false),
  error: z.string(),
  code: z.string(),
  details: z.unknown().optional(),
  info: apiInfoSchema.optional(),
})
