// Generated by NextSpark (nextspark prepare). Do not edit: regenerated on every prepare.

import * as z from 'zod'
import { addressSchema, fileObjectSchema } from './schema/schema-generator'
import { mediaRefSchema } from './schema/media-ref'

export { addressSchema, fileObjectSchema, mediaRefSchema }

/** `address` fields. */
export type Address = z.infer<typeof addressSchema>

/** One uploaded file: the items of `file`, `video`, `audio` and multi-`image` fields. */
export type FileObject = z.infer<typeof fileObjectSchema>

/** `media-library` fields: a plain URL (legacy) or the media id with its url. */
export type MediaRef = z.infer<typeof mediaRefSchema>
