#!/usr/bin/env node
/**
 * @nextsparkjs/core postinstall hook
 *
 * Writes nothing. Since 0.1.0-beta.192 `src/app` is generated by `nextspark dev`, `build` and
 * `prepare`, and a package install never touches a project. The only thing left to do here is
 * tell a project that still carries a committed `src/app` (or `app/`) how to move to the
 * generated host.
 *
 * Only runs in NextSpark projects (not in the monorepo or other contexts).
 * Debug mode: Set NEXTSPARK_DEBUG=1 to see detailed logs
 */

import { existsSync, readFileSync } from 'fs';
import { join, resolve, isAbsolute, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const DEBUG = process.env.NEXTSPARK_DEBUG === '1';

function debug(message) {
  if (DEBUG) {
    console.log(`  [DEBUG] ${message}`);
  }
}

/**
 * Find the project root by walking up from the current directory
 * until we find a package.json that isn't inside node_modules
 */
function findProjectRoot() {
  // When running postinstall, we're in node_modules/@nextsparkjs/core
  // We need to find the project root (where the user's package.json is)
  let current = process.cwd();

  // If we're inside node_modules, walk up to find the project root
  if (current.includes('node_modules')) {
    // Go up until we're out of node_modules
    const parts = current.split('node_modules');
    current = parts[0].replace(/[/\\]$/, ''); // Remove trailing slash
  }

  return current;
}

/**
 * Validate that the project root path is safe to use
 */
function validateProjectRoot(projectRoot) {
  // Must be an absolute path
  if (!isAbsolute(projectRoot)) {
    debug(`Invalid path: not absolute - ${projectRoot}`);
    return false;
  }

  // Must exist
  if (!existsSync(projectRoot)) {
    debug(`Invalid path: does not exist - ${projectRoot}`);
    return false;
  }

  // Resolve to canonical path and verify it doesn't escape
  const resolved = resolve(projectRoot);
  if (resolved !== projectRoot && !projectRoot.startsWith(resolved)) {
    debug(`Invalid path: resolution mismatch - ${projectRoot} vs ${resolved}`);
    return false;
  }

  return true;
}

/**
 * Detect if we're in the NextSpark development monorepo.
 * Consumer projects may also have pnpm-workspace.yaml (for their own packages),
 * so we check for packages/core/ which only exists in the dev monorepo.
 */
function isDevMonorepo(projectRoot) {
  const isMonorepo = existsSync(join(projectRoot, 'packages', 'core', 'package.json'));
  if (isMonorepo) {
    debug('Skipping: NextSpark development monorepo detected');
  }
  return isMonorepo;
}

/**
 * Detect if we're in a NextSpark consumer project
 */
function isNextSparkProject(projectRoot) {
  // If we're in the dev monorepo, skip
  if (isDevMonorepo(projectRoot)) {
    return false;
  }

  // Check for package.json with nextspark dependency
  const pkgPath = join(projectRoot, 'package.json');
  if (!existsSync(pkgPath)) {
    debug('Skipping: no package.json found');
    return false;
  }

  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };

    const hasNextSpark = !!(deps['@nextsparkjs/core'] || deps['@nextsparkjs/cli']);
    if (!hasNextSpark) {
      debug('Skipping: no NextSpark dependencies found');
    }
    return hasNextSpark;
  } catch {
    debug('Skipping: failed to parse package.json');
    return false;
  }
}

/**
 * Whether the project carries an app tree no generation owns: a committed `src/app` (core's
 * `resolveHostMode` decides, validating the generation record) or a pre-root-first `app/`.
 */
async function hasCommittedAppTree(projectRoot) {
  if (existsSync(join(projectRoot, 'app'))) return true;
  try {
    const coreRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
    const { resolveHostMode } = await import(pathToFileURL(join(coreRoot, 'scripts/build/registry/host/mode.mjs')).href);
    return resolveHostMode({ coreRoot, projectRoot }).mode === 'legacy-app';
  } catch (error) {
    debug(`Could not ask core who owns src/app: ${error.message}`);
    return false;
  }
}

// Main execution
try {
  const projectRoot = findProjectRoot();
  debug(`Project root: ${projectRoot}`);

  if (!validateProjectRoot(projectRoot)) {
    debug('Skipping: invalid project root path');
    process.exit(0);
  }

  if (isNextSparkProject(projectRoot) && (await hasCommittedAppTree(projectRoot))) {
    console.log(
      '\n  @nextsparkjs/core: this project has a committed app tree, but src/app is now generated.\n' +
      '  Run `pnpm nextspark migrate --dry-run` to see what changes, then `pnpm nextspark migrate`.\n' +
      '  Nothing was changed. `nextspark sync:app` was removed in 0.1.0-beta.192.\n'
    );
  }
} catch (error) {
  // Postinstall hooks should not break installations
  if (DEBUG) {
    console.warn('\n  [DEBUG] Postinstall error:', error.message);
    if (error.stack) {
      console.warn(error.stack);
    }
  }
}
