import type { FieldDefinition } from '@nextsparkjs/core/types/blocks'

export const fieldDefinitions: FieldDefinition[] = [
  // === CONTENT TAB ===
  {
    name: 'sectionTitle',
    label: 'Section Title',
    type: 'text',
    tab: 'content',
    required: false,
    placeholder: 'Why Choose Us',
    helpText: 'Main heading for this section',
  },
  {
    name: 'sectionSubtitle',
    label: 'Section Subtitle',
    type: 'textarea',
    tab: 'content',
    required: false,
    placeholder: 'Discover the key benefits of working with us',
    rows: 2,
  },
  {
    name: 'benefits',
    label: 'Benefits',
    type: 'array',
    tab: 'content',
    required: true,
    minItems: 1,
    maxItems: 6,
    helpText: 'Add up to 6 benefit cards',
    itemFields: [
      {
        name: 'title',
        label: 'Title',
        type: 'text',
        tab: 'content',
        required: true,
        placeholder: 'Benefit title',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        tab: 'content',
        required: false,
        placeholder: 'Describe this benefit...',
        rows: 3,
      },
      {
        name: 'borderColor',
        label: 'Border Color',
        type: 'color',
        tab: 'content',
        required: false,
        default: '#3b82f6',
        helpText: 'Top border color (when enabled)',
      },
    ],
  },

  // === DESIGN TAB ===
  {
    name: 'showColoredBorders',
    label: 'Enable Colored Borders',
    type: 'checkbox',
    tab: 'design',
    required: false,
    default: false,
    checkboxLabel: 'Show colored top border on each card',
    helpText: 'When enabled, each card displays a colored top border',
  },
  {
    name: 'columns',
    label: 'Number of Columns',
    type: 'select',
    tab: 'design',
    required: false,
    default: '3',
    options: [
      { label: '2 Columns', value: '2' },
      { label: '3 Columns', value: '3' },
      { label: '4 Columns', value: '4' },
    ],
  },
  {
    name: 'cardStyle',
    label: 'Card Style',
    type: 'radio',
    tab: 'design',
    required: false,
    default: 'bordered',
    options: [
      { label: 'Minimal', value: 'minimal' },
      { label: 'Bordered', value: 'bordered' },
      { label: 'Elevated (Shadow)', value: 'elevated' },
    ],
    helpText: 'Visual style for benefit cards',
  },
  {
    name: 'backgroundColor',
    label: 'Background Color',
    type: 'select',
    tab: 'design',
    required: false,
    default: 'transparent',
    options: [
      { label: 'Transparent', value: 'transparent' },
      { label: 'White', value: 'white' },
      { label: 'Gray 50', value: 'gray-50' },
      { label: 'Gray 100', value: 'gray-100' },
    ],
  },

  // === ADVANCED TAB (Testing new field types) ===
  {
    name: 'publishDate',
    label: 'Publish Date',
    type: 'date',
    tab: 'advanced',
    required: false,
    helpText: 'Date field example (date picker)',
  },
  {
    name: 'eventTime',
    label: 'Event Time',
    type: 'time',
    tab: 'advanced',
    required: false,
    helpText: 'Time field example (time picker)',
  },
  {
    name: 'lastUpdated',
    label: 'Last Updated',
    type: 'datetime',
    tab: 'advanced',
    required: false,
    helpText: 'Datetime field example (date + time)',
  },
  {
    name: 'className',
    label: 'CSS Class',
    type: 'text',
    tab: 'advanced',
    required: false,
    placeholder: 'my-custom-class',
  },
  {
    name: 'id',
    label: 'HTML ID',
    type: 'text',
    tab: 'advanced',
    required: false,
    placeholder: 'benefits-section',
  },
]
