/**
 * Template page - directly imports from theme
 * Template: app/(public)/support/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/(public)/support/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
