/**
 * Notes Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the notes entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const notesFields: EntityField[] = [
  {
    name: 'title',
    type: 'text',
    required: false,
    display: {
      label: 'Title',
      description: 'Note title (optional)',
      placeholder: 'Enter title...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 8,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'content',
    type: 'textarea',
    required: true,
    display: {
      label: 'Content',
      description: 'Note content',
      placeholder: 'Enter note content...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 12,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'type',
    type: 'select',
    required: false,
    options: [
      { value: 'general', label: 'General' },
      { value: 'call', label: 'Call Note' },
      { value: 'meeting', label: 'Meeting Note' },
      { value: 'email', label: 'Email Note' },
      { value: 'followup', label: 'Follow-up' },
      { value: 'feedback', label: 'Feedback' },
      { value: 'reminder', label: 'Reminder' },
    ],
    display: {
      label: 'Note Type',
      description: 'Type of note',
      placeholder: 'Select type...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'isPinned',
    type: 'boolean',
    required: false,
    display: {
      label: 'Pinned',
      description: 'Is note pinned/important',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'isPrivate',
    type: 'boolean',
    required: false,
    display: {
      label: 'Private',
      description: 'Is note private to creator',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'entityType',
    type: 'select',
    required: false,
    options: [
      { value: 'lead', label: 'Lead' },
      { value: 'contact', label: 'Contact' },
      { value: 'company', label: 'Company' },
      { value: 'opportunity', label: 'Opportunity' },
      { value: 'campaign', label: 'Campaign' },
    ],
    display: {
      label: 'Related Entity Type',
      description: 'Type of related entity',
      placeholder: 'Select entity type...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'entityId',
    type: 'text',
    required: false,
    display: {
      label: 'Related Entity ID',
      description: 'ID of related entity',
      placeholder: 'Entity ID...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'contactId',
    type: 'relation',
    required: false,
    display: {
      label: 'Contact',
      description: 'Related contact',
      placeholder: 'Select contact...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'companyId',
    type: 'relation',
    required: false,
    display: {
      label: 'Company',
      description: 'Related company',
      placeholder: 'Select company...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'opportunityId',
    type: 'relation',
    required: false,
    display: {
      label: 'Opportunity',
      description: 'Related opportunity',
      placeholder: 'Select opportunity...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'attachments',
    type: 'json',
    required: false,
    display: {
      label: 'Attachments',
      description: 'Array of attachment objects',
      placeholder: 'Add attachments...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 12,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the note was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the note was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]