/**
 * The portable contracts (packages/contracts, generated by `nextspark prepare` from apps/dev's entities)
 * validate requests with the server's own schema generator. These tests prove it on the real entities:
 * for every payload, the contract accepts it exactly when `generateEntitySchemas` does, and parses it to
 * the same value. They also pin what keeps that true: the generator the contracts run is a byte copy of
 * core's portable sources, and no pg type parser is configured (the response wire types rely on that).
 */

import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

import { generateEntitySchemas } from '@/core/lib/entities/schema-generator'
import type { EntityConfig } from '@/core/lib/entities/types'
import { customerEntityConfig } from '../../../../../../apps/dev/entities/customers/customers.config'
import { pagesEntityConfig } from '../../../../../../apps/dev/entities/pages/pages.config'
import { postsEntityConfig } from '../../../../../../apps/dev/entities/posts/posts.config'
import { taskEntityConfig } from '../../../../../../apps/dev/entities/tasks/tasks.config'
import {
  createCustomerInputSchema, updateCustomerInputSchema,
  createPageInputSchema, updatePageInputSchema,
  createPostInputSchema, updatePostInputSchema,
  createTaskInputSchema, updateTaskInputSchema,
} from '../../../../../contracts/src'

const CORE = join(__dirname, '../../../..')
const REPO = join(CORE, '../..')

interface Parseable { safeParse(data: unknown): { success: boolean; data?: unknown } }
interface Case { name: string; payload: unknown }

/** A row as a client fetched it: what a PATCH sends back with its changes (system and read-only keys included). */
const FETCHED_TASK = { id: 't-1', title: 'x', description: 'd', status: 'todo', priority: 'medium', completed: false, teamId: 'team', userId: 'user', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' }

const ENTITIES: Array<{ name: string; config: EntityConfig; create: Parseable; update: Parseable; creates: Case[]; updates: Case[] }> = [
  {
    name: 'tasks',
    config: taskEntityConfig,
    create: createTaskInputSchema,
    update: updateTaskInputSchema,
    creates: [
      { name: 'minimal', payload: { title: 'x' } },
      { name: 'nothing', payload: {} },
      { name: 'a good status', payload: { title: 'x', status: 'done' } },
      { name: 'a bad status', payload: { title: 'x', status: 'nope' } },
      { name: 'null description', payload: { title: 'x', description: null } },
      { name: 'empty description', payload: { title: 'x', description: '' } },
      { name: 'numeric string hours', payload: { title: 'x', estimatedHours: '8.50' } },
      { name: 'number hours', payload: { title: 'x', estimatedHours: 8.5 } },
      { name: 'garbage hours', payload: { title: 'x', estimatedHours: 'abc' } },
      { name: 'an unknown key', payload: { title: 'x', extra: 1 } },
      { name: 'a system key', payload: { title: 'x', userId: 'u' } },
      { name: 'tags', payload: { title: 'x', tags: ['a', 'b'] } },
      { name: 'null tags', payload: { title: 'x', tags: null } },
      { name: 'a date', payload: { title: 'x', dueDate: '2026-02-01' } },
      { name: 'a bad date', payload: { title: 'x', dueDate: 'soon' } },
    ],
    updates: [
      { name: 'a fetched row sent back (PATCH)', payload: FETCHED_TASK },
      { name: 'a fetched row with a change', payload: { ...FETCHED_TASK, title: 'y' } },
      { name: 'one change', payload: { status: 'done' } },
      { name: 'null status', payload: { status: null } },
      { name: 'empty hours', payload: { estimatedHours: '' } },
      { name: 'an unknown key', payload: { nope: 1 } },
      { name: 'empty', payload: {} },
      { name: 'a bad status', payload: { status: 'nope' } },
    ],
  },
  {
    name: 'pages (builder)',
    config: pagesEntityConfig,
    create: createPageInputSchema,
    update: updatePageInputSchema,
    creates: [
      { name: 'a builder save', payload: { title: 'About', slug: 'about', blocks: [{ id: 'b1', blockSlug: 'hero', props: { title: 'Hi' } }], settings: { seo: { title: 'About' } } } },
      { name: 'blocks that are not a block list', payload: { title: 'About', slug: 'about', blocks: 'anything' } },
      { name: 'no slug', payload: { title: 'About' } },
      { name: 'a bad locale', payload: { title: 'About', slug: 'about', locale: 'fr' } },
      { name: 'an unknown key', payload: { title: 'About', slug: 'about', nope: true } },
    ],
    updates: [
      { name: 'blocks and settings', payload: { blocks: [{ id: 'b1', blockSlug: 'hero' }], settings: {} } },
      { name: 'a fetched page sent back', payload: { id: 'p', title: 'About', slug: 'about', status: 'draft', locale: 'en', teamId: 't', userId: 'u', createdAt: 'a', updatedAt: 'b', blocks: [] } },
      { name: 'a bad status', payload: { status: 'gone' } },
    ],
  },
  {
    name: 'customers',
    config: customerEntityConfig,
    create: createCustomerInputSchema,
    update: updateCustomerInputSchema,
    creates: [
      { name: 'minimal', payload: { name: 'Acme', account: 1, office: 'HQ' } },
      { name: 'a numeric string account', payload: { name: 'Acme', account: '12', office: 'HQ' } },
      { name: 'good days', payload: { name: 'Acme', account: 1, office: 'HQ', visitDays: ['lun', 'vie'] } },
      { name: 'a bad day', payload: { name: 'Acme', account: 1, office: 'HQ', visitDays: ['sab'] } },
      { name: 'empty days', payload: { name: 'Acme', account: 1, office: 'HQ', visitDays: '' } },
      { name: 'no office', payload: { name: 'Acme', account: 1 } },
    ],
    updates: [
      { name: 'null phone', payload: { phone: null } },
      { name: 'a fetched row sent back', payload: { id: 'c', name: 'Acme', account: 1, office: 'HQ', teamId: 't', userId: 'u', createdAt: 'a', updatedAt: 'b' } },
    ],
  },
  {
    name: 'posts (builder + taxonomies)',
    config: postsEntityConfig,
    create: createPostInputSchema,
    update: updatePostInputSchema,
    creates: [
      { name: 'a post', payload: { title: 'Hello', slug: 'hello', blocks: [], settings: {} } },
      { name: 'no title', payload: { slug: 'hello' } },
      { name: 'a bad status', payload: { title: 'Hello', slug: 'hello', status: 'nope' } },
      { name: 'an unknown key', payload: { title: 'Hello', slug: 'hello', categories: ['c1'] } },
    ],
    updates: [
      { name: 'one change', payload: { title: 'Changed' } },
      { name: 'blocks', payload: { blocks: [{ id: 'b', blockSlug: 'hero' }] } },
    ],
  },
]

describe('request schemas: the contract accepts a payload exactly when the server does', () => {
  for (const entity of ENTITIES) {
    const server = generateEntitySchemas(entity.config)
    describe(entity.name, () => {
      for (const { name, payload } of entity.creates) {
        it(`create: ${name}`, () => {
          const expected = server.create.safeParse(payload)
          const actual = entity.create.safeParse(payload)
          expect(actual.success).toBe(expected.success)
          if (expected.success) expect(actual.data).toEqual(expected.data)
        })
      }
      for (const { name, payload } of entity.updates) {
        it(`update: ${name}`, () => {
          const expected = server.update.safeParse(payload)
          const actual = entity.update.safeParse(payload)
          expect(actual.success).toBe(expected.success)
          if (expected.success) expect(actual.data).toEqual(expected.data)
        })
      }
    })
  }

  it('covers the cases the review named: a builder save and a fetched-row PATCH are accepted, an unknown key is not', () => {
    expect(createPageInputSchema.safeParse({ title: 'About', slug: 'about', blocks: [{ id: 'b', blockSlug: 'hero' }], settings: {} }).success).toBe(true)
    expect(updateTaskInputSchema.safeParse(FETCHED_TASK).success).toBe(true)
    expect(createTaskInputSchema.safeParse({ title: 'x', description: null, estimatedHours: '8.5' }).success).toBe(true)
    expect(createTaskInputSchema.safeParse({ title: 'x', extra: 1 }).success).toBe(false)
  })
})

describe('what keeps the contract and the server on one source', () => {
  it("the portable sources the contracts run are byte copies of core's", () => {
    const portable = join(CORE, 'src/lib/entities/portable')
    const files = readdirSync(portable).filter(name => name.endsWith('.ts')).sort()
    expect(files).toEqual(['media-ref.ts', 'response-shape.ts', 'schema-generator.ts', 'system-fields.ts', 'types.ts'])
    for (const name of files) {
      expect(readFileSync(join(REPO, 'packages/contracts/src/schema', name), 'utf8')).toBe(readFileSync(join(portable, name), 'utf8'))
    }
  })

  it('the portable sources import zod and each other, nothing else', () => {
    const portable = join(CORE, 'src/lib/entities/portable')
    for (const name of readdirSync(portable).filter(entry => entry.endsWith('.ts'))) {
      const specifiers = [...readFileSync(join(portable, name), 'utf8').matchAll(/^\s*(?:import|export)\s[^'"\n]*from\s+['"]([^'"]+)['"]/gm)].map(match => match[1])
      for (const specifier of specifiers) expect(specifier === 'zod' || /^\.\/[\w-]+$/.test(specifier)).toBe(true)
    }
  })

  it('no pg type parser is configured, so NUMERIC and BIGINT reach the API as strings (the contracts type them so)', () => {
    const hits: string[] = []
    const scan = (dir: string) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (['node_modules', 'dist', '.next', '.nextspark'].includes(entry.name)) continue
        const path = join(dir, entry.name)
        if (entry.isDirectory()) scan(path)
        else if (/\.(?:[cm]?[jt]sx?)$/.test(entry.name) && /setTypeParser|types\.builtins|pg-types/.test(readFileSync(path, 'utf8')) && !path.includes('/tests/')) hits.push(path.replace(`${REPO}/`, ''))
      }
    }
    for (const dir of ['packages/core/src', 'apps/dev/lib', 'apps/dev/config', 'apps/dev/entities']) scan(join(REPO, dir))
    expect(hits).toEqual([])
  })
})
