/**
 * Cards Entity Fields Configuration
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const cardFields: EntityField[] = [
  {
    name: 'title',
    type: 'text',
    required: true,
    display: {
      label: 'Title',
      description: 'Card title',
      placeholder: 'Enter card title...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 12,
    },
    api: {
      readOnly: false,
      searchable: true,
      sortable: true,
    },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Detailed description of the task',
      placeholder: 'Add a more detailed description...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 12,
    },
    api: {
      readOnly: false,
      searchable: true,
      sortable: false,
    },
  },
  {
    name: 'position',
    type: 'number',
    required: false,
    defaultValue: 0,
    display: {
      label: 'Position',
      description: 'Display order within list',
      showInList: false,
      showInDetail: false,
      showInForm: false,
      order: 3,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
    },
  },
  {
    name: 'dueDate',
    type: 'date',
    required: false,
    display: {
      label: 'Due Date',
      description: 'When this task is due',
      placeholder: 'Select due date...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
    },
  },
  {
    name: 'priority',
    type: 'select',
    required: false,
    options: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'urgent', label: 'Urgent' },
    ],
    display: {
      label: 'Priority',
      description: 'Task priority level',
      placeholder: 'Select priority...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 6,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: true,
      filterable: true,
    },
  },
  {
    name: 'labels',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'urgent', label: 'Urgent' },
      { value: 'important', label: 'Important' },
      { value: 'bug', label: 'Bug' },
      { value: 'feature', label: 'Feature' },
      { value: 'enhancement', label: 'Enhancement' },
      { value: 'documentation', label: 'Documentation' },
    ],
    display: {
      label: 'Labels',
      description: 'Tags to categorize this card',
      placeholder: 'Select labels...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 6,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: false,
    },
  },
  {
    name: 'assigneeId',
    type: 'reference',
    required: false,
    referenceEntity: 'users',
    display: {
      label: 'Assignee',
      description: 'Team member assigned to this card',
      placeholder: 'Assign to...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 6,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: false,
    },
  },
  {
    name: 'listId',
    type: 'reference',
    required: true,
    referenceEntity: 'lists',
    display: {
      label: 'List',
      description: 'Parent list',
      placeholder: 'Select list...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 6,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: false,
    },
  },
  {
    name: 'boardId',
    type: 'reference',
    required: true,
    referenceEntity: 'boards',
    display: {
      label: 'Board',
      description: 'Parent board',
      placeholder: 'Select board...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 12,
    },
    api: {
      readOnly: false,
      searchable: false,
      sortable: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the card was created',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 98,
    },
    api: {
      readOnly: true,
      searchable: false,
      sortable: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the card was last modified',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
    },
    api: {
      readOnly: true,
      searchable: false,
      sortable: true,
    },
  },
]

