/**
 * Template page - directly imports from theme
 * Template: app/dashboard/(main)/settings/ai-usage/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/templates/dashboard/(main)/settings/ai-usage/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
