/**
 * Layout template - directly imports from theme
 * Template: app/(public)/layout.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/templates/(public)/layout'

// Direct export of the theme template (no fallback)
export default TemplateComponent
