-- ============================================================================
-- Sample data for contacts table - CRM Theme
-- Aligned with schema in 001_contacts_table.sql
-- Uses users from 999_theme_sample_data.sql
-- References companies from 003_companies_sample_data.sql
-- ============================================================================

-- Clean existing contacts data
DELETE FROM "contacts" WHERE "teamId" = 'team-crm-company';

INSERT INTO "contacts" (
  id,
  "firstName",
  "lastName",
  email,
  phone,
  mobile,
  "companyId",
  position,
  department,
  "isPrimary",
  "birthDate",
  linkedin,
  twitter,
  "preferredChannel",
  timezone,
  "lastContactedAt",
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- TechnoSoft Solutions Contacts (company-crm-001)
(
  'contact-crm-001',
  'Amanda',
  'Davis',
  'amanda.davis@technosoft.com',
  '+1-555-2001',
  '+1-555-3001',
  'company-crm-001',
  'CEO',
  'Executive',
  true,
  '1985-03-15',
  'https://linkedin.com/in/amanda-davis-ceo',
  '@amanda_davis_ceo',
  'email',
  'America/Los_Angeles',
  NOW() - INTERVAL '3 days',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '45 days',
  NOW() - INTERVAL '3 days'
),
(
  'contact-crm-002',
  'Mark',
  'Stevens',
  'mark.stevens@technosoft.com',
  '+1-555-2002',
  '+1-555-3002',
  'company-crm-001',
  'CTO',
  'Technology',
  false,
  '1982-07-22',
  'https://linkedin.com/in/mark-stevens-cto',
  '@mark_stevens_tech',
  'slack',
  'America/Los_Angeles',
  NOW() - INTERVAL '5 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '40 days',
  NOW() - INTERVAL '5 days'
),
(
  'contact-crm-003',
  'Rachel',
  'Kim',
  'rachel.kim@technosoft.com',
  '+1-555-2003',
  '+1-555-3003',
  'company-crm-001',
  'VP Sales',
  'Sales',
  false,
  '1988-11-08',
  'https://linkedin.com/in/rachel-kim-vp',
  '@rachel_kim_sales',
  'phone',
  'America/Los_Angeles',
  NOW() - INTERVAL '7 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '35 days',
  NOW() - INTERVAL '7 days'
),

-- Global Manufacturing Corp Contacts (company-crm-002)
(
  'contact-crm-004',
  'John',
  'Patterson',
  'john.patterson@globalmanufacturing.com',
  '+1-555-2004',
  '+1-555-3004',
  'company-crm-002',
  'President',
  'Executive',
  true,
  '1975-05-12',
  'https://linkedin.com/in/john-patterson-president',
  '@john_patterson_gm',
  'email',
  'America/Detroit',
  NOW() - INTERVAL '10 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '10 days'
),
(
  'contact-crm-005',
  'Susan',
  'Wright',
  'susan.wright@globalmanufacturing.com',
  '+1-555-2005',
  '+1-555-3005',
  'company-crm-002',
  'VP Operations',
  'Operations',
  false,
  '1980-09-03',
  'https://linkedin.com/in/susan-wright-ops',
  '@susan_wright_ops',
  'phone',
  'America/Detroit',
  NOW() - INTERVAL '12 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '115 days',
  NOW() - INTERVAL '12 days'
),

-- Healthcare Innovations Ltd Contacts (company-crm-003)
(
  'contact-crm-006',
  'Patricia',
  'Martinez',
  'patricia.martinez@healthcareinnovations.com',
  '+1-555-2006',
  '+1-555-3006',
  'company-crm-003',
  'Chief Medical Officer',
  'Medical',
  true,
  '1978-12-18',
  'https://linkedin.com/in/dr-patricia-martinez',
  '@dr_martinez_cmo',
  'email',
  'America/New_York',
  NOW() - INTERVAL '2 days',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '30 days',
  NOW() - INTERVAL '2 days'
),
(
  'contact-crm-007',
  'Thomas',
  'Lee',
  'thomas.lee@healthcareinnovations.com',
  '+1-555-2007',
  '+1-555-3007',
  'company-crm-003',
  'IT Director',
  'Information Technology',
  false,
  '1983-04-25',
  'https://linkedin.com/in/thomas-lee-it',
  '@thomas_lee_it',
  'slack',
  'America/New_York',
  NOW() - INTERVAL '4 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '28 days',
  NOW() - INTERVAL '4 days'
),

-- FinanceFirst Bank Contacts (company-crm-004)
(
  'contact-crm-008',
  'Elizabeth',
  'Taylor',
  'elizabeth.taylor@financefirst.com',
  '+1-555-2008',
  '+1-555-3008',
  'company-crm-004',
  'SVP Technology',
  'Technology',
  true,
  '1979-08-14',
  'https://linkedin.com/in/elizabeth-taylor-svp',
  '@liz_taylor_tech',
  'email',
  'America/New_York',
  NOW() - INTERVAL '15 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '15 days'
),
(
  'contact-crm-009',
  'Robert',
  'Johnson',
  'robert.johnson@financefirst.com',
  '+1-555-2009',
  '+1-555-3009',
  'company-crm-004',
  'VP Digital Banking',
  'Digital Banking',
  false,
  '1981-01-30',
  'https://linkedin.com/in/robert-johnson-digital',
  '@rob_johnson_digital',
  'linkedin',
  'America/New_York',
  NOW() - INTERVAL '18 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '175 days',
  NOW() - INTERVAL '18 days'
),

-- EduTech Academy Contacts (company-crm-005)
(
  'contact-crm-010',
  'Maria',
  'Gonzalez',
  'maria.gonzalez@edutech-academy.com',
  '+1-555-2010',
  '+1-555-3010',
  'company-crm-005',
  'Head of Product',
  'Product',
  true,
  '1986-06-07',
  'https://linkedin.com/in/maria-gonzalez-product',
  '@maria_gonzalez_edu',
  'email',
  'America/Chicago',
  NOW() - INTERVAL '1 day',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '1 day'
),
(
  'contact-crm-011',
  'Kevin',
  'Brown',
  'kevin.brown@edutech-academy.com',
  '+1-555-2011',
  '+1-555-3011',
  'company-crm-005',
  'Engineering Manager',
  'Engineering',
  false,
  '1984-10-19',
  'https://linkedin.com/in/kevin-brown-eng',
  '@kevin_brown_dev',
  'slack',
  'America/Chicago',
  NOW() - INTERVAL '3 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '22 days',
  NOW() - INTERVAL '3 days'
),

-- RetailMax Chain Contacts (company-crm-006)
(
  'contact-crm-012',
  'Jennifer',
  'Wilson',
  'jennifer.wilson@retailmax.com',
  '+1-555-2012',
  '+1-555-3012',
  'company-crm-006',
  'VP Digital Transformation',
  'Digital',
  true,
  '1977-02-28',
  'https://linkedin.com/in/jennifer-wilson-retail',
  '@jen_wilson_retail',
  'email',
  'America/Chicago',
  NOW() - INTERVAL '7 days',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '90 days',
  NOW() - INTERVAL '7 days'
),
(
  'contact-crm-013',
  'Michael',
  'Davis',
  'michael.davis@retailmax.com',
  '+1-555-2013',
  '+1-555-3013',
  'company-crm-006',
  'IT Manager',
  'Information Technology',
  false,
  '1987-12-05',
  'https://linkedin.com/in/michael-davis-it',
  '@mike_davis_it',
  'phone',
  'America/Chicago',
  NOW() - INTERVAL '9 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '85 days',
  NOW() - INTERVAL '9 days'
),

-- StartupTech Inc Contacts (company-crm-007)
(
  'contact-crm-014',
  'Sarah',
  'Thompson',
  'sarah.thompson@startuptech.io',
  '+1-555-2014',
  '+1-555-3014',
  'company-crm-007',
  'Co-Founder & CEO',
  'Executive',
  true,
  '1990-05-17',
  'https://linkedin.com/in/sarah-thompson-ceo',
  '@sarah_startup_ceo',
  'whatsapp',
  'America/Los_Angeles',
  NOW() - INTERVAL '1 day',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '1 day'
),
(
  'contact-crm-015',
  'Alex',
  'Rodriguez',
  'alex.rodriguez@startuptech.io',
  '+1-555-2015',
  '+1-555-3015',
  'company-crm-007',
  'Co-Founder & CTO',
  'Technology',
  false,
  '1989-09-23',
  'https://linkedin.com/in/alex-rodriguez-cto',
  '@alex_startup_cto',
  'slack',
  'America/Los_Angeles',
  NOW() - INTERVAL '2 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '14 days',
  NOW() - INTERVAL '2 days'
),

-- Local Consulting Group Contacts (company-crm-008)
(
  'contact-crm-016',
  'Diana',
  'Miller',
  'diana.miller@localconsulting.com',
  '+1-555-2016',
  '+1-555-3016',
  'company-crm-008',
  'Managing Partner',
  'Executive',
  true,
  '1976-11-11',
  'https://linkedin.com/in/diana-miller-partner',
  '@diana_consulting',
  'email',
  'America/Los_Angeles',
  NOW() - INTERVAL '5 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '40 days',
  NOW() - INTERVAL '5 days'
),
(
  'contact-crm-017',
  'Paul',
  'Anderson',
  'paul.anderson@localconsulting.com',
  '+1-555-2017',
  '+1-555-3017',
  'company-crm-008',
  'Senior Consultant',
  'Consulting',
  false,
  '1985-03-29',
  'https://linkedin.com/in/paul-anderson-consultant',
  '@paul_consultant',
  'linkedin',
  'America/Los_Angeles',
  NOW() - INTERVAL '6 days',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '38 days',
  NOW() - INTERVAL '6 days'
);
