import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, rmdirSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { closingBrace, sourceView } from './source-view.js';

/**
 * Converting the app tree of a 0.x project (#203).
 *
 * Since 0.1.0-beta.192 `src/app` is generated by `nextspark prepare` and git-ignored: core's route
 * modules come from `@nextsparkjs/core`, and a project changes a route only through `templates/`
 * (pages, layouts, ...) or `api/` (Route Handlers). A project that still carries the app tree the
 * old `sync:app` (or the wizard) wrote must therefore lose the files the generator will emit again,
 * and turn what the project changed or added into those two source directories:
 *
 * - a file core generated untouched (a generated tag, a sync-state hash, the previous core's
 *   template, the registry's `(templates)` output, or exactly the facade the generator emits for
 *   that route) is removed;
 * - a wrapper that only looks a project template up at run time is removed: the template it looked
 *   up is a static override now;
 * - a file the project changed, at a path core has a route for, becomes an override:
 *   `templates/<path>` for pages, layouts and the like, and for a core Route Handler under
 *   `api/v1/**` too (the project's own `api/` is served at `/api/<path>`, and core owns `/api/v1`);
 * - a file the project added moves to `templates/<path>`, or for a Route Handler under `api/` to
 *   `api/<path without the api/ prefix>`;
 * - what cannot be placed with certainty stops the whole migration before it writes anything, with
 *   the file and the reason.
 *
 * Nothing here writes: `planAppConversion` decides and `applyAppConversion` performs the plan.
 */

/** One route of the installed core's manifest. */
export interface CoreRoute {
  kind: string;
  target: string;
  specifier: string;
  file: string | null;
}

/** What the installed core's host generator offers: the route manifest, and its facade emitter. */
export interface CoreHost {
  routes: Map<string, CoreRoute>;
  emit(input: { kind: string; target: string; specifier: string; file?: string; source?: string; projectRoot: string }): Promise<{ content: string }>;
  kindForFileStem(stem: string): string | null;
}

export type CoreHostLookup = { host: CoreHost } | { unavailable: string };

const CORE_ROUTES_MODULE = join('scripts', 'build', 'registry', 'host', 'core-routes.mjs');
const FACADE_EMITTER_MODULE = join('scripts', 'build', 'registry', 'host', 'facade-emitter.mjs');

/** Load the route manifest and the facade emitter from the core installed in the project. */
export async function loadCoreHost(coreDir: string | null): Promise<CoreHostLookup> {
  if (!coreDir) return { unavailable: 'no installed @nextsparkjs/core was found' };
  const routesModule = join(coreDir, CORE_ROUTES_MODULE);
  const emitterModule = join(coreDir, FACADE_EMITTER_MODULE);
  if (!existsSync(routesModule) || !existsSync(emitterModule)) {
    return { unavailable: 'the installed @nextsparkjs/core does not ship the generated-host route manifest and facade emitter (0.1.0-beta.192 or later); upgrade it first' };
  }
  try {
    const [{ loadCoreRouteManifest }, emitter] = await Promise.all([
      import(pathToFileURL(routesModule).href),
      import(pathToFileURL(emitterModule).href),
    ]);
    const manifest = await loadCoreRouteManifest({ coreRoot: coreDir });
    if (!manifest) return { unavailable: 'the installed @nextsparkjs/core ships no route manifest (@nextsparkjs/core/routes/manifest.json); upgrade it to 0.1.0-beta.192 or later' };
    return {
      host: {
        routes: new Map((manifest.routes as CoreRoute[]).map(route => [route.target, route])),
        emit: input => emitter.emitFacade(input),
        kindForFileStem: (stem: string) => emitter.kindForFileStem(stem),
      },
    };
  } catch (error) {
    return { unavailable: `the installed @nextsparkjs/core route manifest could not be read: ${error instanceof Error ? error.message.split('\n')[0] : String(error)}` };
  }
}

export type AppFileFate =
  | { kind: 'remove'; evidence: string }
  | { kind: 'loader'; template: string | null }
  | { kind: 'override'; destination: string; core: string; baseline: string | null; diff: string; diffLines: number }
  | { kind: 'project'; destination: string }
  | { kind: 'unrecognized'; reason: string };

export interface AppFilePlan {
  /** From the app root, with forward slashes. */
  path: string;
  fate: AppFileFate;
}

export interface WebhookExtension {
  provider: 'stripe' | 'polar';
  /** From the project root, as `billing.webhookExtensions` declares it. */
  module: string;
}

export interface AppConversionPlan {
  root: 'app' | 'src/app';
  files: AppFilePlan[];
  webhookExtensions: WebhookExtension[];
}

export interface AppConversionInput {
  hostRoot: string;
  root: 'app' | 'src/app';
  /** Every file of the app tree, from the app root. */
  files: string[];
  /** Files proven to be untouched output of an earlier core, with how they were proven. */
  generated: Map<string, string>;
  /** The previous core's version of a route file, when it can be fetched: the baseline of a customized file's diff. */
  baselineFor: (path: string) => Buffer | undefined;
  core: CoreHostLookup;
  /** Absolute paths the rest of the migration is about to create, which a converted file must not collide with. */
  reserved: ReadonlySet<string>;
  /** Core's `templates/` directory (its stubs are how an untouched webhook extension is recognized). */
  coreTemplates: string | null;
}

const ROUTE_FILE_EXTENSIONS = ['tsx', 'ts', 'jsx', 'js'];
const PROVIDERS = ['stripe', 'polar'] as const;

/** Source types migrate reads and rewrites; every other file is moved byte for byte. */
const TEXT_SOURCE_EXTENSIONS = new Set(['ts', 'tsx', 'js', 'jsx', 'mjs', 'cjs', 'css', 'scss', 'md', 'mdx', 'json']);
/** The ones whose relative references migrate rewrites. */
const REWRITTEN_EXTENSIONS = new Set(['ts', 'tsx', 'js', 'jsx', 'mjs', 'cjs', 'css', 'scss']);

const strictUtf8 = new TextDecoder('utf-8', { fatal: true });

function decodesAsUtf8(buffer: Buffer): boolean {
  try {
    strictUtf8.decode(buffer);
    return true;
  } catch {
    return false;
  }
}

function extensionOf(path: string): string {
  return path.slice(path.lastIndexOf('.') + 1).toLowerCase();
}

/** A text source file: a known source extension whose bytes decode as valid UTF-8 (nothing else is ever re-encoded). */
function isTextSource(path: string, buffer: Buffer): boolean {
  return TEXT_SOURCE_EXTENSIONS.has(extensionOf(path)) && !buffer.includes(0) && decodesAsUtf8(buffer);
}

/** Not NUL-free text but any decodable content: for the checks that only read (never write) a route file. */
function isText(buffer: Buffer): boolean {
  return !buffer.includes(0) && decodesAsUtf8(buffer);
}

function normalizeNewlines(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

/** The file's stem and extension, or null when the name has no extension. */
function splitName(name: string): { stem: string; extension: string } | null {
  const dot = name.lastIndexOf('.');
  return dot <= 0 ? null : { stem: name.slice(0, dot), extension: name.slice(dot + 1) };
}

/** The source without comments (offsets shift; only the text matters), strings kept. */
function withoutComments(source: string): string {
  const view = sourceView(source);
  let output = '';
  for (let index = 0; index < source.length; index++) {
    const blanked = view.code[index] === ' ' && !/\s/.test(source[index]) && !view.strings.some(text => index >= text.start && index < text.end);
    output += blanked ? ' ' : source[index];
  }
  return output;
}

const normalizeStatement = (text: string) => text.trim().replace(/;$/, '').replace(/\s+/g, ' ').replace(/'([^'"\\]*)'/g, '"$1"');

/**
 * Whether a file is exactly what the old generator emitted for THIS route, and so disposable: a
 * default import of core's module for the route (with its `metadata` under an alias), the template
 * scope import of the route, core's own literal segment config, and the two lookups whose path
 * literal is `app/<this path>` and whose fallback is the imported identifier. Anything else, however
 * small (another import, another path, another fallback), is the project's code.
 */
export function isGeneratorLoader(source: string, path: string, coreSpecifier: string, facade: { literals: readonly string[]; hasMetadata: boolean }): boolean {
  const text = withoutComments(source);
  const withoutExtension = path.replace(/\.[^.]+$/, '');
  let defaultName: string | null = null;
  let metadataName: string | null = null;
  let sawCore = false;
  let sawScope = false;
  for (const match of text.matchAll(/\bimport\s+([^;'"]*?)\s*from\s*(["'])([^"']+)\2\s*;?/g)) {
    const clause = match[1].trim();
    const specifier = match[3];
    if (specifier === coreSpecifier && !sawCore) {
      const parsed = /^([A-Za-z_$][\w$]*)(?:\s*,\s*\{\s*metadata\s+as\s+([A-Za-z_$][\w$]*)\s*\})?$/.exec(clause);
      if (!parsed) return false;
      defaultName = parsed[1];
      metadataName = parsed[2] ?? null;
      sawCore = true;
    } else if (new RegExp(`^@nextsparkjs/registries/template-scopes/(?:server|client)/${withoutExtension.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`).test(specifier) && !sawScope) {
      const names = /^\{([\w\s,]+)\}$/.exec(clause)?.[1].split(',').map(name => name.trim()).filter(Boolean);
      if (!names || !names.includes('getTemplateOrDefault') || names.some(name => name !== 'getTemplateOrDefault' && name !== 'getMetadataOrDefault')) return false;
      sawScope = true;
    } else {
      return false;
    }
  }
  if (!sawCore || !sawScope || !defaultName) return false;
  const remaining = text.replace(/\bimport\s+([^;'"]*?)\s*from\s*(["'])([^"']+)\2\s*;?/g, '');
  const lookup = `"app/${path}"`;
  const wanted = new Set(facade.literals.map(normalizeStatement));
  const statements = remaining.split('\n').map(normalizeStatement).filter(Boolean);
  let sawDefault = false;
  let sawMetadata = false;
  for (const statement of statements) {
    if (statement === `export default getTemplateOrDefault(${lookup}, ${defaultName})` && !sawDefault) sawDefault = true;
    else if (metadataName && statement === `export const metadata = getMetadataOrDefault(${lookup}, ${metadataName})` && !sawMetadata) sawMetadata = true;
    else if (wanted.has(statement)) wanted.delete(statement);
    else return false;
  }
  // The generator emitted the metadata lookup exactly when core's module has metadata to fall back to
  return sawDefault && wanted.size === 0 && sawMetadata === facade.hasMetadata && (metadataName !== null) === facade.hasMetadata;
}

interface Reference {
  start: number;
  end: number;
  value: string;
  /** A Sass module specifier: the target may omit its extension and its partial underscore. */
  sass?: boolean;
}

const KNOWN_JS_CONTEXT = /(?:\bfrom|\bimport|\brequire\s*\(|\brequire\.resolve\s*\(|\bimport\s*\(|\bimport\.meta\.resolve\s*\(|\bexport\s+\*\s+from|\bjest\.(?:mock|requireActual|requireMock|doMock|unmock)\s*\()\s*$/;
const NEW_URL_CONTEXT = /\bnew\s+URL\s*\(\s*$/;
const IMPORT_META_URL = /^\s*,\s*import\s*\.\s*meta\s*\.\s*url\b/;

const CSS_HANDLED_URL = /url\(\s*(['"]?)([^'")\s]+)\1\s*\)/g;
const CSS_STRING = /(['"])((?:(?!\1)[^\\\n]|\\.)*)\1/g;

/** A path CSS resolves against the file: not absolute, not a URL, not a fragment or a variable. */
function isCssRelative(value: string): boolean {
  return value !== '' && !/^(?:[a-z][a-z0-9+.-]*:|\/|#|\$|@|--|var\()/i.test(value) && !value.includes('${') && !value.includes('#{');
}

/**
 * The relative references of a stylesheet: `url()`, `@import`, `@source`, Sass `@use`/`@forward`, CSS
 * Modules `composes ... from`. Every other quoted string that names an existing file is unprovable.
 * Comments are left alone (their text is never a reference).
 */
function cssReferences(source: string, extension: string, fromFile: string): { known: Reference[]; unprovable: string[] } {
  // Blank out comments, keeping offsets
  const clean = source
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
    .replace(extension === 'scss' ? /(^|[^:'"(])\/\/[^\n]*/g : /$^/g, (m, lead) => (lead ?? '') + ' '.repeat(m.length - (lead ?? '').length));
  const known: Reference[] = [];
  const taken: Array<[number, number]> = [];
  const add = (start: number, value: string, sass = false) => {
    // A bare name (`foo/x`, `img.png`) is a load path or a public URL unless a file is there
    if (!/^\.{1,2}(?:\/|$)/.test(value)) {
      const target = resolve(dirname(fromFile), value);
      const candidates = [target, ...['.scss', '.sass', '.css'].flatMap(ext => [`${target}${ext}`, join(dirname(target), `_${basename(target)}${ext}`), join(target, `_index${ext}`), join(target, `index${ext}`)])];
      if (!candidates.some(candidate => existsSync(candidate))) return;
    }
    // A span belongs to one reference: `@import url("x")` is the url() pass's, not the @import pass's too
    if (taken.some(([a, b]) => start >= a && start < b)) return;
    known.push({ start, end: start + value.length, value, sass });
    taken.push([start, start + value.length]);
  };
  for (const match of clean.matchAll(CSS_HANDLED_URL)) {
    const value = match[2];
    if (isCssRelative(value)) add((match.index as number) + match[0].indexOf(value), value);
    else taken.push([match.index as number, (match.index as number) + match[0].length]);
  }
  // Statements whose quoted strings are all references
  for (const match of clean.matchAll(/@(import|source|use|forward)\b([^;{]*)[;{]|\bcomposes\s*:[^;}]*\bfrom\s+(['"][^;}]*)/g)) {
    const isSass = match[1] === 'use' || match[1] === 'forward' || (match[1] === 'import' && extension === 'scss');
    const body = match[2] ?? match[3] ?? '';
    const bodyStart = (match.index as number) + match[0].indexOf(body);
    for (const str of body.matchAll(CSS_STRING)) {
      const at = bodyStart + (str.index as number) + 1;
      if (isCssRelative(str[2]) && !/^(?:https?:)?\/\//.test(str[2])) add(at, str[2], isSass);
    }
  }
  const unprovable: string[] = [];
  for (const str of clean.matchAll(CSS_STRING)) {
    const at = (str.index as number) + 1;
    if (taken.some(([a, b]) => at >= a && at < b)) continue;
    const value = str[2];
    if (isCssRelative(value) && /^\.{1,2}(?:\/|$)/.test(value) && existsSync(resolve(dirname(fromFile), value.split(/[?#]/)[0]))) unprovable.push(value);
  }
  return { known, unprovable: [...new Set(unprovable)] };
}

/**
 * Every relative file reference of a source file that can be rewritten with certainty: module
 * specifiers (`from`, `import`, `import()`, `require`, `require.resolve`, `import.meta.resolve`, `jest.mock`),
 * `new URL('..', import.meta.url)`, and in CSS `url()`, `@import` and `@source`. `unprovable` are
 * relative paths to files that exist, in any other syntax: they would break and cannot be fixed here.
 */
function relativeReferences(source: string, extension: string, fromFile: string): { known: Reference[]; unprovable: string[] } {
  if (extension === 'css' || extension === 'scss') return cssReferences(source, extension, fromFile);
  const view = sourceView(source);
  const known: Reference[] = [];
  const unprovable: string[] = [];
  for (const text of view.strings) {
    if (!/^\.{1,2}(?:\/|$)/.test(text.value)) continue;
    const before = view.code.slice(Math.max(0, text.start - 60), text.start);
    const after = view.code.slice(text.end, text.end + 40);
    if (KNOWN_JS_CONTEXT.test(before) || (NEW_URL_CONTEXT.test(before) && IMPORT_META_URL.test(after))) {
      known.push({ start: text.start + 1, end: text.end - 1, value: text.value });
    } else if (text.value.includes('${') || existsSync(resolve(dirname(fromFile), text.value.split(/[?#]/)[0]))) {
      unprovable.push(text.value);
    }
  }
  return { known, unprovable: [...new Set(unprovable)] };
}

const RESOLVE_SUFFIXES = ['', '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.css', '.json', '/index.ts', '/index.tsx', '/index.js', '/index.jsx'];

interface ImportResolution {
  /** Absolute path of what the specifier names, without the moved-file mapping applied. */
  target: string;
  /** Whether the target is inside the app root that is being emptied. */
  inside: boolean;
  /** The moved file the target is (its new absolute path), when it is one. */
  movedTo: string | null;
}

function resolveRelativeImport(specifier: string, fromFile: string, appRootDirectory: string, moved: ReadonlyMap<string, string>, sass = false): ImportResolution {
  const target = resolve(dirname(fromFile), specifier);
  const inside = target === appRootDirectory || target.startsWith(`${appRootDirectory}${sep}`);
  let movedTo: string | null = null;
  for (const suffix of RESOLVE_SUFFIXES) {
    const candidate = moved.get(`${target}${suffix}`);
    if (candidate) {
      // What a specifier leaves out (an extension, /index.ts) belongs to the file: keep it off the new one too
      movedTo = suffix === '' ? candidate : candidate.slice(0, candidate.length - suffix.length);
      break;
    }
  }
  if (!movedTo && sass) {
    // A Sass module may leave out the partial underscore and the extension
    const directory = dirname(target);
    const base = basename(target);
    for (const extension of ['.scss', '.sass', '.css']) {
      const candidate = moved.get(join(directory, `_${base}${extension}`));
      if (candidate) {
        movedTo = join(dirname(candidate), base);
        break;
      }
      const index = moved.get(join(target, `_index${extension}`)) ?? moved.get(join(target, `index${extension}`));
      if (index) {
        movedTo = dirname(index);
        break;
      }
    }
  }
  return { target, inside, movedTo };
}

/** Whether a relative target names a file: on disk, or (after the move) one of the files about to be written. */
function resolvesToFile(target: string, destinations: ReadonlySet<string>, sass: boolean): boolean {
  const directory = dirname(target);
  const name = basename(target);
  const candidates = [target, ...RESOLVE_SUFFIXES.map(suffix => `${target}${suffix}`)];
  if (sass) for (const extension of ['.scss', '.sass', '.css']) candidates.push(join(directory, `_${name}${extension}`), join(target, `_index${extension}`), join(target, `index${extension}`));
  return candidates.some(candidate => {
    if (destinations.has(candidate)) return true;
    try {
      return statSync(candidate).isFile();
    } catch {
      return false;
    }
  });
}

/**
 * The source of a file that moves from `fromFile` to `toFile`, with every relative import pointing
 * where it pointed before: at the file's new place when the target moves too, at the same file
 * otherwise. An import into the app root that is not moved would break: it comes back in `broken`.
 */
export function rewriteMovedImports(
  source: string,
  fromFile: string,
  toFile: string,
  appRootDirectory: string,
  moved: ReadonlyMap<string, string>,
): { source: string; broken: string[]; unprovable: string[] } {
  const extension = extensionOf(fromFile);
  if (!REWRITTEN_EXTENSIONS.has(extension)) return { source, broken: [], unprovable: [] };
  const { known: specifiers, unprovable } = relativeReferences(source, extension, fromFile);
  const broken: string[] = [];
  const destinations = new Set(moved.values());
  specifiers.sort((left, right) => left.start - right.start);
  const unique = specifiers.filter((reference, index) => !specifiers.some((other, at) => at < index && reference.start < other.end && other.start < reference.end));
  let output = '';
  let cursor = 0;
  for (const specifier of unique) {
    const resolution = resolveRelativeImport(specifier.value, fromFile, appRootDirectory, moved, specifier.sass === true);
    let next: string | null = null;
    if (resolution.movedTo) {
      next = relative(dirname(toFile), resolution.movedTo).split(sep).join('/');
    } else if (resolution.inside) {
      // A CSS or other file that stays behind is only fine when nothing of it is left to find
      broken.push(specifier.value);
    } else {
      next = relative(dirname(toFile), resolution.target).split(sep).join('/');
    }
    if (next !== null) {
      if (!next.startsWith('.') && specifier.value.startsWith('.')) next = `./${next}`;
      // Invariant: a reference that resolved before must resolve after (at its new place, or where it points)
      const before = resolvesToFile(resolution.target, destinations, specifier.sass === true);
      const after = resolvesToFile(resolve(dirname(toFile), next), destinations, specifier.sass === true);
      if (before && !after) unprovable.push(specifier.value);
      output += source.slice(cursor, specifier.start) + next;
      cursor = specifier.end;
    }
  }
  return { source: output + source.slice(cursor), broken, unprovable };
}

/** A small line diff (context 2) of `after` against `before`; empty when they are equal. */
export function lineDiff(before: string, after: string, labels: { before: string; after: string }, maxLines = 160): { text: string; changedLines: number } {
  const left = normalizeNewlines(before).split('\n');
  const right = normalizeNewlines(after).split('\n');
  if (left.length * right.length > 4_000_000) {
    return { text: `--- ${labels.before}\n+++ ${labels.after}\n(too large to diff: ${left.length} and ${right.length} lines)`, changedLines: left.length + right.length };
  }
  const table: Uint32Array[] = Array.from({ length: left.length + 1 }, () => new Uint32Array(right.length + 1));
  for (let row = left.length - 1; row >= 0; row--) {
    for (let column = right.length - 1; column >= 0; column--) {
      table[row][column] = left[row] === right[column] ? table[row + 1][column + 1] + 1 : Math.max(table[row + 1][column], table[row][column + 1]);
    }
  }
  const operations: { mark: ' ' | '-' | '+'; text: string }[] = [];
  let row = 0;
  let column = 0;
  while (row < left.length && column < right.length) {
    if (left[row] === right[column]) {
      operations.push({ mark: ' ', text: left[row] });
      row++;
      column++;
    } else if (table[row + 1][column] >= table[row][column + 1]) {
      operations.push({ mark: '-', text: left[row++] });
    } else {
      operations.push({ mark: '+', text: right[column++] });
    }
  }
  while (row < left.length) operations.push({ mark: '-', text: left[row++] });
  while (column < right.length) operations.push({ mark: '+', text: right[column++] });
  const changedLines = operations.filter(operation => operation.mark !== ' ').length;
  if (changedLines === 0) return { text: '', changedLines: 0 };
  const near = new Set<number>();
  operations.forEach((operation, index) => {
    if (operation.mark === ' ') return;
    for (let offset = -2; offset <= 2; offset++) near.add(index + offset);
  });
  const lines = [`--- ${labels.before}`, `+++ ${labels.after}`];
  let skipped = false;
  operations.forEach((operation, index) => {
    if (!near.has(index)) {
      skipped = true;
      return;
    }
    if (skipped && lines.length > 2) lines.push('...');
    skipped = false;
    lines.push(`${operation.mark}${operation.text}`);
  });
  if (lines.length > maxLines) return { text: `${lines.slice(0, maxLines).join('\n')}\n... (${lines.length - maxLines} more diff lines)`, changedLines };
  return { text: lines.join('\n'), changedLines };
}

function sourceExtension(path: string): string | null {
  return splitName(posix.basename(path))?.extension ?? null;
}

/** Where a project file of the app tree goes, or why it cannot go anywhere. */
function destinationFor(path: string, host: CoreHost, override: boolean): { destination: string } | { reason: string } {
  const isApi = path === 'api' || path.startsWith('api/');
  const stem = splitName(posix.basename(path))?.stem ?? posix.basename(path);
  if (!isApi) {
    if (!path.includes('/') && !host.kindForFileStem(stem.split('.')[0])) {
      return { reason: `it is a file of the app root that is not a route (${posix.basename(path)}): move what it holds to public/ or styles/globals.css by hand, delete it, then run migrate again` };
    }
    return { destination: `templates/${path}` };
  }
  // A Route Handler of core replaced at the same path is an explicit override; anything else lives under api/
  if (override) return { destination: `templates/${path}` };
  const rest = path.slice('api/'.length);
  if (rest === 'v1' || rest.startsWith('v1/') || rest === 'plugins' || rest.startsWith('plugins/')) {
    return { reason: `it adds ${path.replace(/\/[^/]+$/, '')} in the namespace core owns (/api/v1/** and /api/plugins/**): the generator refuses a project route there. Rename its directory to /api/<name> (the URL changes, so update its callers) and run migrate again` };
  }
  return { destination: `api/${rest}` };
}

/**
 * Decide what happens to every file of the app tree.
 *
 * @throws never: what cannot be placed is `unrecognized` in the plan
 */
export async function planAppConversion(input: AppConversionInput): Promise<AppConversionPlan> {
  const { hostRoot, root, generated, core } = input;
  const appRootDirectory = join(hostRoot, root);
  const files: AppFilePlan[] = [];
  const decided = new Map<string, AppFilePlan>();
  const record = (path: string, fate: AppFileFate) => {
    const plan = { path, fate };
    decided.set(path, plan);
    files.push(plan);
  };

  if ('unavailable' in core) {
    for (const path of [...input.files].sort()) {
      const evidence = generated.get(path);
      if (evidence) record(path, { kind: 'remove', evidence });
      else record(path, { kind: 'unrecognized', reason: core.unavailable });
    }
    return { root, files, webhookExtensions: [] };
  }
  const host = core.host;

  const candidates: { path: string; content: Buffer }[] = [];
  for (const path of [...input.files].sort()) {
    const evidence = generated.get(path);
    if (evidence) {
      record(path, { kind: 'remove', evidence });
      continue;
    }
    const content = readFileSync(join(appRootDirectory, path));
    const coreRoute = host.routes.get(path);
    // Exactly what the generator would emit for this route: nothing of the project's is in it
    if (coreRoute && isText(content)) {
      try {
        const emitted = await host.emit({ kind: coreRoute.kind, target: path, specifier: coreRoute.specifier, file: coreRoute.file ?? undefined, projectRoot: hostRoot });
        if (normalizeNewlines(emitted.content) === normalizeNewlines(content.toString('utf8'))) {
          record(path, { kind: 'remove', evidence: `identical to the file the generator emits for ${coreRoute.specifier}` });
          continue;
        }
      } catch {
        // A core route the emitter cannot read is core's problem to report at prepare time
      }
    }
    // ...or for the project's own template at that path: a generation of this release wrote it
    const own = isText(content) ? await projectFacadeMatch(host, hostRoot, path, content.toString('utf8')) : null;
    if (own) {
      record(path, { kind: 'remove', evidence: `identical to the file the generator emits for the project's ${own}` });
      continue;
    }
    if (coreRoute && isText(content) && isGeneratorLoader(content.toString('utf8'), path, coreRoute.specifier, await facadeShape(host, coreRoute, path, hostRoot))) {
      const template = posix.join('templates', path);
      record(path, { kind: 'loader', template: existsSync(join(hostRoot, template)) ? template : null });
      continue;
    }
    candidates.push({ path, content });
  }

  // Where each remaining file goes; the imports between them are checked once every place is known
  const placed = new Map<string, { destination: string; override: boolean; coreRoute: CoreRoute | undefined }>();
  const moved = new Map<string, string>();
  const taken = new Set<string>();
  for (const { path, content } of candidates) {
    const coreRoute = host.routes.get(path);
    const name = posix.basename(path);
    const parts = splitName(name);
    // `page.isr.tsx` is a page too: the stem is what precedes the first dot
    const routeStem = name.split('.')[0];
    const isRoute = parts !== null && ROUTE_FILE_EXTENSIONS.includes(parts.extension) && host.kindForFileStem(routeStem) !== null;
    if (!isText(content) && !path.includes('/')) {
      record(path, { kind: 'unrecognized', reason: `it is a binary file of the app root (${name}): move it to public/ by hand (Next serves public/favicon.ico), then run migrate again` });
      continue;
    }
    const place = destinationFor(path, host, coreRoute !== undefined);
    if ('reason' in place) {
      record(path, { kind: 'unrecognized', reason: place.reason });
      continue;
    }
    const destinationAbsolute = join(hostRoot, place.destination);
    if (existsSync(destinationAbsolute) || input.reserved.has(destinationAbsolute) || taken.has(destinationAbsolute)) {
      record(path, { kind: 'unrecognized', reason: `${place.destination} already exists, so this file cannot be moved there: merge the two by hand (the project's file wins over core's) and run migrate again` });
      continue;
    }
    if (isRoute) {
      const surface = place.destination.startsWith('api/') ? 'api' : 'templates';
      const withoutExtension = place.destination.slice(surface.length + 1).replace(/\.[^.]+$/, '');
      // A file of api/ is served at /api/<path>; templates/ replaces the route at the same path
      const target = surface === 'api' ? place.destination : path;
      try {
        await host.emit({
          kind: host.kindForFileStem(routeStem) as string,
          target,
          specifier: `@/${surface}/${withoutExtension}`,
          source: content.toString('utf8'),
          file: destinationAbsolute,
          projectRoot: hostRoot,
        });
      } catch (error) {
        const diagnostics = (error as { diagnostics?: { code: string; message: string }[] }).diagnostics;
        const detail = diagnostics ? diagnostics.map(item => `[${item.code}] ${item.message}`).join('; ') : (error instanceof Error ? error.message.split('\n')[0] : String(error));
        record(path, { kind: 'unrecognized', reason: `the generator cannot use it as ${place.destination}: ${detail}` });
        continue;
      }
      if (isText(content) && /\bgetTemplateOrDefault\s*\(|registries\/template-scopes/.test(content.toString('utf8'))) {
        record(path, { kind: 'unrecognized', reason: 'it looks a template up at run time and also holds code of its own; the generated host resolves overrides statically. Move its own code into templates/ at this path (a plain page or layout), delete this file, and run migrate again' });
        continue;
      }
    }
    placed.set(path, { destination: place.destination, override: coreRoute !== undefined, coreRoute });
    moved.set(join(appRootDirectory, path), destinationAbsolute);
    taken.add(destinationAbsolute);
  }

  for (const [path, place] of placed) {
    const content = readFileSync(join(appRootDirectory, path));
    if (isTextSource(path, content)) {
      const { broken, unprovable } = rewriteMovedImports(content.toString('utf8'), join(appRootDirectory, path), join(hostRoot, place.destination), appRootDirectory, moved);
      if (unprovable.length > 0) {
        record(path, { kind: 'unrecognized', reason: `it names ${unprovable.map(item => `'${item}'`).join(', ')} as a relative path in a form migrate cannot rewrite (it handles import, require, require.resolve, import.meta.resolve, new URL(..., import.meta.url) and CSS url()/@import), and moving the file would break it. Change it to an import or an alias path, then run migrate again` });
        continue;
      }
      if (broken.length > 0) {
        record(path, { kind: 'unrecognized', reason: `it imports ${broken.map(item => `'${item}'`).join(', ')} from the app tree, and that file is not kept (core generates it, or it is not a route). Import it from core or from the project's own directories instead, then run migrate again` });
        continue;
      }
    }
    if (place.override && place.coreRoute) {
      const baseline = input.baselineFor(path);
      const coreFile = place.coreRoute.file;
      const coreSource = !baseline && coreFile && /\.[cm]?tsx?$/.test(coreFile) ? readFileSync(coreFile) : undefined;
      const base = baseline ?? coreSource;
      const label = baseline ? `core ${place.coreRoute.specifier} (previous release template)` : `core ${place.coreRoute.specifier}`;
      const diff = base
        ? lineDiff(base.toString('utf8'), content.toString('utf8'), { before: label, after: `${root}/${path}` })
        : { text: '', changedLines: -1 };
      record(path, {
        kind: 'override',
        destination: place.destination,
        core: place.coreRoute.specifier,
        baseline: base ? label : null,
        diff: base ? diff.text : "(core's module ships compiled and the previous release's template could not be fetched: compare the file with core's route by hand)",
        diffLines: diff.changedLines,
      });
    } else {
      record(path, { kind: 'project', destination: place.destination });
    }
  }

  return { root, files: files.sort((left, right) => left.path.localeCompare(right.path)), webhookExtensions: webhookExtensionsFor(input, decided) };
}

/** What core's own facade for a route carries: the literal segment config the old generator copied into a loader, and whether it re-exports `metadata`. */
async function facadeShape(host: CoreHost, route: CoreRoute, path: string, hostRoot: string): Promise<{ literals: string[]; hasMetadata: boolean }> {
  try {
    const emitted = await host.emit({ kind: route.kind, target: path, specifier: route.specifier, file: route.file ?? undefined, projectRoot: hostRoot });
    const lines = emitted.content.split('\n');
    return {
      literals: lines.filter(line => line.startsWith('export const ')),
      hasMetadata: lines.some(line => /^export \{[^}]*\bmetadata\b[^}]*\} from /.test(line)),
    };
  } catch {
    return { literals: ['<the emitter rejects the core route>'], hasMetadata: false };
  }
}

/** The project source a file of the app tree would be the generated facade of (`templates/<path>` or `api/<path>`), when it is exactly that. */
async function projectFacadeMatch(host: CoreHost, hostRoot: string, path: string, content: string): Promise<string | null> {
  const parts = splitName(posix.basename(path));
  const routeStem = posix.basename(path).split('.')[0];
  const kind = parts && ROUTE_FILE_EXTENSIONS.includes(parts.extension) ? host.kindForFileStem(routeStem) : null;
  if (!parts || !kind) return null;
  const withoutExtension = path.slice(0, path.length - parts.extension.length - 1);
  const candidates = [{ surface: 'templates', rest: withoutExtension, target: path }];
  if (path.startsWith('api/')) candidates.push({ surface: 'api', rest: withoutExtension.slice('api/'.length), target: path });
  for (const { surface, rest, target } of candidates) {
    for (const extension of ROUTE_FILE_EXTENSIONS) {
      const file = join(hostRoot, surface, `${rest}.${extension}`);
      if (!existsSync(file)) continue;
      try {
        const emitted = await host.emit({ kind, target, specifier: `@/${surface}/${rest}`, file, projectRoot: hostRoot });
        if (normalizeNewlines(emitted.content) === normalizeNewlines(content)) return `${surface}/${rest}.${extension}`;
      } catch {
        // A source the emitter rejects is reported when the generator runs
      }
    }
  }
  return null;
}

/**
 * The project's billing webhook extensions to declare in nextspark.config.ts: core's webhook route
 * used to load `lib/billing/<provider>-webhook-extensions` itself, at run time, from a copy in the
 * project's app tree; that copy is gone now, so a module that holds more than core's empty stub has
 * to be named in `billing.webhookExtensions`.
 */
function webhookExtensionsFor(input: AppConversionInput, decided: ReadonlyMap<string, AppFilePlan>): WebhookExtension[] {
  const found: WebhookExtension[] = [];
  for (const provider of PROVIDERS) {
    const route = decided.get(`api/v1/billing/webhooks/${provider}/route.ts`) ?? decided.get(`api/v1/billing/webhooks/${provider}/route.tsx`);
    if (!route || (route.fate.kind !== 'remove' && route.fate.kind !== 'loader')) continue;
    const module = ['ts', 'tsx', 'js', 'mjs'].map(extension => `lib/billing/${provider}-webhook-extensions.${extension}`).find(path => existsSync(join(input.hostRoot, path)));
    if (!module) continue;
    const stub = input.coreTemplates ? join(input.coreTemplates, 'lib', 'billing', `${provider}-webhook-extensions.ts`) : null;
    if (stub && existsSync(stub) && normalizeNewlines(readFileSync(stub, 'utf8')) === normalizeNewlines(readFileSync(join(input.hostRoot, module), 'utf8'))) continue;
    found.push({ provider, module: `./${module.replace(/\.[^.]+$/, '')}` });
  }
  return found;
}

/** The files that block the migration, as one line each. */
export function unrecognizedLines(plan: AppConversionPlan): string[] {
  return plan.files.flatMap(file => file.fate.kind === 'unrecognized' ? [`${plan.root}/${file.path}: ${file.fate.reason}`] : []);
}

/**
 * `nextspark.config.ts` with `billing.webhookExtensions` declared, or the reason it cannot be
 * edited safely (the file is left as it is and the migration stops before writing).
 */
export function declareWebhookExtensions(config: string, extensions: WebhookExtension[]): { source: string } | { error: string } {
  if (extensions.length === 0) return { source: config };
  const view = sourceView(config);
  const call = /\bdefineConfig\s*\(\s*\{/.exec(view.code);
  if (!call) return { error: 'nextspark.config.ts has no defineConfig({ ... }) object literal to add billing.webhookExtensions to' };
  const open = call.index + call[0].length - 1;
  const close = closingBrace(view.code, open);
  if (close === null) return { error: 'nextspark.config.ts has an unbalanced defineConfig({ ... }) object' };
  // A `billing` key of that object itself, not of a nested one
  let depth = 0;
  for (let index = open; index < close; index++) {
    const char = view.code[index];
    if (char === '{' || char === '[' || char === '(') depth++;
    else if (char === '}' || char === ']' || char === ')') depth--;
    else if (depth === 1 && /\bbilling\b/.test(view.code.slice(index, index + 8)) && !/[\w$]/.test(view.code[index - 1] ?? ' ')) {
      return { error: `nextspark.config.ts already has a billing entry: add webhookExtensions to it by hand (${extensions.map(item => `${item.provider}: '${item.module}'`).join(', ')})` };
    }
  }
  const before = view.code.slice(open + 1, close);
  const firstProperty = /\n([ \t]+)\S/.exec(before);
  const indent = firstProperty?.[1] ?? '  ';
  const body = billingConfigLine(extensions);
  // The last thing of the object that is code (a trailing comment is not)
  const last = before.trimEnd();
  const commaAt = open + 1 + last.length;
  const needsComma = last !== '' && !last.endsWith(',');
  const lineStart = config.lastIndexOf('\n', close - 1) + 1;
  const closesOnItsOwnLine = config.slice(lineStart, close).trim() === '';
  if (closesOnItsOwnLine) {
    return { source: `${config.slice(0, commaAt)}${needsComma ? ',' : ''}${config.slice(commaAt, lineStart)}${indent}${body}\n${config.slice(lineStart)}` };
  }
  // One-line object: `{ plugins: [] }` becomes `{ plugins: [], billing: { ... } }`
  const inline = body.replace(/,$/, '');
  return { source: `${config.slice(0, commaAt)}${needsComma ? ',' : ''} ${inline}${config.slice(commaAt)}` };
}

export function billingConfigLine(extensions: WebhookExtension[]): string {
  return `billing: { webhookExtensions: { ${extensions.map(item => `${item.provider}: ${JSON.stringify(item.module)}`).join(', ')} } },`;
}

/**
 * The one check every destructive step goes through: `target` (written, moved, removed) must be
 * inside `hostRoot` by its real path, and neither it nor any directory above it, down from
 * `hostRoot`, may be a symbolic link (a link would carry the operation outside the project).
 * @throws Error naming the path
 */
export function assertContained(hostRoot: string, target: string): void {
  const root = realpathSync(hostRoot);
  const path = resolve(target);
  const fromRoot = relative(resolve(hostRoot), path);
  if (fromRoot === '..' || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) throw new Error(`Refusing to touch ${target}: it is outside the project`);
  let current = resolve(hostRoot);
  for (const part of fromRoot.split(sep).filter(Boolean)) {
    current = join(current, part);
    let stat;
    try {
      stat = lstatSync(current);
    } catch {
      return; // The rest does not exist yet: nothing to follow
    }
    if (stat.isSymbolicLink()) throw new Error(`Refusing to touch ${relative(resolve(hostRoot), current).split(sep).join('/')}: it is a symbolic link, so the operation could leave the project`);
  }
  const real = realpathSync(path);
  if (real !== root && !real.startsWith(`${root}${sep}`)) throw new Error(`Refusing to touch ${target}: its real path is outside the project`);
}

function removeEmptyDirectories(directory: string): boolean {
  if (!existsSync(directory)) return true;
  let empty = true;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.isDirectory() && removeEmptyDirectories(join(directory, entry.name))) continue;
    empty = false;
  }
  if (empty) rmdirSync(directory);
  return empty;
}

/** Perform a plan: write the converted files, then remove the app tree's planned files. */
export function applyAppConversion(hostRoot: string, plan: AppConversionPlan): { removed: number; overrides: number; moved: number } {
  const appRootDirectory = join(hostRoot, plan.root);
  const moved = new Map<string, string>();
  for (const file of plan.files) {
    if (file.fate.kind === 'override' || file.fate.kind === 'project') moved.set(join(appRootDirectory, file.path), join(hostRoot, file.fate.destination));
  }
  for (const [source, destination] of moved) {
    if (existsSync(destination)) throw new Error(`Refusing to overwrite ${relative(hostRoot, destination).split(sep).join('/')}`);
    assertContained(hostRoot, source);
    assertContained(hostRoot, destination);
    const content = readFileSync(source);
    mkdirSync(dirname(destination), { recursive: true });
    if (isTextSource(source, content)) writeFileSync(destination, rewriteMovedImports(content.toString('utf8'), source, destination, appRootDirectory, moved).source);
    else writeFileSync(destination, content);
  }
  for (const file of plan.files) {
    const source = join(appRootDirectory, file.path);
    assertContained(hostRoot, source);
    if (existsSync(source)) unlinkSync(source);
  }
  assertContained(hostRoot, appRootDirectory);
  removeEmptyDirectories(appRootDirectory);
  const overrides = plan.files.filter(file => file.fate.kind === 'override').length;
  return {
    removed: plan.files.filter(file => file.fate.kind === 'remove' || file.fate.kind === 'loader').length,
    overrides,
    moved: plan.files.filter(file => file.fate.kind === 'project').length + overrides,
  };
}

export interface ApiUrlMove {
  file: string;
  line: number;
  from: string;
  to: string;
}

const API_URL_PATTERN = /\/api\/v1\/(theme|plugin)\/((?:[\w.-]+|\$\{[^}]*\}))\/([^\s'"`)\\]*)/g;

const API_URL_SOURCE = /\.(?:[cm]?[jt]sx?|json|md|mdx|ya?ml|sh|env\.example)$/;

/**
 * The project URLs that change: core's runtime dispatchers under `/api/v1/theme/<theme>/**` and
 * `/api/v1/plugin/<plugin>/**` are gone, the project's `api/` is served at `/api/**` and a plugin's
 * at `/api/plugins/<plugin>/**`. Scanned in the project's own files; the caller lists them.
 */
export function apiUrlMoves(files: readonly string[], hostRoot: string): ApiUrlMove[] {
  const moves: ApiUrlMove[] = [];
  for (const file of files) {
    if (!API_URL_SOURCE.test(file)) continue;
    let text: string;
    try {
      text = readFileSync(file, 'utf8');
    } catch {
      continue;
    }
    if (!text.includes('/api/v1/')) continue;
    text.split('\n').forEach((line, index) => {
      for (const match of line.matchAll(API_URL_PATTERN)) {
        const [from, family, owner, rest] = match;
        const to = family === 'theme' ? `/api/${rest}` : `/api/plugins/${owner}/${rest}`;
        moves.push({ file: relative(hostRoot, file).split(sep).join('/'), line: index + 1, from, to });
      }
    });
  }
  return moves;
}
