import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The line that keeps `app/(templates)` out of git. The registry build rewrites
 * that tree on every run, so a tracked copy only ever drifts from what the build
 * produces - and a fresh checkout would start from the drifted copy.
 */
export const TEMPLATES_GITIGNORE_ENTRY = 'app/(templates)/';

const EQUIVALENT_ENTRIES = new Set(['app/(templates)', 'app/(templates)/', '/app/(templates)', '/app/(templates)/']);

/** Whether a line of the project's .gitignore already ignores `app/(templates)`. */
export function isTemplatesIgnored(projectRoot: string): boolean {
  const gitignorePath = join(projectRoot, '.gitignore');
  return existsSync(gitignorePath)
    && readFileSync(gitignorePath, 'utf-8').split(/\r?\n/).some((line) => EQUIVALENT_ENTRIES.has(line.trim()));
}

/**
 * Add `app/(templates)/` to the project's .gitignore, creating the file if there
 * is none, unless a line already ignores that tree.
 *
 * @returns Whether the line was added.
 */
export function ensureTemplatesIgnored(projectRoot: string): boolean {
  if (isTemplatesIgnored(projectRoot)) {
    return false;
  }

  const gitignorePath = join(projectRoot, '.gitignore');
  const current = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf-8') : '';

  const separator = current === '' ? '' : current.endsWith('\n') ? '\n' : '\n\n';
  writeFileSync(
    gitignorePath,
    `${current}${separator}# Generated by the NextSpark registry build\n${TEMPLATES_GITIGNORE_ENTRY}\n`
  );
  return true;
}

/**
 * The files under `app/(templates)` that git tracks in this project. Empty when
 * the project is not a git repository or git is not installed: there is nothing
 * to warn about then.
 */
export function trackedTemplatesFiles(projectRoot: string): string[] {
  try {
    return execFileSync('git', ['ls-files', '--', 'app/(templates)'], {
      cwd: projectRoot,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .split('\n')
      .filter(Boolean);
  } catch {
    return [];
  }
}
