import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The line that keeps `app/(templates)` out of git. The registry build rewrites
 * that tree on every run, so a tracked copy only ever drifts from what the build
 * produces - and a fresh checkout would start from the drifted copy.
 */
export const TEMPLATES_GITIGNORE_ENTRY = 'app/(templates)/';

const NEXTSPARK_DIR = ['.nextspark', '.nextspark/', '/.nextspark', '/.nextspark/'];

/**
 * Paths of a few shapes under `dir`, of the depths and names the tree there
 * takes, for an entry to be asked about before a run has written anything under
 * it: a project being set up, or a directory whose name a run picks as it writes.
 * They only catch a .gitignore that plainly lacks the line; what a run writes is
 * asked about path by path once it is on disk.
 */
function shapesUnder(dir: string): string[] {
  return [`${dir}/middleware.ts`, `${dir}/dashboard/layout.tsx`, `${dir}/(public)/page.tsx`];
}

/**
 * What sync:app and the registry build leave in a project that has no place in
 * git, grouped under a comment each: the regenerated app/(templates); under
 * .nextspark/ the backups - which can hold a middleware or a config the project
 * never meant to commit - and this machine's sync state; and the copy of app/
 * that --backup takes, one directory per run.
 *
 * `covers` tells whether a path from the project root falls under the entry, and
 * `shapes` are the paths the entry is asked about besides those. `ignoredBy`
 * lists lines that ignore everything under the entry, and stands in where there
 * is no git to ask: git missing, or a project that is not a repository.
 *
 * `asAWhole` marks an entry whose files can't be vouched for one by one before
 * they are written: each copy of app/ goes into a directory named as it is
 * created, and brings app's own .gitignore files, which git reads once they are
 * there and which can take a file back. What covers such a copy is a line that
 * ignores the directory itself, since git doesn't look into a directory it
 * ignores; so once a path under the entry is written, only one of `ignoredBy`,
 * below the .gitignore's last negation, counts.
 */
const GENERATED_PATHS: {
  comment: string;
  entry: string;
  covers: (path: string) => boolean;
  shapes: string[];
  ignoredBy: string[];
  asAWhole?: boolean;
}[] = [
  {
    comment: '# Generated by the NextSpark registry build',
    entry: TEMPLATES_GITIGNORE_ENTRY,
    covers: (path) => path === 'app/(templates)' || path.startsWith('app/(templates)/'),
    shapes: shapesUnder('app/(templates)'),
    ignoredBy: ['app/(templates)', 'app/(templates)/', '/app/(templates)', '/app/(templates)/'],
  },
  {
    comment: '# Backups and state that nextspark sync:app keeps on this machine',
    entry: '.nextspark/backups/',
    covers: (path) => path === '.nextspark/backups' || path.startsWith('.nextspark/backups/'),
    shapes: shapesUnder('.nextspark/backups/2026-01-01T00-00-00-000Z-a1b2c3'),
    ignoredBy: [...NEXTSPARK_DIR, '.nextspark/backups', '.nextspark/backups/', '/.nextspark/backups', '/.nextspark/backups/'],
  },
  {
    comment: '# Backups and state that nextspark sync:app keeps on this machine',
    entry: '.nextspark/sync-state.json',
    covers: (path) => path === '.nextspark/sync-state.json',
    shapes: ['.nextspark/sync-state.json'],
    ignoredBy: [...NEXTSPARK_DIR, '.nextspark/sync-state.json', '/.nextspark/sync-state.json'],
  },
  {
    comment: '# Backups and state that nextspark sync:app keeps on this machine',
    entry: 'app.backup.v*/',
    covers: (path) => /^app\.backup\.v[^/]*\//.test(path),
    shapes: shapesUnder('app.backup.v0.1.0-beta.190.2026-01-01T00-00-00-000Z-a1b2c3'),
    ignoredBy: [
      'app.backup.v*', 'app.backup.v*/', '/app.backup.v*', '/app.backup.v*/',
      'app.backup.*', 'app.backup.*/', '/app.backup.*', '/app.backup.*/',
    ],
    asAWhole: true,
  },
];

function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

/**
 * Every file under `dir`, from the project root, with a symlink listed as the
 * file git sees it as - `dir` itself too, when it is one.
 */
function filesUnder(projectRoot: string, dir: string): string[] {
  const absolute = join(projectRoot, dir);
  if (isSymlink(absolute)) return [dir];
  if (!existsSync(absolute) || !lstatSync(absolute).isDirectory()) return [];
  return readdirSync(absolute, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory() ? filesUnder(projectRoot, `${dir}/${entry.name}`) : [`${dir}/${entry.name}`]
  );
}

/** The symlinks under `dir`, from the project root, without going through any of them. */
function symlinksUnder(projectRoot: string, dir: string): string[] {
  const absolute = join(projectRoot, dir);
  if (!existsSync(absolute) || !lstatSync(absolute).isDirectory()) return [];
  return readdirSync(absolute, { withFileTypes: true }).flatMap((entry) => {
    if (entry.isSymbolicLink()) return [`${dir}/${entry.name}`];
    return entry.isDirectory() ? symlinksUnder(projectRoot, `${dir}/${entry.name}`) : [];
  });
}

/**
 * The places sync:app and the registry build write under that they can't write
 * under safely, from the project root, each with what is wrong with it.
 *
 * A symlink: app, app/(templates) or anything in it, .nextspark, its backups,
 * its registries or anything in them, the sync state, and each of `written` -
 * the paths a sync writes or removes - or a directory above one. What goes
 * through one lands wherever it points, outside the project maybe, and blind: a
 * directory sync:app reads skips a symlink, so a file behind one looks missing
 * and is written over as new, and the build replaces and removes files in
 * app/(templates). Nor can git vouch for it: a symlink is no directory for a line
 * like `app/(templates)/`, so git picks it up, and git won't say whether a path
 * beyond one is ignored.
 *
 * Or something other than what goes there: a file where a directory goes, or a
 * directory where a file does, which stops a run halfway, once it has written
 * part of what it writes.
 */
export function unsafeWritePlaces(projectRoot: string, written: readonly string[] = []): { path: string; problem: string }[] {
  const places: { path: string; kind: 'directory' | 'file' }[] = [
    { path: 'app', kind: 'directory' },
    { path: 'app/(templates)', kind: 'directory' },
    { path: '.nextspark', kind: 'directory' },
    { path: '.nextspark/backups', kind: 'directory' },
    { path: '.nextspark/registries', kind: 'directory' },
    { path: '.nextspark/sync-state.json', kind: 'file' },
  ];

  const unsafe: { path: string; problem: string }[] = [];
  for (const { path, kind } of places) {
    let stat;
    try {
      stat = lstatSync(join(projectRoot, path));
    } catch {
      continue;
    }
    if (stat.isSymbolicLink()) {
      unsafe.push({ path, problem: 'is a symlink' });
    } else if (kind === 'directory' ? !stat.isDirectory() : !stat.isFile()) {
      unsafe.push({ path, problem: `is not a ${kind}` });
    }
  }

  // The first symlink on the way to each path written, from the project root
  for (const path of written) {
    const parts = path.split('/');
    for (let depth = 1; depth <= parts.length; depth++) {
      const along = parts.slice(0, depth).join('/');
      if (!isSymlink(join(projectRoot, along))) continue;
      if (!unsafe.some((place) => place.path === along)) unsafe.push({ path: along, problem: 'is a symlink' });
      break;
    }
  }

  // A tree that is somewhere else already, past a symlink, is not walked
  const walked = unsafe.some(({ path }) => path === 'app' || path === 'app/(templates)') ? [] : ['app/(templates)'];
  if (!unsafe.some(({ path }) => path === '.nextspark' || path === '.nextspark/registries')) walked.push('.nextspark/registries');
  const inside = walked.flatMap((dir) => symlinksUnder(projectRoot, dir)).filter((path) => !unsafe.some((place) => place.path === path));
  return [...unsafe, ...inside.map((path) => ({ path, problem: 'is a symlink' }))];
}

/**
 * The files sync:app and the registry build have left in the project that
 * belong under a .gitignore entry: everything under app/(templates),
 * .nextspark/backups and each app.backup.v directory, and the sync state.
 */
export function generatedPathsOnDisk(projectRoot: string): string[] {
  const appBackups = readdirSync(projectRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith('app.backup.v'))
    .map((entry) => entry.name);
  return [
    ...filesUnder(projectRoot, 'app/(templates)'),
    ...filesUnder(projectRoot, '.nextspark/backups'),
    ...(existsSync(join(projectRoot, '.nextspark', 'sync-state.json')) ? ['.nextspark/sync-state.json'] : []),
    ...appBackups.flatMap((dir) => filesUnder(projectRoot, dir)),
  ];
}

/**
 * Which of `paths` git ignores in this project, or null when it can't say: git
 * missing, or a project that is not a repository. `--no-index` keeps the answer
 * about the patterns alone, so a path already tracked - which is what the
 * app/(templates) warning is about - still counts as ignored and the line is
 * not added a second time.
 *
 * Git answers every path in the order it was asked, with the pattern that
 * decided it: none for a path no pattern matches, and one starting with `!` for
 * a negation, both of which leave the path in. Fewer answers than paths is git
 * stopping partway, which is no answer.
 */
function gitIgnoredPaths(projectRoot: string, paths: readonly string[]): Set<string> | null {
  const unique = [...new Set(paths)];
  if (unique.length === 0) return new Set();

  const asked = spawnSync('git', ['check-ignore', '--no-index', '--stdin', '-z', '--verbose', '--non-matching'], {
    cwd: projectRoot,
    input: unique.map((path) => `${path}\0`).join(''),
    encoding: 'utf-8',
    maxBuffer: Infinity,
  });
  // 0 is some path ignored and 1 is none; anything else is git declining to answer
  if (asked.error || (asked.status !== 0 && asked.status !== 1)) return null;

  // Each answer is four fields: the .gitignore, the line, the pattern and the path
  const fields = asked.stdout.split('\0');
  if (fields.length !== unique.length * 4 + 1) return null;
  return new Set(unique.filter((_, index) => {
    const pattern = fields[index * 4 + 2];
    return pattern !== '' && !pattern.startsWith('!');
  }));
}

/**
 * The lines of the project's .gitignore as git takes their patterns: without the
 * byte order mark that starts the file, a line's closing carriage return, or its
 * trailing spaces. Anything else - a leading space, a trailing tab - is part of
 * the pattern for git, so it stays. None when there is no file, or when it is a
 * symlink, which git does not read.
 */
function gitignoreLines(projectRoot: string): string[] {
  const gitignorePath = join(projectRoot, '.gitignore');
  if (!existsSync(gitignorePath) || gitignoreIsSymlink(projectRoot)) return [];
  return linesAsGitReadsThem(readFileSync(gitignorePath, 'utf-8'));
}

/** The lines of a .gitignore's content as git takes their patterns (see `gitignoreLines`). */
function linesAsGitReadsThem(content: string): string[] {
  return content
    .replace(/^\uFEFF/, '')
    .split('\n')
    .map((line) => line.replace(/\r$/, '').replace(/ +$/, ''));
}

/**
 * The lines the project's .gitignore lacks for sync:app's output, in the order
 * they would be added. `written` are paths from the project root that a run
 * writes or has written; each entry is asked about those under it, every one of
 * them, and about its shapes. What counts is whether git ends up ignoring all of
 * them, not whether some line spells the entry: a negation below a broader
 * pattern, as in `app.backup.*` then `!app.backup.v` and a star, un-ignores the
 * backups again, and a rule that names a file of each shape leaves the rest of
 * the tree in. One path left out is enough to add the line, since the line is
 * what covers the whole of the entry.
 *
 * An entry the file already has below its last negation is not lacking, whatever
 * git answers: appending it again puts it no further down, and what leaves a
 * path in then is a .gitignore further down the tree.
 *
 * Without git to ask, a line that ignores the whole entry counts only below the
 * file's last negation too. Git takes a path's last matching line, so a negation
 * after the line can take back what it ignores - `app.backup.*` then
 * `!app.backup.v` and a star leaves the backups in once the project is a
 * repository - and one before it can't. The same goes for an entry that counts
 * only as a whole once something is written under it, git or no git.
 */
export function missingGitignoreEntries(projectRoot: string, written: readonly string[] = []): string[] {
  const lines = gitignoreLines(projectRoot);
  const lastNegation = lines.reduce((last, line, index) => (line.startsWith('!') ? index : last), -1);
  const inPlace = new Set(lines.slice(lastNegation + 1));
  const ignoredAsAWhole = ({ ignoredBy }: { ignoredBy: string[] }) => ignoredBy.some((line) => inPlace.has(line));

  const asked = GENERATED_PATHS.map((generated) => {
    const under = written.filter(generated.covers);
    const wholeOnly = generated.asAWhole === true && under.length > 0;
    return { ...generated, wholeOnly, paths: wholeOnly ? [] : [...generated.shapes, ...under] };
  });
  const ignored = gitIgnoredPaths(projectRoot, asked.flatMap(({ paths }) => paths));
  if (ignored) {
    return asked
      .filter((generated) => generated.wholeOnly
        ? !ignoredAsAWhole(generated)
        : !inPlace.has(generated.entry) && !generated.paths.every((path) => ignored.has(path)))
      .map(({ entry }) => entry);
  }

  return GENERATED_PATHS.filter((generated) => !ignoredAsAWhole(generated)).map(({ entry }) => entry);
}

/**
 * The paths among `paths` that git does not ignore in this project, in the order
 * given; none outside a repository. With the entries in a .gitignore git reads at
 * the project root, only a .gitignore further down the tree, which git reads
 * after it, can leave one of sync:app's paths in.
 */
export function unignoredPaths(projectRoot: string, paths: readonly string[]): string[] {
  const ignored = gitIgnoredPaths(projectRoot, paths);
  return ignored ? paths.filter((path) => !ignored.has(path)) : [];
}

/**
 * Whether the project's .gitignore is a symlink. Git does not read a .gitignore
 * through a symlink, so a line written to the file it points at ignores nothing.
 */
export function gitignoreIsSymlink(projectRoot: string): boolean {
  try {
    return lstatSync(join(projectRoot, '.gitignore')).isSymbolicLink();
  } catch {
    return false;
  }
}

/**
 * Add the lines the project's .gitignore lacks for sync:app's output, creating
 * the file if there is none. A .gitignore that is a symlink is left as it is.
 *
 * @returns The lines added.
 */
export function ensureGeneratedPathsIgnored(projectRoot: string, written: readonly string[] = []): string[] {
  const missing = missingGitignoreEntries(projectRoot, written);
  if (missing.length === 0 || gitignoreIsSymlink(projectRoot)) return [];

  const gitignorePath = join(projectRoot, '.gitignore');
  const current = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf-8') : '';

  const blocks: string[] = [];
  for (const { comment, entry } of GENERATED_PATHS.filter(({ entry }) => missing.includes(entry))) {
    const last = blocks[blocks.length - 1];
    if (last?.startsWith(`${comment}\n`)) {
      blocks[blocks.length - 1] = `${last}${entry}\n`;
    } else {
      blocks.push(`${comment}\n${entry}\n`);
    }
  }

  const separator = current === '' ? '' : current.endsWith('\n') ? '\n' : '\n\n';
  writeFileSync(gitignorePath, `${current}${separator}${blocks.join('\n')}`);
  return missing;
}

/**
 * The .gitignore sync:app keeps in .nextspark/backups. Each backup there goes
 * into a directory named as it is created - by sync:app, and by core's registry
 * build, which picks its own - and can hold anything, a .gitignore included, so
 * no line in the project's .gitignore can be asked about for a backup before it
 * exists. A .gitignore in the directory that ignores everything in it covers
 * every one of them: git takes the patterns of the deepest .gitignore over those
 * of any other, the repository's exclude file and core.excludesFile, and doesn't
 * look into a directory it ignores.
 */
export const BACKUPS_GITIGNORE = '.nextspark/backups/.gitignore';

const BACKUPS_GITIGNORE_CONTENT = '# Backups nextspark keeps on this machine: none of them belongs in git\n*\n';

/**
 * What .nextspark/backups/.gitignore is: absent; in place, when `*` is the only
 * pattern git reads in it, whatever its comments; a symlink, which git does not
 * read; or anything else - a file with other patterns, which can take a backup
 * back, or no file at all.
 */
export function backupsGitignoreState(projectRoot: string): 'missing' | 'in place' | 'symlink' | 'other' {
  const path = join(projectRoot, BACKUPS_GITIGNORE);
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) return 'symlink';
    if (!stat.isFile()) return 'other';
    const patterns = linesAsGitReadsThem(readFileSync(path, 'utf-8')).filter((line) => line !== '' && !line.startsWith('#'));
    return patterns.length === 1 && patterns[0] === '*' ? 'in place' : 'other';
  } catch {
    return 'missing';
  }
}

/**
 * Give .nextspark/backups the .gitignore sync:app keeps there, when it has none.
 * One already there is never written over: what it holds is the project's.
 *
 * @returns Whether it was written.
 */
export function ensureBackupsGitignore(projectRoot: string): boolean {
  if (backupsGitignoreState(projectRoot) !== 'missing') return false;
  mkdirSync(join(projectRoot, '.nextspark', 'backups'), { recursive: true });
  writeFileSync(join(projectRoot, BACKUPS_GITIGNORE), BACKUPS_GITIGNORE_CONTENT, { flag: 'wx' });
  return true;
}

/**
 * The files under `app/(templates)` that git tracks in this project. Empty when
 * the project is not a git repository or git is not installed: there is nothing
 * to warn about then.
 */
export function trackedTemplatesFiles(projectRoot: string): string[] {
  try {
    return execFileSync('git', ['ls-files', '--', 'app/(templates)'], {
      cwd: projectRoot,
      encoding: 'utf-8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .split('\n')
      .filter(Boolean);
  } catch {
    return [];
  }
}
