#!/usr/bin/env node
/**
 * Generates the `generated/` host: `src/app` facades through the facade emitter and the entity
 * registries under `.nextspark/registries`, both git-ignored and fully rewritten on every run -
 * the same ownership `nextspark prepare` will have over a real project's generated roots.
 *
 * Run: node packages/core/tests/fixtures/host-conformance/generate.mjs
 */
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

import { FacadeEmitError, analyzeRouteSource, emitFacade, loadNextSegmentConfig, planFacade } from '../../../scripts/build/registry/host/facade-emitter.mjs'
import { checkGeneratedModule } from '../../../scripts/build/registry/host/static-imports.mjs'
import { FIXTURE_ROOT, MODES, resolveEntities, resolveRoutePlan } from './plan.mjs'
import { readFile } from 'node:fs/promises'

const HOST = join(FIXTURE_ROOT, 'generated')
const APP_DIR = join(HOST, 'src/app')
const REGISTRIES_DIR = join(HOST, '.nextspark/registries')
const CORE_ROOT = join(FIXTURE_ROOT, '../../..')
const PAGE_EXTENSIONS = MODES.flatMap(mode => [`${mode}.tsx`, `${mode}.ts`]).concat('tsx', 'ts')
const HEADER = '// Generated by NextSpark. Do not edit: regenerated on every build.\n'

/**
 * A route used by both host variants must be valid with cacheComponents on and off; a
 * mode-only route (page.isr.tsx / page.cc.tsx) only in its own.
 */
async function emitRoute(route) {
  const modes = route.mode ? [route.mode] : MODES
  const source = await readFile(route.file, 'utf8')
  const analysis = await analyzeRouteSource({ source, file: route.file, projectRoot: CORE_ROOT })
  const diagnostics = []
  for (const mode of modes) {
    const { diagnostics: found } = planFacade({
      ...route,
      analysis,
      cacheComponents: mode === 'cc',
      pageExtensions: PAGE_EXTENSIONS,
      nextSegmentConfig: loadNextSegmentConfig(CORE_ROOT),
    })
    diagnostics.push(...found.map(diagnostic => ({ ...diagnostic, message: `[${mode} host] ${diagnostic.message}` })))
  }
  if (diagnostics.length > 0) throw new FacadeEmitError(diagnostics)
  return emitFacade({ ...route, source, projectRoot: CORE_ROOT, cacheComponents: modes.length === 1 ? modes[0] === 'cc' : undefined, pageExtensions: PAGE_EXTENSIONS })
}

/** One entity registry: static imports and a literal object of the imported names. */
export function renderEntityRegistry(exportName, importName, file, entities) {
  const imports = entities.map(entity => `import { ${importName} as ${entity} } from '@/entities/${entity}/${file}'\n`).join('')
  return `${HEADER}${imports}\nexport const ${exportName} = { ${entities.join(', ')} } as const\n`
}

export async function generate() {
  const plan = resolveRoutePlan()
  const emitted = []
  const errors = []
  for (const route of plan) {
    try {
      emitted.push(await emitRoute(route))
    } catch (error) {
      if (!(error instanceof FacadeEmitError)) throw error
      errors.push(error.message)
    }
  }
  if (errors.length > 0) throw new Error(errors.join('\n'))

  await rm(join(HOST, 'src'), { recursive: true, force: true })
  await rm(join(HOST, '.nextspark'), { recursive: true, force: true })
  for (const { target, content } of emitted) {
    const path = join(APP_DIR, target)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, content)
  }

  const entities = resolveEntities()
  await mkdir(REGISTRIES_DIR, { recursive: true })
  const registries = {
    'entities.server.ts': renderEntityRegistry('ENTITY_REGISTRY', 'entity', 'entity', entities),
    'entities.client.ts': renderEntityRegistry('CLIENT_ENTITY_REGISTRY', 'clientEntity', 'client', entities),
  }
  for (const [name, content] of Object.entries(registries)) {
    // Registries get the same guarantee as facades: nothing outside the registry grammar.
    const violations = await checkGeneratedModule({ source: content, file: name, grammar: 'registry', projectRoot: CORE_ROOT })
    if (violations.length > 0) throw new Error(`Generated registry ${name} leaves the allowed grammar:\n${violations.map(v => `  ${v.line}: ${v.kind}: ${v.text}`).join('\n')}`)
    await writeFile(join(REGISTRIES_DIR, name), content)
  }
  return { routes: plan, files: emitted.map(file => `src/app/${file.target}`).concat('.nextspark/registries/entities.server.ts', '.nextspark/registries/entities.client.ts') }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { files } = await generate()
  console.log(`Generated ${files.length} files under ${HOST}:\n${files.map(file => `  ${file}`).join('\n')}`)
}
