/**
 * The fixture's host config for the production generator (`nextspark prepare`,
 * packages/core/scripts/build/registry/host/prepare.mjs): core defaults from the fake core's
 * route manifest, replaced by a project `templates/` file at the same path, plus project `api/`
 * and plugin `api/` route handlers. Shared by the generator (to emit facades) and the
 * conformance script (to map build output of both hosts back to the same source module).
 */
import { readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { CORE_ROUTES, ENTITY_MODULES } from './fake-core/routes.mjs'
import { loadCoreRouteManifest } from '../../../scripts/build/registry/host/core-routes.mjs'
import { planEntityRoutes, readAllEntityFacts } from '../../../scripts/build/registry/host/entity-routes.mjs'
import { CORE_COMPOSITION_WRAPPERS } from '../../../scripts/build/registry/host/static-imports.mjs'
import { resolveNextPackage } from '../../../scripts/build/registry/host/facade-emitter.mjs'
import { hashInputs } from '../../../scripts/build/registry/host/generation.mjs'
import { resolveHostPlan } from '../../../scripts/build/registry/host/plan.mjs'
import { existsSync } from 'node:fs'

export const FIXTURE_ROOT = dirname(fileURLToPath(import.meta.url))
export const SOURCE_ROOT = join(FIXTURE_ROOT, 'source')
export const FAKE_CORE_ROOT = join(FIXTURE_ROOT, 'fake-core')
export const GENERATED_ROOT = join(FIXTURE_ROOT, 'generated')
export const CORE_ROOT = join(FIXTURE_ROOT, '../../..')
export const HOSTS = ['manual', 'generated']
export const MODES = ['isr', 'cc']
export const BUNDLERS = ['webpack', 'turbopack']
export const PAGE_EXTENSIONS = MODES.flatMap(mode => [`${mode}.tsx`, `${mode}.ts`]).concat('tsx', 'ts')

/** The fake core's manifest, through the production loader. */
export function loadFixtureCoreRoutes() {
  return loadCoreRouteManifest({
    coreRoot: FAKE_CORE_ROOT,
    entries: CORE_ROUTES,
    manifestPath: join(FAKE_CORE_ROOT, 'routes.mjs'),
    resolveFile: fixtureCoreFile,
    isProtected: () => false,
  })
}

/** The composition wrappers of the fake core, next to core's own (what a composed facade of the fixture may call). */
export const FIXTURE_COMPOSITION_WRAPPERS = Object.freeze({
  ...CORE_COMPOSITION_WRAPPERS,
  '@fixture-core/app/shell-layout': ['withShell'],
  [ENTITY_MODULES.layout]: ['createEntityLayoutRoute'],
  [ENTITY_MODULES.list]: ['createEntityListRoute'],
  [ENTITY_MODULES.detail]: ['createEntityDetailRoute'],
  [ENTITY_MODULES.create]: ['createEntityCreateRoute'],
  [ENTITY_MODULES.edit]: ['createEntityEditRoute'],
})

/** The fake core's module of a `@fixture-core/...` specifier. */
export function fixtureCoreFile(specifier) {
  const base = join(FAKE_CORE_ROOT, specifier.replace('@fixture-core/', ''))
  return ['.tsx', '.ts'].map(extension => `${base}${extension}`).find(candidate => existsSync(candidate)) ?? null
}

/**
 * The entities the fixture writes routes for: the ones with a config the host can read (`<name>.config.ts`
 * exporting `<name>EntityConfig`). The others (notes, posts) have registry entries only.
 */
export function fixtureEntities(sourceRoot = SOURCE_ROOT) {
  return readdirSync(join(sourceRoot, 'entities'), { withFileTypes: true })
    .filter(entry => entry.isDirectory() && existsSync(join(sourceRoot, 'entities', entry.name, `${entry.name}.config.ts`)))
    .map(entry => ({
      name: entry.name,
      exportName: `${entry.name}EntityConfig`,
      configPath: `@/entities/${entry.name}/${entry.name}.config`,
      relativePath: entry.name,
      parent: null,
      children: [],
      source: 'project',
    }))
}

/** The per-entity routes of the fixture (host/entity-routes.mjs, with the fake core's factory modules). */
export async function fixtureEntityPlan({ manifest, sourceRoot = SOURCE_ROOT } = {}) {
  const entities = fixtureEntities(sourceRoot)
  const facts = await readAllEntityFacts({ entities, projectRoot: CORE_ROOT, sourceRoot })
  return planEntityRoutes({ entities, facts, coreRoutes: manifest.routes, resolveFile: fixtureCoreFile, modes: MODES, modules: ENTITY_MODULES })
}

/** Every plugin directory under source/plugins (the fixture enables them all). */
export function fixturePlugins() {
  return readdirSync(join(SOURCE_ROOT, 'plugins'), { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => ({ name: entry.name, root: join(SOURCE_ROOT, 'plugins', entry.name), importBase: `@/plugins/${entry.name}` }))
}

/** Entity registry inputs: one server config and one client-safe config per entity. */
export function resolveEntities() {
  return readdirSync(join(SOURCE_ROOT, 'entities'), { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
}

const HEADER = '// Generated by NextSpark. Do not edit: regenerated on every build.\n'

/** One entity registry: static imports and a literal object of the imported names. */
export function renderEntityRegistry(exportName, importName, file, entities) {
  const imports = entities.map(entity => `import { ${importName} as ${entity} } from '@/entities/${entity}/${file}'\n`).join('')
  return `${HEADER}${imports}\nexport const ${exportName} = { ${entities.join(', ')} } as const\n`
}

/**
 * The host config of the fixture: `source/` is the project, `generated/` the host directory;
 * TypeScript and Next.js resolve from packages/core. Both cache modes are validated.
 */
export function fixtureHostConfig({ hostRoot = GENERATED_ROOT, sourceRoot = SOURCE_ROOT, loadCoreRoutes = loadFixtureCoreRoutes } = {}) {
  return {
    hostRoot,
    projectRoot: CORE_ROOT,
    coreRoot: FAKE_CORE_ROOT,
    loadCoreRoutes,
    plugins: sourceRoot === SOURCE_ROOT ? fixturePlugins() : [],
    project: { root: sourceRoot, importBase: '@', label: 'source' },
    entities: ({ manifest }) => fixtureEntityPlan({ manifest, sourceRoot }),
    compositionWrappers: FIXTURE_COMPOSITION_WRAPPERS,
    modes: MODES,
    pageExtensions: PAGE_EXTENSIONS,
    // Registries get the same guarantee as facades: nothing outside the registry grammar.
    registries: async () => {
      const entities = resolveEntities()
      return [
        { path: '.nextspark/registries/entities.client.ts', content: renderEntityRegistry('CLIENT_ENTITY_REGISTRY', 'clientEntity', 'client', entities), grammar: 'registry' },
        { path: '.nextspark/registries/entities.server.ts', content: renderEntityRegistry('ENTITY_REGISTRY', 'entity', 'entity', entities), grammar: 'registry' },
      ]
    },
    inputs: () => hashInputs({ root: FIXTURE_ROOT, dirs: ['source', 'fake-core'] }),
    versions: { next: resolveNextPackage(CORE_ROOT)?.version ?? 'unresolved' },
    watch: {
      dirs: [join(sourceRoot, 'templates'), join(sourceRoot, 'api'), join(sourceRoot, 'plugins'), join(sourceRoot, 'entities')],
      files: [join(FAKE_CORE_ROOT, 'routes.mjs')],
    },
  }
}

/**
 * Every src/app file of the host, sorted by target. Throws on a collision the plan cannot
 * resolve (two project sources for one target); a project template replacing a core default is
 * the intended override.
 */
export async function resolveRoutePlan() {
  const config = fixtureHostConfig()
  const manifest = await config.loadCoreRoutes()
  const entityPlan = await config.entities({ manifest })
  if (entityPlan.diagnostics.length > 0) throw new Error(entityPlan.diagnostics.map(d => d.message).join('\n'))
  return resolveHostPlan({ coreRoutes: manifest.routes, entityRoutes: entityPlan.routes, plugins: config.plugins, project: config.project, modes: MODES })
}
