/**
 * The fixture's host config for the production generator (`nextspark prepare`,
 * packages/core/scripts/build/registry/host/prepare.mjs): core defaults from the fake core's
 * route manifest, replaced by a project `templates/` file at the same path, plus project `api/`
 * and plugin `api/` route handlers. Shared by the generator (to emit facades) and the
 * conformance script (to map build output of both hosts back to the same source module).
 */
import { readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { CORE_ROUTES } from './fake-core/routes.mjs'
import { loadCoreRouteManifest } from '../../../scripts/build/registry/host/core-routes.mjs'
import { resolveNextPackage } from '../../../scripts/build/registry/host/facade-emitter.mjs'
import { hashInputs } from '../../../scripts/build/registry/host/generation.mjs'
import { resolveHostPlan } from '../../../scripts/build/registry/host/plan.mjs'

export const FIXTURE_ROOT = dirname(fileURLToPath(import.meta.url))
export const SOURCE_ROOT = join(FIXTURE_ROOT, 'source')
export const FAKE_CORE_ROOT = join(FIXTURE_ROOT, 'fake-core')
export const GENERATED_ROOT = join(FIXTURE_ROOT, 'generated')
export const CORE_ROOT = join(FIXTURE_ROOT, '../../..')
export const HOSTS = ['manual', 'generated']
export const MODES = ['isr', 'cc']
export const BUNDLERS = ['webpack', 'turbopack']
export const PAGE_EXTENSIONS = MODES.flatMap(mode => [`${mode}.tsx`, `${mode}.ts`]).concat('tsx', 'ts')

/** The fake core's manifest, through the production loader. */
export function loadFixtureCoreRoutes() {
  return loadCoreRouteManifest({
    coreRoot: FAKE_CORE_ROOT,
    entries: CORE_ROUTES,
    manifestPath: join(FAKE_CORE_ROOT, 'routes.mjs'),
    resolveFile: specifier => join(FAKE_CORE_ROOT, `${specifier.replace('@fixture-core/', '')}.tsx`),
    isProtected: () => false,
  })
}

/** Every plugin directory under source/plugins (the fixture enables them all). */
export function fixturePlugins() {
  return readdirSync(join(SOURCE_ROOT, 'plugins'), { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => ({ name: entry.name, root: join(SOURCE_ROOT, 'plugins', entry.name), importBase: `@/plugins/${entry.name}` }))
}

/** Entity registry inputs: one server config and one client-safe config per entity. */
export function resolveEntities() {
  return readdirSync(join(SOURCE_ROOT, 'entities'), { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
}

const HEADER = '// Generated by NextSpark. Do not edit: regenerated on every build.\n'

/** One entity registry: static imports and a literal object of the imported names. */
export function renderEntityRegistry(exportName, importName, file, entities) {
  const imports = entities.map(entity => `import { ${importName} as ${entity} } from '@/entities/${entity}/${file}'\n`).join('')
  return `${HEADER}${imports}\nexport const ${exportName} = { ${entities.join(', ')} } as const\n`
}

/**
 * The host config of the fixture: `source/` is the project, `generated/` the host directory;
 * TypeScript and Next.js resolve from packages/core. Both cache modes are validated.
 */
export function fixtureHostConfig({ hostRoot = GENERATED_ROOT, sourceRoot = SOURCE_ROOT, loadCoreRoutes = loadFixtureCoreRoutes } = {}) {
  return {
    hostRoot,
    projectRoot: CORE_ROOT,
    coreRoot: FAKE_CORE_ROOT,
    loadCoreRoutes,
    plugins: sourceRoot === SOURCE_ROOT ? fixturePlugins() : [],
    project: { root: sourceRoot, importBase: '@', label: 'source' },
    modes: MODES,
    pageExtensions: PAGE_EXTENSIONS,
    // Registries get the same guarantee as facades: nothing outside the registry grammar.
    registries: async () => {
      const entities = resolveEntities()
      return [
        { path: '.nextspark/registries/entities.client.ts', content: renderEntityRegistry('CLIENT_ENTITY_REGISTRY', 'clientEntity', 'client', entities), grammar: 'registry' },
        { path: '.nextspark/registries/entities.server.ts', content: renderEntityRegistry('ENTITY_REGISTRY', 'entity', 'entity', entities), grammar: 'registry' },
      ]
    },
    inputs: () => hashInputs({ root: FIXTURE_ROOT, dirs: ['source', 'fake-core'] }),
    versions: { next: resolveNextPackage(CORE_ROOT)?.version ?? 'unresolved' },
    watch: {
      dirs: [join(sourceRoot, 'templates'), join(sourceRoot, 'api'), join(sourceRoot, 'plugins'), join(sourceRoot, 'entities')],
      files: [join(FAKE_CORE_ROOT, 'routes.mjs')],
    },
  }
}

/**
 * Every src/app file of the host, sorted by target. Throws on a collision the plan cannot
 * resolve (two project sources for one target); a project template replacing a core default is
 * the intended override.
 */
export async function resolveRoutePlan() {
  const config = fixtureHostConfig()
  const { routes } = await config.loadCoreRoutes()
  return resolveHostPlan({ coreRoutes: routes, plugins: config.plugins, project: config.project, modes: MODES })
}
