/**
 * Template page - directly imports from theme
 * Template: app/(public)/posts/[slug]/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/blog/templates/(public)/posts/[slug]/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
