/**
 * Template page - directly imports from theme
 * Template: app/(public)/author/[username]/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/blog/templates/(public)/author/[username]/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
