/**
 * Template page - directly imports from theme
 * Template: app/superadmin/ai-observability/[traceId]/page.tsx
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/superadmin/ai-observability/[traceId]/page'

// Direct export of the theme template (no fallback)
export default TemplateComponent
