/**
 * Generated by the NextSpark registry build: a copy of app/dashboard/(main)/layout.tsx, so theme
 * routes under src/app/(templates) render inside the same layout. Rewritten on every build.
 */
// Implementation: @nextsparkjs/core/routes/dashboard/(main)/layout (#203). The project's template override for this route is
// still resolved here at runtime, until the generated host replaces this file.
import DefaultMainDashboardLayout from "@nextsparkjs/core/routes/dashboard/(main)/layout"
import { getTemplateOrDefault } from "@nextsparkjs/registries/template-scopes/server/dashboard/(main)/layout"

export default getTemplateOrDefault("app/dashboard/(main)/layout.tsx", DefaultMainDashboardLayout)
