/**
 * Products Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the products entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const productsFields: EntityField[] = [
  {
    name: 'code',
    type: 'text',
    required: true,
    display: {
      label: 'Product Code',
      description: 'Product code or SKU',
      placeholder: 'Enter product code...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Product Name',
      description: 'Product name',
      placeholder: 'Enter product name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 8,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'category',
    type: 'text',
    required: false,
    display: {
      label: 'Category',
      description: 'Product category',
      placeholder: 'Enter category...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'type',
    type: 'select',
    required: false,
    options: [
      { value: 'product', label: 'Product' },
      { value: 'service', label: 'Service' },
      { value: 'subscription', label: 'Subscription' },
      { value: 'bundle', label: 'Bundle' },
      { value: 'addon', label: 'Add-on' },
    ],
    display: {
      label: 'Product Type',
      description: 'Type of product',
      placeholder: 'Select type...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Product description',
      placeholder: 'Enter description...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 12,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'price',
    type: 'number',
    required: true,
    display: {
      label: 'Price',
      description: 'Standard selling price',
      placeholder: '0.00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'cost',
    type: 'number',
    required: false,
    display: {
      label: 'Cost',
      description: 'Product cost',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'currency',
    type: 'select',
    required: false,
    options: [
      { value: 'USD', label: 'US Dollar' },
      { value: 'EUR', label: 'Euro' },
      { value: 'GBP', label: 'British Pound' },
      { value: 'MXN', label: 'Mexican Peso' },
      { value: 'CAD', label: 'Canadian Dollar' },
      { value: 'AUD', label: 'Australian Dollar' },
      { value: 'JPY', label: 'Japanese Yen' },
      { value: 'CNY', label: 'Chinese Yuan' },
      { value: 'INR', label: 'Indian Rupee' },
      { value: 'BRL', label: 'Brazilian Real' },
    ],
    display: {
      label: 'Currency',
      description: 'Currency code',
      placeholder: 'Select currency...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'unit',
    type: 'select',
    required: false,
    options: [
      { value: 'piece', label: 'Piece' },
      { value: 'hour', label: 'Hour' },
      { value: 'day', label: 'Day' },
      { value: 'week', label: 'Week' },
      { value: 'month', label: 'Month' },
      { value: 'year', label: 'Year' },
      { value: 'kg', label: 'Kilogram' },
      { value: 'lb', label: 'Pound' },
      { value: 'meter', label: 'Meter' },
      { value: 'foot', label: 'Foot' },
      { value: 'license', label: 'License' },
      { value: 'user', label: 'User' },
    ],
    display: {
      label: 'Unit of Measure',
      description: 'Unit of measure',
      placeholder: 'Select unit...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'isActive',
    type: 'boolean',
    required: false,
    display: {
      label: 'Active',
      description: 'Is product currently active',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'minimumQuantity',
    type: 'number',
    required: false,
    display: {
      label: 'Minimum Quantity',
      description: 'Minimum order quantity',
      placeholder: '1',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'image',
    type: 'url',
    required: false,
    display: {
      label: 'Image',
      description: 'Product image URL',
      placeholder: 'https://example.com/image.png',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'brochureUrl',
    type: 'url',
    required: false,
    display: {
      label: 'Brochure URL',
      description: 'Product brochure URL',
      placeholder: 'https://example.com/brochure.pdf',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 6,
    },
    api: {
      searchable: false,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'commissionRate',
    type: 'number',
    required: false,
    display: {
      label: 'Commission Rate (%)',
      description: 'Sales commission percentage',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 15,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the product was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the product was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]