/**
 * Template page - directly imports from theme
 * Template: app/dashboard/(main)/settings/ai-usage/page.d.ts
 * Generated by: scripts/build-registry.mjs
 */
import TemplateComponent from '@/contents/themes/default/templates/dashboard/(main)/settings/ai-usage/page.d'

// Direct export of the theme template (no fallback)
export default TemplateComponent
