/**
 * Permission System Initialization
 *
 * DEPRECATED: Runtime initialization replaced by build-time generation.
 * This file now re-exports from the PermissionService and pre-computed registry.
 *
 * The permissions-registry.ts is auto-generated by scripts/build-registry.mjs
 * and includes all permissions pre-computed with O(1) lookups.
 *
 * Query functions are now in PermissionService.
 *
 * @see core/lib/services/permission.service.ts
 * @see core/lib/registries/permissions-registry.ts
 */

// Re-export query functions from PermissionService
export {
  PermissionService,
  hasPermission,
  getRolePermissions,
  getPermissionsByCategory,
  getCategories,
  getFullMatrix,
  isValidPermission,
  getPermissionConfig,
  permissionRegistry,
} from '../services/permission.service'

// Re-export data from the registry
export {
  ALL_PERMISSIONS,
  PERMISSIONS_BY_CATEGORY,
  FULL_MATRIX,
  UI_SECTIONS,
  PERMISSIONS_METADATA
} from '@nextsparkjs/registries/permissions-registry'

/**
 * Legacy initialization function - no longer needed
 * Permissions are now computed at build time
 * @deprecated Use imports from permissions-registry directly
 */
export function initializePermissionRegistry(): void {
  // No-op - permissions are pre-computed at build time
  console.debug('[permissions] Registry is pre-computed at build time, no initialization needed')
}

/**
 * Legacy function - no longer needed
 * Entity permissions are included in the build-time registry
 * @deprecated Use imports from permissions-registry directly
 */
export function ensureEntityPermissionsLoaded(): void {
  // No-op - entity permissions are pre-computed at build time
}
