-- ============================================================================
-- Sample data for notes table - CRM Theme
-- Aligned with schema in 001_notes_table.sql
-- Uses users from 999_theme_sample_data.sql
-- References contacts, companies, opportunities from their sample data
-- ============================================================================

-- Clean existing notes data
DELETE FROM "notes" WHERE "teamId" = 'team-crm-company';

INSERT INTO "notes" (
  id,
  title,
  content,
  type,
  "isPinned",
  "isPrivate",
  "contactId",
  "companyId",
  "opportunityId",
  attachments,
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Contact-related Notes
(
  'note-crm-001',
  'Amanda Davis - Expansion Discussion',
  'Amanda is very happy with current CRM performance. Mentioned they are growing rapidly and may need to add 50+ users by Q2. Interested in advanced analytics module and custom integrations. She has budget authority up to $100K.',
  'meeting',
  true,
  false,
  'contact-crm-001',
  'company-crm-001',
  NULL,
  '[]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '7 days'
),
(
  'note-crm-002',
  'Dr. Martinez Security Concerns',
  'Dr. Martinez raised important questions about data encryption at rest and in transit. Needs documentation for their security review board. Also asked about disaster recovery procedures and data backup frequency. Very thorough and detail-oriented.',
  'call',
  false,
  false,
  'contact-crm-006',
  'company-crm-003',
  NULL,
  '[{"name": "Security_Assessment_Report.pdf", "url": "https://example.com/security-report.pdf"}]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  'note-crm-003',
  'Elizabeth Taylor - Technical Architecture',
  'Elizabeth wants to review our technical architecture in detail. She is concerned about scalability and performance with their user base of 5000+ employees. Needs load testing results and performance benchmarks.',
  'email',
  false,
  true,
  'contact-crm-008',
  'company-crm-004',
  'opp-crm-007',
  '[{"name": "Performance_Benchmarks.xlsx", "url": "https://example.com/benchmarks.xlsx"}]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  'note-crm-004',
  'Maria Gonzalez Demo Notes',
  'Key points for Maria Gonzalez demo: 1) Student lifecycle management, 2) Parent communication tools, 3) Academic tracking, 4) Integration with LMS. She specifically asked about FERPA compliance.',
  'general',
  true,
  false,
  'contact-crm-010',
  'company-crm-005',
  'opp-crm-008',
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),

-- Company-related Notes
(
  'note-crm-005',
  'TechnoSoft Implementation Success Story',
  'Excellent case study material - 40% increase in sales productivity, 60% reduction in data entry time, 95% user adoption rate. Amanda Davis is willing to be a reference customer and participate in case studies.',
  'general',
  true,
  false,
  NULL,
  'company-crm-001',
  NULL,
  '[{"name": "TechnoSoft_Case_Study_Draft.docx", "url": "https://example.com/case-study.docx"}]'::jsonb,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '10 days'
),
(
  'note-crm-006',
  'Global Manufacturing Integration Challenges',
  'Complex integration requirements with legacy ERP system (SAP R/3). Will need custom connector development. IT team is cautious about changes but operations team is pushing for modernization. Political dynamics to navigate.',
  'general',
  true,
  true,
  NULL,
  'company-crm-002',
  NULL,
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '5 days'
),
(
  'note-crm-007',
  'StartupTech Growth Trajectory',
  'Fast-growing startup, secured Series A funding. Currently 25 employees but planning to reach 75 by end of year. Need scalable solution that can grow with them. Price sensitive but understand value of good systems.',
  'general',
  false,
  false,
  NULL,
  'company-crm-007',
  NULL,
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '1 day'
),
(
  'note-crm-008',
  'FinanceFirst Technical Requirements',
  'Technical requirements summary: 1) Single Sign-On with Active Directory, 2) API rate limiting of 10,000 calls/hour, 3) Data encryption AES-256, 4) Audit logging for all user actions, 5) Backup every 6 hours, 6) 99.9% uptime SLA requirement.',
  'general',
  false,
  false,
  NULL,
  'company-crm-004',
  NULL,
  '[{"name": "Technical_Requirements_FinanceFirst.pdf", "url": "https://example.com/tech-requirements.pdf"}]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '20 days'
),

-- Opportunity-related Notes
(
  'note-crm-009',
  'TechnoSoft Enterprise Deal Strategy',
  'This is our biggest opportunity this quarter. Amanda has full decision authority but needs to present to board in February. Focus on ROI metrics and competitive differentiation. Main competitor is Salesforce but we have advantage on customization.',
  'general',
  true,
  true,
  NULL,
  NULL,
  'opp-crm-001',
  '[{"name": "ROI_Analysis_TechnoSoft.xlsx", "url": "https://example.com/roi-analysis.xlsx"}]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '2 days'
),
(
  'note-crm-010',
  'Global Manufacturing Budget Cycle',
  'Budget approval process is complex - needs CFO and CIO approval. Best chance is to get into their Q1 2025 budget cycle. John Patterson is champion but needs ammunition for business case. Focus on operational efficiency gains.',
  'general',
  true,
  false,
  NULL,
  NULL,
  'opp-crm-003',
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '30 days',
  NOW() - INTERVAL '15 days'
),
(
  'note-crm-011',
  'FinanceFirst Competitive Intelligence',
  'Learned from Elizabeth that they are also evaluating Microsoft Dynamics and HubSpot. Our advantages: better financial services compliance, more flexible reporting. Weaknesses: higher price point, newer in market. Strategy: emphasize security and compliance.',
  'general',
  true,
  true,
  NULL,
  NULL,
  'opp-crm-007',
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '8 days'
),
(
  'note-crm-012',
  'EduTech Stakeholder Meeting Summary',
  'Meeting with Maria (Product), Kevin (Engineering), and Finance director. All aligned on need for CRM. Main concerns: 1) Student data privacy, 2) Integration with existing LMS, 3) Training for non-technical staff. Decision timeline: end of Q1 2025.',
  'meeting',
  true,
  false,
  NULL,
  NULL,
  'opp-crm-008',
  '[]'::jsonb,
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),

-- Call Follow-up Notes
(
  'note-crm-013',
  'Amanda Davis Call Follow-up Items',
  'Action items from call: 1) Send technical architecture document, 2) Provide API documentation, 3) Schedule demo with development team, 4) Send pricing for Pro vs Enterprise tiers. She seemed very engaged and asked good questions.',
  'call',
  false,
  false,
  'contact-crm-001',
  'company-crm-001',
  'opp-crm-001',
  '[]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  'note-crm-014',
  'Enterprise Proposal Feedback',
  'Received feedback on enterprise proposal from Amanda. She likes the implementation timeline and training approach. Questioned the data migration timeline - thinks 2 weeks might be tight. Also asked about additional customization options.',
  'general',
  false,
  false,
  'contact-crm-001',
  'company-crm-001',
  'opp-crm-001',
  '[]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '8 days'
),

-- Healthcare Demo Prep
(
  'note-crm-015',
  'Healthcare Demo Preparation Notes',
  'Key points for Healthcare Innovations demo: 1) HIPAA compliance features, 2) Patient data encryption, 3) Audit logging, 4) Integration with EMR systems, 5) Role-based access controls. Patricia specifically asked about data residency and backup procedures.',
  'general',
  true,
  false,
  'contact-crm-006',
  'company-crm-003',
  'opp-crm-005',
  '[{"name": "HIPAA_Compliance_Checklist.pdf", "url": "https://example.com/hipaa-checklist.pdf"}]'::jsonb,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
);
