/**
 * Environment Setup Generator
 *
 * Generates and configures the .env file based on wizard responses.
 */

import crypto from 'crypto'
import fs from 'fs-extra'
import path from 'path'
import type { WizardConfig } from '../types.js'
import type { EnvSetupAnswers } from '../prompts/env-config.js'
import { showSuccess, showInfo, showWarning } from '../banner.js'

/**
 * Generate a secure random secret
 */
function generateSecret(): string {
  return crypto.randomBytes(32).toString('hex')
}

/**
 * Setup environment configuration for the project
 *
 * @param projectPath - Path to the project directory
 * @param answers - Environment setup answers from prompts
 * @param config - Full wizard configuration
 */
export async function setupEnvironment(
  projectPath: string,
  answers: EnvSetupAnswers,
  config: WizardConfig
): Promise<void> {
  if (!answers.setupEnv) {
    showInfo('Skipping .env setup')
    return
  }

  const envExamplePath = path.join(projectPath, '.env.example')
  const envPath = path.join(projectPath, '.env')

  // Check if .env.example exists
  if (!await fs.pathExists(envExamplePath)) {
    showWarning('.env.example not found, creating default .env file')
    await createDefaultEnv(envPath, answers, config)
    return
  }

  // Check if .env already exists
  if (await fs.pathExists(envPath)) {
    showWarning('.env already exists, updating existing file')
    await updateExistingEnv(envPath, answers, config)
    return
  }

  // Copy .env.example to .env
  await fs.copy(envExamplePath, envPath)
  showSuccess('Copied .env.example to .env')

  // Update the .env file with wizard values
  await updateEnvFile(envPath, answers, config)
}

/**
 * Update an existing .env file with new values
 */
async function updateExistingEnv(
  envPath: string,
  answers: EnvSetupAnswers,
  config: WizardConfig
): Promise<void> {
  let content = await fs.readFile(envPath, 'utf-8')

  // Update NEXT_PUBLIC_ACTIVE_THEME
  content = updateEnvVar(content, 'NEXT_PUBLIC_ACTIVE_THEME', config.projectSlug)
  showSuccess(`Set NEXT_PUBLIC_ACTIVE_THEME=${config.projectSlug}`)

  // Generate and set secrets if requested
  if (answers.generateSecrets) {
    const authSecret = generateSecret()
    content = updateEnvVar(content, 'BETTER_AUTH_SECRET', authSecret)
    showSuccess('Generated secure BETTER_AUTH_SECRET')
  }

  // Set DATABASE_URL if provided
  if (answers.databaseUrl) {
    content = updateEnvVar(content, 'DATABASE_URL', answers.databaseUrl)
    showSuccess('Set DATABASE_URL')
  }

  await fs.writeFile(envPath, content, 'utf-8')
}

/**
 * Update the .env file with wizard configuration values
 */
async function updateEnvFile(
  envPath: string,
  answers: EnvSetupAnswers,
  config: WizardConfig
): Promise<void> {
  let content = await fs.readFile(envPath, 'utf-8')

  // Update NEXT_PUBLIC_ACTIVE_THEME with project slug
  content = updateEnvVar(content, 'NEXT_PUBLIC_ACTIVE_THEME', config.projectSlug)
  showSuccess(`Set NEXT_PUBLIC_ACTIVE_THEME=${config.projectSlug}`)

  // Generate and set secrets if requested
  if (answers.generateSecrets) {
    const authSecret = generateSecret()
    content = updateEnvVar(content, 'BETTER_AUTH_SECRET', authSecret)
    showSuccess('Generated secure BETTER_AUTH_SECRET')
  }

  // Set DATABASE_URL if provided
  if (answers.databaseUrl) {
    content = updateEnvVar(content, 'DATABASE_URL', answers.databaseUrl)
    showSuccess('Set DATABASE_URL')
  }

  await fs.writeFile(envPath, content, 'utf-8')
}

/**
 * Update or add an environment variable in content
 */
function updateEnvVar(content: string, key: string, value: string): string {
  // Pattern to match the env var (with or without quotes, commented or not)
  const pattern = new RegExp(`^(#?\\s*${key}\\s*=).*$`, 'm')

  if (pattern.test(content)) {
    // Update existing variable
    return content.replace(pattern, `${key}=${value}`)
  } else {
    // Add new variable at the end
    return content.trimEnd() + `\n${key}=${value}\n`
  }
}

/**
 * Create a default .env file when .env.example doesn't exist
 */
async function createDefaultEnv(
  envPath: string,
  answers: EnvSetupAnswers,
  config: WizardConfig
): Promise<void> {
  const authSecret = answers.generateSecrets ? generateSecret() : 'your-secret-key-min-32-chars'
  const databaseUrl = answers.databaseUrl || 'postgresql://user:password@localhost:5432/nextspark'

  const content = `# NextSpark Environment Configuration
# Generated by NextSpark Wizard for: ${config.projectName}

# Database
DATABASE_URL=${databaseUrl}

# Authentication (Better Auth)
BETTER_AUTH_SECRET=${authSecret}

# App URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Active Theme
NEXT_PUBLIC_ACTIVE_THEME=${config.projectSlug}

# Email (Resend) - Optional
RESEND_API_KEY=
RESEND_FROM_EMAIL=

# Google OAuth - Optional
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
# Required if using OAuth providers - encrypts OAuth tokens in database
# Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
# OAUTH_ENCRYPTION_KEY=

# Stripe - Optional
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=

# Upstash Redis - Optional (for distributed rate limiting)
# Get credentials from https://upstash.com
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=

# Rate Limiting - Optional (development/testing only)
# Set to 'true' to disable rate limiting (WARNING: Never use in production!)
# DISABLE_RATE_LIMITING=true

# CORS Configuration - Optional
# Additional origins for CORS (comma-separated)
# CORS_ADDITIONAL_ORIGINS=http://localhost:8081,https://mobile.myapp.com
# Enable CORS debug logging
# NEXTSPARK_DEBUG_CORS=true

# =============================================================================
# CYPRESS TEST CREDENTIALS
# =============================================================================
# Used by Cypress tests for authentication.
# The CYPRESS_ prefix makes them available as Cypress.env('VARIABLE_NAME')
#
# Core system users (pre-installed from core migrations)
CYPRESS_DEVELOPER_EMAIL=developer@nextspark.dev
CYPRESS_DEVELOPER_PASSWORD=Pandora1234
CYPRESS_SUPERADMIN_EMAIL=superadmin@nextspark.dev
CYPRESS_SUPERADMIN_PASSWORD=Pandora1234

# Theme users - Uncomment and customize when you create your own test users
# CYPRESS_TEST_PASSWORD=Test1234
# CYPRESS_OWNER_EMAIL=owner@example.com
# CYPRESS_ADMIN_EMAIL=admin@example.com
# CYPRESS_MEMBER_EMAIL=member@example.com
`

  await fs.writeFile(envPath, content, 'utf-8')
  showSuccess('Created .env file with default configuration')

  if (answers.generateSecrets) {
    showSuccess('Generated secure BETTER_AUTH_SECRET')
  }

  if (answers.databaseUrl) {
    showSuccess('Set DATABASE_URL')
  }
}
