-- ============================================================================
-- Sample data for products table - CRM Theme
-- Aligned with schema in 001_products_table.sql
-- Uses users from 999_theme_sample_data.sql
-- ============================================================================

-- Clean existing products data
DELETE FROM "products" WHERE "teamId" = 'team-crm-company';

INSERT INTO "products" (
  id,
  code,
  name,
  category,
  type,
  description,
  price,
  cost,
  currency,
  unit,
  "isActive",
  image,
  "brochureUrl",
  "minimumQuantity",
  "commissionRate",
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Software Products (Subscriptions)
(
  'prod-crm-001',
  'CRM-PRO-001',
  'CRM Pro License',
  'Software',
  'subscription',
  'Professional CRM software license with advanced features for growing teams',
  299.00,
  50.00,
  'USD',
  'user',
  true,
  'https://example.com/crm-pro-screenshot1.png',
  'https://example.com/crm-pro-brochure.pdf',
  1,
  10.00,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '30 days'
),
(
  'prod-crm-002',
  'CRM-ENT-001',
  'CRM Enterprise License',
  'Software',
  'subscription',
  'Enterprise CRM solution with unlimited users and advanced customization capabilities',
  899.00,
  150.00,
  'USD',
  'license',
  true,
  'https://example.com/crm-ent-screenshot1.png',
  'https://example.com/crm-enterprise-brochure.pdf',
  1,
  12.00,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '25 days'
),
(
  'prod-crm-003',
  'MOD-ANA-001',
  'Advanced Analytics Module',
  'Add-ons',
  'subscription',
  'Advanced analytics and reporting module for enhanced CRM insights',
  149.00,
  25.00,
  'USD',
  'user',
  true,
  'https://example.com/analytics-module.png',
  'https://example.com/analytics-brochure.pdf',
  1,
  8.00,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '90 days',
  NOW() - INTERVAL '5 days'
),
(
  'prod-crm-004',
  'MOD-MKT-001',
  'Marketing Automation Module',
  'Add-ons',
  'subscription',
  'Marketing automation module with campaign management and lead scoring',
  199.00,
  35.00,
  'USD',
  'user',
  true,
  'https://example.com/marketing-module.png',
  'https://example.com/marketing-brochure.pdf',
  1,
  8.00,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '15 days'
),

-- Service Products
(
  'prod-crm-005',
  'SRV-IMP-001',
  'CRM Implementation Service',
  'Services',
  'service',
  'Professional CRM implementation and setup service with data migration',
  2500.00,
  800.00,
  'USD',
  'piece',
  true,
  'https://example.com/implementation-process.png',
  'https://example.com/implementation-brochure.pdf',
  1,
  15.00,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '180 days',
  NOW() - INTERVAL '20 days'
),
(
  'prod-crm-006',
  'SRV-TRN-001',
  'CRM Training Workshop',
  'Services',
  'service',
  'Comprehensive CRM training workshop for teams with hands-on practice',
  1200.00,
  300.00,
  'USD',
  'day',
  true,
  'https://example.com/training-workshop.png',
  'https://example.com/training-brochure.pdf',
  1,
  12.00,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '150 days',
  NOW() - INTERVAL '15 days'
),
(
  'prod-crm-007',
  'SRV-INT-001',
  'Custom Integration Development',
  'Services',
  'service',
  'Custom integration development service for connecting CRM with third-party systems',
  5000.00,
  2000.00,
  'USD',
  'piece',
  true,
  'https://example.com/integration-service.png',
  'https://example.com/integration-brochure.pdf',
  1,
  15.00,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '10 days'
),

-- Support Packages
(
  'prod-crm-008',
  'SUP-PRI-001',
  'Priority Support Package',
  'Support',
  'subscription',
  'Priority support package with dedicated support representative',
  499.00,
  100.00,
  'USD',
  'month',
  true,
  'https://example.com/priority-support.png',
  'https://example.com/support-brochure.pdf',
  12,
  10.00,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '150 days',
  NOW() - INTERVAL '8 days'
),
(
  'prod-crm-009',
  'SUP-ENT-001',
  'Enterprise Support Package',
  'Support',
  'subscription',
  'Enterprise-grade support with dedicated team and custom SLAs',
  999.00,
  250.00,
  'USD',
  'month',
  true,
  'https://example.com/enterprise-support.png',
  'https://example.com/enterprise-support-brochure.pdf',
  12,
  12.00,
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '150 days',
  NOW() - INTERVAL '5 days'
),

-- Hardware/Infrastructure (for on-premise)
(
  'prod-crm-010',
  'HW-SRV-001',
  'Enterprise Server Package',
  'Infrastructure',
  'product',
  'Complete server package for on-premise CRM deployment with high availability',
  8500.00,
  5200.00,
  'USD',
  'piece',
  true,
  'https://example.com/server-package.png',
  'https://example.com/server-brochure.pdf',
  1,
  5.00,
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '120 days',
  NOW() - INTERVAL '10 days'
);
