/**
 * Campaigns Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the campaigns entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const campaignsFields: EntityField[] = [
  {
    name: 'name',
    type: 'text',
    required: true,
    display: {
      label: 'Campaign Name',
      description: 'Campaign name',
      placeholder: 'Enter campaign name...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'type',
    type: 'select',
    required: false,
    options: [
      { value: 'email', label: 'Email' },
      { value: 'social', label: 'Social Media' },
      { value: 'event', label: 'Event' },
      { value: 'webinar', label: 'Webinar' },
      { value: 'advertising', label: 'Advertising' },
      { value: 'content', label: 'Content Marketing' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Campaign Type',
      description: 'Type of campaign',
      placeholder: 'Select type...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'status',
    type: 'select',
    required: false,
    options: [
      { value: 'planned', label: 'Planned' },
      { value: 'active', label: 'Active' },
      { value: 'paused', label: 'Paused' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    display: {
      label: 'Status',
      description: 'Current campaign status',
      placeholder: 'Select status...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'objective',
    type: 'text',
    required: false,
    display: {
      label: 'Objective',
      description: 'Campaign objective',
      placeholder: 'Enter objective...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Detailed campaign description',
      placeholder: 'Enter description...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 12,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'startDate',
    type: 'date',
    required: true,
    display: {
      label: 'Start Date',
      description: 'Campaign start date',
      placeholder: 'Select date...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'endDate',
    type: 'date',
    required: true,
    display: {
      label: 'End Date',
      description: 'Campaign end date',
      placeholder: 'Select date...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'budget',
    type: 'number',
    required: false,
    display: {
      label: 'Budget',
      description: 'Campaign budget',
      placeholder: '0.00',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'actualCost',
    type: 'number',
    required: false,
    display: {
      label: 'Actual Cost',
      description: 'Actual cost spent',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'targetAudience',
    type: 'text',
    required: false,
    display: {
      label: 'Target Audience',
      description: 'Target audience description',
      placeholder: 'Describe target audience...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'targetLeads',
    type: 'number',
    required: false,
    display: {
      label: 'Target Leads',
      description: 'Target number of leads',
      placeholder: '0',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 3,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'actualLeads',
    type: 'number',
    required: false,
    display: {
      label: 'Actual Leads',
      description: 'Actual leads generated',
      placeholder: '0',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 3,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'targetRevenue',
    type: 'number',
    required: false,
    display: {
      label: 'Target Revenue',
      description: 'Target revenue to generate',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 3,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'actualRevenue',
    type: 'number',
    required: false,
    display: {
      label: 'Actual Revenue',
      description: 'Actual revenue generated',
      placeholder: '0.00',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 3,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'roi',
    type: 'number',
    required: false,
    display: {
      label: 'ROI (%)',
      description: 'Return on investment percentage',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 15,
      columnWidth: 3,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'channel',
    type: 'select',
    required: false,
    options: [
      { value: 'email', label: 'Email' },
      { value: 'social_media', label: 'Social Media' },
      { value: 'web', label: 'Web' },
      { value: 'print', label: 'Print' },
      { value: 'tv', label: 'TV' },
      { value: 'radio', label: 'Radio' },
      { value: 'other', label: 'Other' },
    ],
    display: {
      label: 'Main Channel',
      description: 'Main campaign channel',
      placeholder: 'Select channel...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 16,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'assignedTo',
    type: 'user',
    required: false,
    display: {
      label: 'Campaign Manager',
      description: 'Campaign manager assigned',
      placeholder: 'Select user...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 17,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the campaign was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the campaign was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]