/**
 * Activities Entity Fields Configuration
 *
 * Separated from main config according to new refactoring plan.
 * Contains all field definitions for the activities entity.
 */

import type { EntityField } from '@nextsparkjs/core/lib/entities/types'

export const activitiesFields: EntityField[] = [
  {
    name: 'type',
    type: 'select',
    required: true,
    options: [
      { value: 'call', label: 'Call' },
      { value: 'email', label: 'Email' },
      { value: 'meeting', label: 'Meeting' },
      { value: 'task', label: 'Task' },
      { value: 'note', label: 'Note' },
      { value: 'demo', label: 'Demo' },
      { value: 'presentation', label: 'Presentation' },
    ],
    display: {
      label: 'Activity Type',
      description: 'Type of activity',
      placeholder: 'Select type...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 1,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'subject',
    type: 'text',
    required: true,
    display: {
      label: 'Subject',
      description: 'Activity subject or title',
      placeholder: 'Enter subject...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 2,
      columnWidth: 8,
    },
    api: {
      searchable: true,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'description',
    type: 'textarea',
    required: false,
    display: {
      label: 'Description',
      description: 'Detailed description',
      placeholder: 'Enter description...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 3,
      columnWidth: 12,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'status',
    type: 'select',
    required: false,
    options: [
      { value: 'scheduled', label: 'Scheduled' },
      { value: 'in_progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
      { value: 'overdue', label: 'Overdue' },
    ],
    display: {
      label: 'Status',
      description: 'Current activity status',
      placeholder: 'Select status...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 4,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'priority',
    type: 'select',
    required: false,
    options: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'urgent', label: 'Urgent' },
    ],
    display: {
      label: 'Priority',
      description: 'Activity priority level',
      placeholder: 'Select priority...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 5,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'dueDate',
    type: 'datetime',
    required: false,
    display: {
      label: 'Due Date',
      description: 'When activity is due',
      placeholder: 'Select date and time...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 6,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'completedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Completed At',
      description: 'When activity was completed',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 7,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'duration',
    type: 'number',
    required: false,
    display: {
      label: 'Duration (minutes)',
      description: 'Duration in minutes',
      placeholder: '60',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 8,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'outcome',
    type: 'textarea',
    required: false,
    display: {
      label: 'Outcome',
      description: 'Activity outcome or result',
      placeholder: 'Enter outcome...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 9,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'location',
    type: 'text',
    required: false,
    display: {
      label: 'Location',
      description: 'Location for meetings',
      placeholder: 'Enter location...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 10,
      columnWidth: 6,
    },
    api: {
      searchable: true,
      sortable: false,
      readOnly: false,
    },
  },
  {
    name: 'contactId',
    type: 'relation',
    required: false,
    display: {
      label: 'Contact',
      description: 'Related contact',
      placeholder: 'Select contact...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 11,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
    relation: {
      entity: 'contacts',
      titleField: 'email',
    },
  },
  {
    name: 'companyId',
    type: 'relation',
    required: false,
    display: {
      label: 'Company',
      description: 'Related company',
      placeholder: 'Select company...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 12,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
    relation: {
      entity: 'companies',
      titleField: 'name',
    },
  },
  {
    name: 'opportunityId',
    type: 'relation',
    required: false,
    display: {
      label: 'Opportunity',
      description: 'Related opportunity',
      placeholder: 'Select opportunity...',
      showInList: false,
      showInDetail: true,
      showInForm: true,
      order: 13,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
    relation: {
      entity: 'opportunities',
      titleField: 'name',
    },
  },
  {
    name: 'assignedTo',
    type: 'user',
    required: false,
    display: {
      label: 'Assigned To',
      description: 'User assigned to this activity',
      placeholder: 'Select user...',
      showInList: true,
      showInDetail: true,
      showInForm: true,
      order: 14,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: false,
    },
  },
  {
    name: 'createdAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Created At',
      description: 'When the activity was created',
      showInList: true,
      showInDetail: true,
      showInForm: false,
      order: 98,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
  {
    name: 'updatedAt',
    type: 'datetime',
    required: false,
    display: {
      label: 'Updated At',
      description: 'When the activity was last updated',
      showInList: false,
      showInDetail: true,
      showInForm: false,
      order: 99,
      columnWidth: 4,
    },
    api: {
      searchable: false,
      sortable: true,
      readOnly: true,
    },
  },
]