-- ============================================================================
-- Sample data for leads table - CRM Theme
-- Aligned with schema in 001_leads_table.sql
-- Uses users from 999_theme_sample_data.sql
-- ============================================================================

-- Clean existing leads data
DELETE FROM "leads" WHERE "teamId" = 'team-crm-company';

INSERT INTO "leads" (
  id,
  "companyName",
  "contactName",
  email,
  phone,
  website,
  source,
  status,
  score,
  industry,
  "companySize",
  budget,
  "assignedTo",
  notes,
  "userId",
  "teamId",
  "createdAt",
  "updatedAt"
) VALUES
-- Hot Leads (High Priority)
(
  'lead-crm-001',
  'NewTech Ventures',
  'Sarah Johnson',
  'sarah.johnson@newtech-ventures.com',
  '+1-555-1001',
  'https://newtech-ventures.com',
  'web',
  'qualified',
  85,
  'Technology',
  '51-200',
  50000.00,
  'usr-crm-sales-rep',
  'Very interested in our enterprise solution. Has budget approval.',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '2 days'
),
(
  'lead-crm-002',
  'Innovate Corp',
  'Michael Rodriguez',
  'michael.rodriguez@innovate-corp.com',
  '+1-555-1002',
  'https://innovate-corp.com',
  'referral',
  'qualified',
  92,
  'Manufacturing',
  '201-500',
  120000.00,
  'usr-crm-sales-rep',
  'Referral from existing customer Global Manufacturing. Decision maker.',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '1 day'
),
(
  'lead-crm-003',
  'Future Health Systems',
  'Emily Chen',
  'emily.chen@future-health.com',
  '+1-555-1003',
  'https://future-health.com',
  'social_media',
  'qualified',
  88,
  'Healthcare',
  '201-500',
  85000.00,
  'usr-crm-sales-mgr',
  'LinkedIn connection. Expressed interest in healthcare-specific features.',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '7 days',
  NOW() - INTERVAL '3 days'
),

-- Warm Leads (Medium Priority)
(
  'lead-crm-004',
  'Growth Solutions LLC',
  'David Thompson',
  'david.thompson@growth-solutions.com',
  '+1-555-1004',
  'https://growth-solutions.com',
  'cold_call',
  'contacted',
  72,
  'Consulting',
  '11-50',
  25000.00,
  'usr-crm-sales-rep',
  'Initial call went well. Needs follow-up demo.',
  'usr-crm-sales-mgr',
  'team-crm-company',
  NOW() - INTERVAL '10 days',
  NOW() - INTERVAL '5 days'
),
(
  'lead-crm-005',
  'SmartEdu Technologies',
  'Lisa Anderson',
  'lisa.anderson@smartedu.com',
  '+1-555-1005',
  'https://smartedu.com',
  'advertising',
  'contacted',
  65,
  'Education Technology',
  '51-200',
  32000.00,
  'usr-crm-sales-rep',
  'Came through Google Ads. Evaluating multiple vendors.',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '7 days'
),
(
  'lead-crm-006',
  'Digital Retail Group',
  'Robert Wilson',
  'robert.wilson@digital-retail.com',
  '+1-555-1006',
  'https://digital-retail.com',
  'trade_show',
  'contacted',
  58,
  'Retail',
  '500+',
  150000.00,
  'usr-crm-sales-mgr',
  'Met at CRM Conference 2024. Large potential deal.',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '15 days',
  NOW() - INTERVAL '10 days'
),

-- Cold Leads (Lower Priority)
(
  'lead-crm-007',
  'Local Services Co',
  'Jennifer Brown',
  'jennifer.brown@local-services.com',
  '+1-555-1007',
  'https://local-services.com',
  'email',
  'new',
  35,
  'Professional Services',
  '11-50',
  8000.00,
  NULL,
  'Downloaded whitepaper. No response to follow-up emails yet.',
  'usr-crm-marketing',
  'team-crm-company',
  NOW() - INTERVAL '20 days',
  NOW() - INTERVAL '15 days'
),
(
  'lead-crm-008',
  'Miller Family Business',
  'James Miller',
  'james.miller@family-business.com',
  '+1-555-1008',
  'https://family-business.com',
  'cold_call',
  'contacted',
  42,
  'Family Business',
  '1-10',
  12000.00,
  'usr-crm-sales-rep',
  'Small business owner. Budget constraints but interested.',
  'usr-crm-sales-rep',
  'team-crm-company',
  NOW() - INTERVAL '18 days',
  NOW() - INTERVAL '12 days'
),

-- Converted Lead (Example of successful conversion)
(
  'lead-crm-009',
  'TechnoSoft Solutions',
  'Amanda Davis',
  'amanda.davis@technosoft.com',
  '+1-555-1009',
  'https://technosoft.com',
  'referral',
  'converted',
  95,
  'Software Development',
  '51-200',
  25000.00,
  'usr-crm-sales-mgr',
  'Successfully converted to customer. Now company_001.',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '60 days',
  NOW() - INTERVAL '35 days'
),

-- International Lead
(
  'lead-crm-010',
  'Innovacion Mexico',
  'Carlos Garcia',
  'carlos.garcia@innovacion-mx.com',
  '+52-555-1010',
  'https://innovacion-mx.com',
  'partner',
  'qualified',
  78,
  'Technology',
  '51-200',
  35000.00,
  'usr-crm-sales-mgr',
  'Partner referral from Mexico. Needs Spanish-speaking support.',
  'usr-crm-ceo',
  'team-crm-company',
  NOW() - INTERVAL '8 days',
  NOW() - INTERVAL '4 days'
);

-- Note: convertedToContactId and convertedToCompanyId are UUID columns
-- Cannot link to TEXT IDs like 'contact-crm-001' directly
-- The conversion tracking can be done at application level
