import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  BACKUPS_GITIGNORE,
  backupsGitignoreState,
  ensureBackupsGitignore,
  ensureGeneratedPathsIgnored,
  generatedPathsOnDisk,
  missingGitignoreEntries,
  trackedTemplatesFiles,
  unsafeWritePlaces,
} from '../src/utils/templates-gitignore.js'

async function project() {
  const root = await mkdtemp(join(tmpdir(), 'nextspark-templates-gitignore-'))
  return { root, cleanup: () => rm(root, { recursive: true, force: true }) }
}

/** Whether git ignores `path` in the repository at `root`. */
function gitIgnores(root: string, path: string): boolean {
  try {
    execFileSync('git', ['check-ignore', '-q', '--', path], { cwd: root, stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

test('the missing line is appended to an existing .gitignore, once', async () => {
  const { root, cleanup } = await project()
  try {
    await writeFile(join(root, '.gitignore'), '# NextSpark\n.nextspark/')

    assert.deepEqual(ensureGeneratedPathsIgnored(root), ['app/(templates)/', 'app.backup.v*/'])
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [])

    assert.equal(
      await readFile(join(root, '.gitignore'), 'utf-8'),
      '# NextSpark\n.nextspark/\n\n# Generated by the NextSpark registry build\napp/(templates)/\n\n' +
        '# Backups and state that nextspark sync:app keeps on this machine\napp.backup.v*/\n'
    )
  } finally {
    await cleanup()
  }
})

test('a .gitignore that already ignores each path another way is left alone', async () => {
  const { root, cleanup } = await project()
  try {
    const own = 'node_modules/\n/app/(templates)\n/.nextspark\napp.backup.*\n'
    await writeFile(join(root, '.gitignore'), own)

    assert.deepEqual(missingGitignoreEntries(root), [])
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [])
    assert.equal(await readFile(join(root, '.gitignore'), 'utf-8'), own)
  } finally {
    await cleanup()
  }
})

test('a project with no .gitignore gets one', async () => {
  const { root, cleanup } = await project()
  try {
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [
      'app/(templates)/',
      '.nextspark/backups/',
      '.nextspark/sync-state.json',
      'app.backup.v*/',
    ])
    assert.equal(
      await readFile(join(root, '.gitignore'), 'utf-8'),
      '# Generated by the NextSpark registry build\napp/(templates)/\n\n' +
        '# Backups and state that nextspark sync:app keeps on this machine\n' +
        '.nextspark/backups/\n.nextspark/sync-state.json\napp.backup.v*/\n'
    )
  } finally {
    await cleanup()
  }
})

test('tracked files under app/(templates) are listed, and a project outside git has none', async () => {
  const { root, cleanup } = await project()
  try {
    await mkdir(join(root, 'app/(templates)/dashboard'), { recursive: true })
    await writeFile(join(root, 'app/(templates)/dashboard/layout.tsx'), 'export default function L() { return null }\n')

    assert.deepEqual(trackedTemplatesFiles(root), [])

    execFileSync('git', ['init', '-q'], { cwd: root })
    execFileSync('git', ['add', 'app'], { cwd: root })

    assert.deepEqual(trackedTemplatesFiles(root), ['app/(templates)/dashboard/layout.tsx'])
  } finally {
    await cleanup()
  }
})

test('sync:app backups end up ignored in a .gitignore that does not ignore .nextspark', async () => {
  const { root, cleanup } = await project()
  try {
    await writeFile(join(root, '.gitignore'), 'node_modules/\n')
    execFileSync('git', ['init', '-q'], { cwd: root })

    ensureGeneratedPathsIgnored(root)

    assert.equal(gitIgnores(root, '.nextspark/backups/2026-01-01T00-00-00-000Z-a1b2c3/middleware.ts'), true)
    assert.equal(gitIgnores(root, '.nextspark/sync-state.json'), true)
    assert.equal(gitIgnores(root, 'app/(templates)/dashboard/layout.tsx'), true)
    assert.equal(gitIgnores(root, 'app.backup.v0.1.0-beta.190.2026-01-01T00-00-00-000Z-a1b2c3/layout.tsx'), true)
  } finally {
    await cleanup()
  }
})

test('a negation that un-ignores the backups is not read as a line that already ignores them', async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    await writeFile(join(root, '.gitignore'), 'node_modules/\napp.backup.*\n!app.backup.v*/\n')

    const backup = 'app.backup.v0.1.0-beta.190.2026-01-01T00-00-00-000Z-a1b2c3'
    await mkdir(join(root, backup), { recursive: true })
    await writeFile(join(root, backup, 'private.env'), 'SECRET=1\n')
    assert.equal(gitIgnores(root, `${backup}/private.env`), false, 'the negation leaves the backup un-ignored')

    assert.deepEqual(ensureGeneratedPathsIgnored(root), [
      'app/(templates)/',
      '.nextspark/backups/',
      '.nextspark/sync-state.json',
      'app.backup.v*/',
    ])

    assert.equal(gitIgnores(root, `${backup}/private.env`), true, 'git ignores the backup once the line is added')
    assert.equal(
      execFileSync('git', ['status', '--porcelain'], { cwd: root, encoding: 'utf-8' }).includes(backup),
      false,
      'the backup is no longer untracked'
    )
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [], 'a second run adds nothing')
  } finally {
    await cleanup()
  }
})

test("a rule that covers another run's backup does not stand in for this run's", async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    await writeFile(
      join(root, '.gitignore'),
      'app/(templates)/\n.nextspark/\napp.backup.v0.1.0-beta.190.*/\n'
    )
    const backup = 'app.backup.v0.1.0-beta.189.2026-09-16T00-00-00-000Z-x1y2z3'

    const written = [`${backup}/layout.tsx`]

    assert.deepEqual(missingGitignoreEntries(root, written), ['app.backup.v*/'])
    assert.deepEqual(ensureGeneratedPathsIgnored(root, written), ['app.backup.v*/'])
    for (const file of ['layout.tsx', 'dashboard/page.tsx', '.env.local']) {
      assert.equal(gitIgnores(root, `${backup}/${file}`), true, `git ignores ${backup}/${file}`)
    }
    assert.deepEqual(missingGitignoreEntries(root, written), [], 'a second check finds nothing missing')
  } finally {
    await cleanup()
  }
})

test('app/(templates) counts as ignored only when every file of the tree is, not one of them', async () => {
  const cases: { name: string; gitignore: string; nested?: [string, string] }[] = [
    { name: 'a rule under **', gitignore: '**/dashboard/layout.tsx\n' },
    { name: 'a .gitignore inside the tree', gitignore: '', nested: ['app/(templates)/dashboard/.gitignore', 'layout.tsx\n'] },
    {
      name: 'rules that name the shapes but not a file the run writes',
      gitignore: 'app/(templates)/middleware.ts\napp/(templates)/dashboard/\napp/(templates)/(public)/\n',
    },
  ]
  const written = ['app/(templates)/dashboard/layout.tsx', 'app/(templates)/(auth)/login/page.tsx']

  for (const { name, gitignore, nested } of cases) {
    const { root, cleanup } = await project()
    try {
      execFileSync('git', ['init', '-q'], { cwd: root })
      await writeFile(join(root, '.gitignore'), `${gitignore}.nextspark/\napp.backup.v*/\n`)
      if (nested) {
        await mkdir(join(root, nested[0], '..'), { recursive: true })
        await writeFile(join(root, nested[0]), nested[1])
      }

      assert.deepEqual(ensureGeneratedPathsIgnored(root, written), ['app/(templates)/'], name)
      for (const file of [...written, 'app/(templates)/(public)/[locale]/page.tsx']) {
        assert.equal(gitIgnores(root, file), true, `${name}: git ignores ${file}`)
      }
    } finally {
      await cleanup()
    }
  }
})

test('every path a run wrote is asked about, however many there are and whatever they are named', async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    // Rules for a file of each shape and for all but the last few of the tree's
    // files, and rules for the rest that only git, not the text, reads as done
    await writeFile(
      join(root, '.gitignore'),
      'app/(templates)/middleware.ts\napp/(templates)/dashboard/layout.tsx\napp/(templates)/(public)/page.tsx\n' +
        'app/(templates)/covered/\n.nextspark/*\napp.backup.v*/**\n'
    )
    const covered = Array.from({ length: 20_000 }, (_, i) => `app/(templates)/covered/(group ${i % 50})/page ${i}.tsx`)
    const left = [
      'app/(templates)/deep/with spaces/área/"quoted" (1)/page.tsx',
      "app/(templates)/it's [locale]/*?/page.tsx",
      'app/(templates)/new\nline/page.tsx',
    ]

    assert.deepEqual(missingGitignoreEntries(root, [...covered, ...left]), ['app/(templates)/'])
    assert.deepEqual(ensureGeneratedPathsIgnored(root, [...covered, ...left]), ['app/(templates)/'])
    for (const file of left) {
      assert.equal(gitIgnores(root, file), true, `git ignores ${JSON.stringify(file)}`)
    }
  } finally {
    await cleanup()
  }
})

test("a backup a run wrote counts, not a file of each shape under another run's", async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    await writeFile(
      join(root, '.gitignore'),
      'app/(templates)/\napp.backup.v*/\n.nextspark/sync-state.json\n' +
        '.nextspark/backups/*/middleware.ts\n.nextspark/backups/*/dashboard/layout.tsx\n.nextspark/backups/*/(public)/page.tsx\n'
    )
    const written = ['.nextspark/backups/2026-09-16T00-00-00-000Z-q1w2e3/i18n.ts']

    assert.equal(gitIgnores(root, written[0]), false)
    assert.deepEqual(ensureGeneratedPathsIgnored(root, written), ['.nextspark/backups/'])
    assert.equal(gitIgnores(root, written[0]), true)
  } finally {
    await cleanup()
  }
})

test('the paths on disk are every file under the places sync:app and the registry build write, and nothing else', async () => {
  const { root, cleanup } = await project()
  try {
    const files = [
      'app/(templates)/deep/with spaces/área/"quoted" (1).tsx',
      '.nextspark/backups/2026-09-16T00-00-00-000Z-q1w2e3/app/(templates)/dashboard/layout.tsx',
      '.nextspark/sync-state.json',
      'app.backup.v0.1.0-beta.189.2026-09-16T00-00-00-000Z-x1y2z3/.env.local',
      'app.backup.v0.1.0-beta.189.2026-09-16T00-00-00-000Z-x1y2z3/(public)/page.tsx',
    ]
    const others = ['app/page.tsx', '.nextspark/registries/entities.ts', 'app.backup.vnotes.txt', 'app.backup/layout.tsx']
    for (const file of [...files, ...others]) {
      await mkdir(join(root, file, '..'), { recursive: true })
      await writeFile(join(root, file), '')
    }

    assert.deepEqual(generatedPathsOnDisk(root).sort(), [...files].sort())
  } finally {
    await cleanup()
  }
})

test('a .gitignore that is a symlink is not written through', async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    await writeFile(join(root, 'rules'), 'node_modules/\n')
    await symlink('rules', join(root, '.gitignore'))

    assert.equal(missingGitignoreEntries(root).length, 4)
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [])
    assert.equal(await readFile(join(root, 'rules'), 'utf-8'), 'node_modules/\n')
  } finally {
    await cleanup()
  }
})

test('a line the .gitignore has below its last negation is not added again, and one above a negation is', async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    const rest = '.nextspark/\napp.backup.v*/\n'
    const written = ['app/(templates)/dashboard/layout.tsx']
    await mkdir(join(root, 'app'), { recursive: true })
    await writeFile(join(root, 'app/.gitignore'), '!(templates)/\n')

    await writeFile(join(root, '.gitignore'), `${rest}app/(templates)/\n`)
    assert.equal(gitIgnores(root, written[0]), false, 'app/.gitignore takes the tree back')
    assert.deepEqual(missingGitignoreEntries(root, written), [])
    assert.deepEqual(ensureGeneratedPathsIgnored(root, written), [])

    await writeFile(join(root, 'app/.gitignore'), '')
    await writeFile(join(root, '.gitignore'), `${rest}app/(templates)/\n!app/(templates)/\n`)
    assert.deepEqual(ensureGeneratedPathsIgnored(root, written), ['app/(templates)/'])
    assert.equal(gitIgnores(root, written[0]), true)
  } finally {
    await cleanup()
  }
})

test('a line counts as the entry only as git reads it: a CRLF or trailing spaces do not change it, a leading space or a trailing tab does', async () => {
  const written = ['app/(templates)/dashboard/layout.tsx']
  const rest = '.nextspark/\napp.backup.v*/\n'

  const same = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: same.root })
    await mkdir(join(same.root, 'app'), { recursive: true })
    await writeFile(join(same.root, 'app/.gitignore'), '!(templates)/\n')
    await writeFile(join(same.root, '.gitignore'), `\uFEFF!unrelated\r\napp/(templates)/   \r\n${rest}`)

    assert.deepEqual(missingGitignoreEntries(same.root, written), [], 'the entry is already below the last negation')
  } finally {
    await same.cleanup()
  }

  for (const line of [' app/(templates)/', 'app/(templates)/\t', 'app/(templates)/\u00a0']) {
    const { root, cleanup } = await project()
    try {
      execFileSync('git', ['init', '-q'], { cwd: root })
      await writeFile(join(root, '.gitignore'), `!unrelated\n${line}\n${rest}`)
      assert.equal(gitIgnores(root, written[0]), false, `${JSON.stringify(line)} is another pattern for git`)

      assert.deepEqual(ensureGeneratedPathsIgnored(root, written), ['app/(templates)/'], JSON.stringify(line))
      assert.equal(gitIgnores(root, written[0]), true, JSON.stringify(line))
    } finally {
      await cleanup()
    }
  }
})

test('once a copy of app/ is written, only a line that ignores its directory counts, whatever the copy holds', async () => {
  const backup = 'app.backup.v0.1.0-beta.190.2026-09-16T00-00-00-000Z-Nm4pQz'
  const copy = [`${backup}/layout.tsx`, `${backup}/.gitignore`, `${backup}/visible.txt`]
  const rest = 'app/(templates)/\n.nextspark/\n'
  const cases: { name: string; gitignore: string; missing: string[] }[] = [
    { name: 'a rule for every file under the copies', gitignore: `${rest}app.backup.v*/**\n`, missing: ['app.backup.v*/'] },
    { name: 'a rule for the copies named with this suffix', gitignore: `${rest}app.backup.v*-Nm4pQz/\n`, missing: ['app.backup.v*/'] },
    { name: 'a line for every copy, taken back below', gitignore: `${rest}app.backup.*/\n!app.backup.v*/\n`, missing: ['app.backup.v*/'] },
    { name: 'a line for every copy', gitignore: `${rest}app.backup.*/\n`, missing: [] },
  ]

  // Every case runs before anything is asserted, so a failure names each rule that got through
  const wrong: string[] = []
  for (const { name, gitignore, missing } of cases) {
    const { root, cleanup } = await project()
    try {
      execFileSync('git', ['init', '-q'], { cwd: root })
      await writeFile(join(root, '.gitignore'), gitignore)

      const got = missingGitignoreEntries(root, copy)
      if (JSON.stringify(got) !== JSON.stringify(missing)) wrong.push(`${name}: missing ${JSON.stringify(got)}`)

      // The copy as --backup writes it, with app's .gitignore, which takes a file back
      await mkdir(join(root, backup), { recursive: true })
      await writeFile(join(root, backup, '.gitignore'), '!visible.txt\n')
      await writeFile(join(root, backup, 'visible.txt'), 'SECRET=1\n')
      ensureGeneratedPathsIgnored(root, copy)
      if (!gitIgnores(root, `${backup}/visible.txt`)) wrong.push(`${name}: git does not ignore ${backup}/visible.txt`)
    } finally {
      await cleanup()
    }
  }

  assert.deepEqual(wrong, [])
})

test('the .gitignore in .nextspark/backups ignores a backup whatever its directory is named and whatever the rules above take back', async () => {
  const { root, cleanup } = await project()
  try {
    execFileSync('git', ['init', '-q'], { cwd: root })
    await writeFile(join(root, '.gitignore'), '!.nextspark/\n!.nextspark/backups/**\n')
    await writeFile(join(root, '.git/info/exclude'), '!*\n')
    await mkdir(join(root, '.nextspark/backups/2026-09-16T00-00-00-000Z-r3g1st'), { recursive: true })
    await writeFile(join(root, '.nextspark/.gitignore'), '!backups/\n!backups/**\n')
    await writeFile(join(root, '.nextspark/backups/2026-09-16T00-00-00-000Z-r3g1st/.gitignore'), '!*\n')
    const backups = [
      '.nextspark/backups/2026-09-16T00-00-00-000Z-Zz9Qa1/app/(templates)/(public)/page.tsx',
      '.nextspark/backups/2026-09-16T00-00-00-000Z-r3g1st/i18n.ts',
      '.nextspark/backups/named by hand/.env.local',
    ]
    for (const file of backups) {
      await mkdir(join(root, file, '..'), { recursive: true })
      await writeFile(join(root, file), 'SECRET=1\n')
    }
    assert.deepEqual(backups.map((file) => gitIgnores(root, file)), [false, false, false])

    assert.equal(backupsGitignoreState(root), 'missing')
    assert.equal(ensureBackupsGitignore(root), true)
    assert.equal(ensureBackupsGitignore(root), false, 'a second call leaves it as it is')
    assert.equal(backupsGitignoreState(root), 'in place')

    assert.deepEqual(backups.map((file) => gitIgnores(root, file)), [true, true, true])
    assert.equal(
      execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd: root, encoding: 'utf-8' }),
      '?? .gitignore\n?? .nextspark/.gitignore\n'
    )
  } finally {
    await cleanup()
  }
})

test('a .gitignore in .nextspark/backups counts as in place only with * as its one pattern, and one already there is never written over', async () => {
  const cases: { content: string; state: string }[] = [
    { content: '# Our own words\r\n\n*   \r\n', state: 'in place' },
    { content: '*\n!manual-snapshots/\n', state: 'other' },
    { content: '*\n!*-q1w2e3/\n!*-q1w2e3/**\n', state: 'other' },
    { content: '# nothing\n', state: 'other' },
  ]
  for (const { content, state } of cases) {
    const { root, cleanup } = await project()
    try {
      await mkdir(join(root, '.nextspark/backups'), { recursive: true })
      await writeFile(join(root, BACKUPS_GITIGNORE), content)
      assert.equal(backupsGitignoreState(root), state, JSON.stringify(content))
      assert.equal(ensureBackupsGitignore(root), false, JSON.stringify(content))
      assert.equal(await readFile(join(root, BACKUPS_GITIGNORE), 'utf-8'), content)
    } finally {
      await cleanup()
    }
  }

  const linked = await project()
  const outside = await project()
  try {
    await mkdir(join(linked.root, '.nextspark/backups'), { recursive: true })
    await symlink(join(outside.root, 'rules'), join(linked.root, BACKUPS_GITIGNORE))
    assert.equal(backupsGitignoreState(linked.root), 'symlink')
    assert.equal(ensureBackupsGitignore(linked.root), false)
    assert.equal(existsSync(join(outside.root, 'rules')), false, 'nothing is written through the symlink')
  } finally {
    await linked.cleanup()
    await outside.cleanup()
  }
})

/**
 * Run `check` on a project where git can't be asked about it: outside a
 * repository, or with no git on PATH in one that is.
 */
async function withoutGitToAsk<T>(root: string, mode: 'outside a repository' | 'without git on PATH', check: () => T): Promise<T> {
  if (mode === 'outside a repository') return check()
  execFileSync('git', ['init', '-q'], { cwd: root })
  const path = process.env.PATH
  process.env.PATH = join(root, 'no-git-here')
  try {
    return check()
  } finally {
    process.env.PATH = path
  }
}

test('without git to ask, a line counts only below the .gitignore\'s last negation, as git reads it once the project is a repository', async () => {
  const files = [
    'app/(templates)/dashboard/layout.tsx',
    '.nextspark/backups/2026-09-16T00-00-00-000Z-q1w2e3/i18n.ts',
    '.nextspark/sync-state.json',
    'app.backup.v0.1.0-beta.190.2026-09-16T00-00-00-000Z-x1y2z3/layout.tsx',
  ]
  const cases: { name: string; gitignore: string; added: string[] }[] = [
    {
      name: 'each line taken back by a negation below it',
      gitignore: 'app/(templates)/\n!app/(templates)/\n.nextspark/backups/\n!.nextspark/backups/\n' +
        '.nextspark/sync-state.json\n!/.nextspark/sync-state.json\napp.backup.*/\n!app.backup.v*/\n',
      added: ['app/(templates)/', '.nextspark/backups/', '.nextspark/sync-state.json', 'app.backup.v*/'],
    },
    {
      name: 'lines that ignore again, below the last negation, what one above took back',
      gitignore: 'app/(templates)/\n!app/(templates)/\n.nextspark/\n!.nextspark/\napp.backup.*/\n!app.backup.v*/\n' +
        'app.backup.v*/\n/.nextspark\napp/(templates)\n',
      added: [],
    },
  ]

  // Every case runs in both modes before anything is asserted, so a failure names each one
  const wrong: string[] = []
  for (const mode of ['outside a repository', 'without git on PATH'] as const) {
    for (const { name, gitignore, added } of cases) {
      const { root, cleanup } = await project()
      try {
        await writeFile(join(root, '.gitignore'), gitignore)

        const got = await withoutGitToAsk(root, mode, () => ensureGeneratedPathsIgnored(root))
        if (JSON.stringify(got) !== JSON.stringify(added)) wrong.push(`${mode}, ${name}: added ${JSON.stringify(got)}`)

        execFileSync('git', ['init', '-q'], { cwd: root })
        for (const file of files) {
          if (!gitIgnores(root, file)) wrong.push(`${mode}, ${name}: git does not ignore ${file}`)
        }
      } finally {
        await cleanup()
      }
    }
  }

  assert.deepEqual(wrong, [])
})

test('a symlink where sync:app writes, or something else in the way, is found, and a symlink is listed as the file git sees, not gone through', async () => {
  const { root, cleanup } = await project()
  const outside = await project()
  try {
    await mkdir(join(outside.root, 'dashboard'), { recursive: true })
    await writeFile(join(outside.root, 'dashboard/layout.tsx'), '')
    await mkdir(join(root, 'app'), { recursive: true })
    await mkdir(join(root, '.nextspark/backups/2026-09-16T00-00-00-000Z-q1w2e3'), { recursive: true })
    await writeFile(join(root, '.nextspark/backups/2026-09-16T00-00-00-000Z-q1w2e3/i18n.ts'), '')

    assert.deepEqual(unsafeWritePlaces(root), [])

    await symlink(outside.root, join(root, 'app/(templates)'))
    assert.deepEqual(unsafeWritePlaces(root), [{ path: 'app/(templates)', problem: 'is a symlink' }])
    assert.ok(generatedPathsOnDisk(root).includes('app/(templates)'), 'the symlink is listed')
    assert.ok(!generatedPathsOnDisk(root).some((path) => path.startsWith('app/(templates)/')), 'nothing past it is')

    await rm(join(root, 'app/(templates)'))
    await mkdir(join(root, 'app/(templates)/(public)'), { recursive: true })
    await symlink(join(outside.root, 'dashboard'), join(root, 'app/(templates)/(public)/dashboard'))
    await symlink(join(outside.root, 'missing'), join(root, '.nextspark/sync-state.json'))
    await symlink(join(outside.root, 'dashboard'), join(root, '.nextspark/registries'))
    await symlink(join(outside.root, 'dashboard'), join(root, 'app/dashboard'))
    assert.deepEqual(unsafeWritePlaces(root, ['app/dashboard/page.tsx', 'app/layout.tsx', 'i18n.ts']), [
      { path: '.nextspark/registries', problem: 'is a symlink' },
      { path: '.nextspark/sync-state.json', problem: 'is a symlink' },
      { path: 'app/dashboard', problem: 'is a symlink' },
      { path: 'app/(templates)/(public)/dashboard', problem: 'is a symlink' },
    ])
    assert.deepEqual(unsafeWritePlaces(root).map(({ path }) => path), [
      '.nextspark/registries',
      '.nextspark/sync-state.json',
      'app/(templates)/(public)/dashboard',
    ], 'app/dashboard counts only when a sync writes under it')

    await rm(join(root, '.nextspark/registries'))
    await mkdir(join(root, '.nextspark/registries'))
    await symlink(join(outside.root, 'index.ts'), join(root, '.nextspark/registries/index.ts'))
    assert.ok(unsafeWritePlaces(root).some(({ path }) => path === '.nextspark/registries/index.ts'), 'a symlink in the registries is found')

    await rm(join(root, '.nextspark'), { recursive: true })
    await writeFile(join(root, '.nextspark'), '')
    await rm(join(root, 'app'), { recursive: true })
    await symlink(outside.root, join(root, 'app'))
    assert.deepEqual(unsafeWritePlaces(root), [
      { path: 'app', problem: 'is a symlink' },
      { path: '.nextspark', problem: 'is not a directory' },
    ])
  } finally {
    await outside.cleanup()
    await cleanup()
  }
})
