import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { ensureGeneratedPathsIgnored, missingGitignoreEntries, trackedTemplatesFiles } from '../src/utils/templates-gitignore.js'

async function project() {
  const root = await mkdtemp(join(tmpdir(), 'nextspark-templates-gitignore-'))
  return { root, cleanup: () => rm(root, { recursive: true, force: true }) }
}

test('the missing line is appended to an existing .gitignore, once', async () => {
  const { root, cleanup } = await project()
  try {
    await writeFile(join(root, '.gitignore'), '# NextSpark\n.nextspark/')

    assert.deepEqual(ensureGeneratedPathsIgnored(root), ['app/(templates)/'])
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [])

    assert.equal(
      await readFile(join(root, '.gitignore'), 'utf-8'),
      '# NextSpark\n.nextspark/\n\n# Generated by the NextSpark registry build\napp/(templates)/\n'
    )
  } finally {
    await cleanup()
  }
})

test('a .gitignore that already ignores each path another way is left alone', async () => {
  const { root, cleanup } = await project()
  try {
    await writeFile(join(root, '.gitignore'), 'node_modules/\n/app/(templates)\n/.nextspark\n')

    assert.deepEqual(missingGitignoreEntries(root), [])
    assert.deepEqual(ensureGeneratedPathsIgnored(root), [])
    assert.equal(await readFile(join(root, '.gitignore'), 'utf-8'), 'node_modules/\n/app/(templates)\n/.nextspark\n')
  } finally {
    await cleanup()
  }
})

test('a project with no .gitignore gets one', async () => {
  const { root, cleanup } = await project()
  try {
    assert.deepEqual(ensureGeneratedPathsIgnored(root), ['app/(templates)/', '.nextspark/backups/', '.nextspark/sync-state.json'])
    assert.equal(
      await readFile(join(root, '.gitignore'), 'utf-8'),
      '# Generated by the NextSpark registry build\napp/(templates)/\n\n' +
        '# Backups and state that nextspark sync:app keeps on this machine\n.nextspark/backups/\n.nextspark/sync-state.json\n'
    )
  } finally {
    await cleanup()
  }
})

test('tracked files under app/(templates) are listed, and a project outside git has none', async () => {
  const { root, cleanup } = await project()
  try {
    await mkdir(join(root, 'app/(templates)/dashboard'), { recursive: true })
    await writeFile(join(root, 'app/(templates)/dashboard/layout.tsx'), 'export default function L() { return null }\n')

    assert.deepEqual(trackedTemplatesFiles(root), [])

    execFileSync('git', ['init', '-q'], { cwd: root })
    execFileSync('git', ['add', 'app'], { cwd: root })

    assert.deepEqual(trackedTemplatesFiles(root), ['app/(templates)/dashboard/layout.tsx'])
  } finally {
    await cleanup()
  }
})

test('sync:app backups end up ignored in a .gitignore that does not ignore .nextspark', async () => {
  const { root, cleanup } = await project()
  try {
    await writeFile(join(root, '.gitignore'), 'node_modules/\n')
    execFileSync('git', ['init', '-q'], { cwd: root })

    ensureGeneratedPathsIgnored(root)

    const checkIgnore = (path: string) => {
      try {
        execFileSync('git', ['check-ignore', '-q', path], { cwd: root })
        return true
      } catch {
        return false
      }
    }
    assert.equal(checkIgnore('.nextspark/backups/2026-01-01T00-00-00-000Z-a1b2c3/middleware.ts'), true)
    assert.equal(checkIgnore('.nextspark/sync-state.json'), true)
    assert.equal(checkIgnore('app/(templates)/dashboard/layout.tsx'), true)
  } finally {
    await cleanup()
  }
})
