/**
 * A web-mobile project is the web-only project plus what mobile/ needs (#203 stage 7b): the same root source
 * contract under web/, and a packages/contracts workspace package that `nextspark prepare` generates the API
 * contracts (DTO types and zod schemas) into, from web/'s entities, for mobile/ to import.
 *
 * The generator runs for real in temporary directories, with the mobile template's committed sources standing in for
 * the installed @nextsparkjs/mobile templates; the contracts are generated by core's own prepare script.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { createRequire } from 'node:module'
import { spawnSync } from 'node:child_process'
import { generateProject } from '../src/wizard/generators/index.js'
import { applyPreset } from '../src/wizard/presets.js'
import { MOBILE_SAMPLE_FALLBACK_TYPES } from '../src/wizard/generators/mobile-sample-fallbacks.js'
import { hostPreparationArgs } from '../src/utils/preparation.js'
import type { ProjectType } from '../src/wizard/types.js'

const REPO = path.resolve(import.meta.dirname, '../../..')
const MOBILE_TEMPLATES = path.join(REPO, 'packages/mobile/templates')
const PREPARE_SCRIPT = path.join(REPO, 'packages/core/scripts/build/registry/host/prepare-cli.mjs')
const require = createRequire(path.join(REPO, 'package.json'))

/** The project type's generated directory; the mobile template is the committed one (its gitignored app/ stood in). */
async function generate(type: ProjectType): Promise<string> {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'nextspark-web-mobile-contracts-')))
  const templates = path.join(root, 'node_modules/@nextsparkjs/mobile/templates')
  fs.mkdirSync(path.dirname(templates), { recursive: true })
  fs.cpSync(MOBILE_TEMPLATES, templates, { recursive: true, filter: source => path.basename(source) !== 'app' })
  fs.mkdirSync(path.join(templates, 'app'), { recursive: true })
  fs.writeFileSync(path.join(templates, 'app/_layout.tsx'), 'export default function Layout() { return null }\n')
  fs.writeFileSync(path.join(root, 'package.json'), JSON.stringify({ name: 'acme', private: true }))
  fs.writeFileSync(path.join(root, 'pnpm-workspace.yaml'), "packages:\n  - 'packages/widgets/*'\n")

  const config = applyPreset({ projectName: 'Acme', projectSlug: 'acme', projectDescription: 'Acme' }, 'saas', type)
  const previous = process.cwd()
  process.chdir(root)
  try {
    await generateProject(config)
  } finally {
    process.chdir(previous)
  }
  return root
}

function files(dir: string): string[] {
  const found: string[] = []
  const walk = (current: string) => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      if (entry.name === 'node_modules') continue
      const full = path.join(current, entry.name)
      if (entry.isDirectory()) walk(full)
      else found.push(path.relative(dir, full).split(path.sep).join('/'))
    }
  }
  walk(dir)
  return found.sort()
}

const readJson = (file: string) => JSON.parse(fs.readFileSync(file, 'utf8'))

test('web-mobile: web/ is the web-only project, and packages/contracts is the one thing added for mobile/', async () => {
  const flat = await generate('web')
  const monorepo = await generate('web-mobile')
  try {
    // The same root source contract: everything of a web-only project is in web/, except the two files that
    // belong to the repository root of a monorepo (its .gitignore and its pnpm-workspace.yaml)
    const flatFiles = files(flat)
    const webFiles = files(path.join(monorepo, 'web'))
    assert.deepEqual(flatFiles.filter(file => !webFiles.includes(file)), ['.gitignore', 'pnpm-workspace.yaml'])
    assert.deepEqual(webFiles.filter(file => !flatFiles.includes(file)), [])
    assert.ok(webFiles.includes('nextspark.config.ts') && webFiles.includes('entities/tasks/tasks.config.ts'))
    for (const shared of ['nextspark.config.ts', 'entities/tasks/tasks.config.ts', 'entities/tasks/tasks.fields.ts', 'config/app.config.ts']) {
      assert.equal(fs.readFileSync(path.join(monorepo, 'web', shared), 'utf8'), fs.readFileSync(path.join(flat, shared), 'utf8'), `${shared} differs between web-only and web/`)
    }

    // The contracts package: a private workspace package fed by web/, with no generated source yet
    const contracts = path.join(monorepo, 'packages/contracts')
    assert.deepEqual(files(contracts), ['README.md', 'package.json', 'tsconfig.json'])
    const manifest = readJson(path.join(contracts, 'package.json'))
    assert.equal(manifest.name, '@project/contracts')
    assert.equal(manifest.private, true)
    assert.deepEqual(manifest.exports, { '.': './src/index.ts' })
    assert.deepEqual(Object.keys(manifest.dependencies), ['zod'], 'the contracts import zod and nothing else')
    assert.equal(manifest.nextspark.contractsProject, '../../web')
    assert.equal(path.resolve(contracts, manifest.nextspark.contractsProject), path.join(monorepo, 'web'))

    // It is a workspace member, mobile/ depends on it, and the root has the commands
    const yaml = fs.readFileSync(path.join(monorepo, 'pnpm-workspace.yaml'), 'utf8')
    assert.match(yaml, /^ {2}- 'packages\/contracts'$/m)
    assert.equal(readJson(path.join(monorepo, 'mobile/package.json')).dependencies['@project/contracts'], 'workspace:*')
    const scripts = readJson(path.join(monorepo, 'package.json')).scripts
    assert.equal(scripts.contracts, 'pnpm --filter web exec nextspark prepare --contracts-only')
    assert.equal(scripts['contracts:check'], 'pnpm --filter web exec nextspark prepare --contracts-only --check')
    assert.match(fs.readFileSync(path.join(monorepo, 'README.md'), 'utf8'), /packages\/contracts\/src` is generated by `nextspark prepare`/)
    assert.doesNotMatch(fs.readFileSync(path.join(monorepo, '.gitignore'), 'utf8'), /packages\/contracts/, 'the generated contracts are committed: mobile builds from them without the web project')
  } finally {
    fs.rmSync(flat, { recursive: true, force: true })
    fs.rmSync(monorepo, { recursive: true, force: true })
  }
})

test('web-mobile: nextspark prepare generates the contracts of web/ into packages/contracts, and --check covers them', async () => {
  const monorepo = await generate('web-mobile')
  try {
    const web = path.join(monorepo, 'web')
    const run = (...args: string[]) => spawnSync(process.execPath, [PREPARE_SCRIPT, '--contracts-only', ...args], { cwd: web, encoding: 'utf8' })

    const before = run('--check')
    assert.equal(before.status, 1, 'nothing generated yet')
    assert.match(before.stderr, /have not been generated/)

    const generated = run()
    assert.equal(generated.status, 0, generated.stdout + generated.stderr)
    assert.match(generated.stdout, /Generated the portable contracts \(\d+ files\) in \.\.\/packages\/contracts/)
    const contractFiles = files(path.join(monorepo, 'packages/contracts'))
    assert.deepEqual(contractFiles.filter(file => file.startsWith('src/')), [
      'src/entities/index.ts', 'src/entities/pages.ts', 'src/entities/posts.ts', 'src/entities/tasks.ts', 'src/envelope.ts', 'src/fields.ts', 'src/index.ts',
      // core's portable schema sources, copied verbatim: what the server validates with
      'src/schema/media-ref.ts', 'src/schema/response-shape.ts', 'src/schema/schema-generator.ts', 'src/schema/system-fields.ts', 'src/schema/types.ts',
    ])
    assert.equal(fs.existsSync(path.join(web, '.nextspark/contracts')), false, 'the module went to the package, not to .nextspark')
    const tasks = fs.readFileSync(path.join(monorepo, 'packages/contracts/src/entities/tasks.ts'), 'utf8')
    assert.match(tasks, /export type Task = z\.infer<typeof taskSchema>/)
    assert.match(tasks, /export type CreateTaskInput = /)
    // The schemas the server validates with, byte for byte
    for (const name of ['media-ref', 'response-shape', 'schema-generator', 'system-fields', 'types']) {
      assert.equal(fs.readFileSync(path.join(monorepo, `packages/contracts/src/schema/${name}.ts`), 'utf8'), fs.readFileSync(path.join(REPO, `packages/core/src/lib/entities/portable/${name}.ts`), 'utf8'))
    }
    assert.match(fs.readFileSync(path.join(monorepo, 'packages/contracts/src/entities/tasks.ts'), 'utf8'), /taskSchemas\.create as unknown as/)

    assert.equal(run('--check').status, 0)
    // Editing an entity makes the committed contracts stale for --check, and prepare brings them up to date
    const fields = path.join(web, 'entities/tasks/tasks.fields.ts')
    fs.writeFileSync(fields, fs.readFileSync(fields, 'utf8').replace("{ value: 'todo', label: 'To Do' },", "{ value: 'todo', label: 'To Do' },\n      { value: 'later', label: 'Later' },"))
    const stale = run('--check')
    assert.equal(stale.status, 1)
    assert.match(stale.stderr, /stale +\.\.\/packages\/contracts\/src\/entities\/tasks\.ts/)
    assert.equal(run().status, 0)
    assert.match(fs.readFileSync(path.join(monorepo, 'packages/contracts/src/entities/tasks.ts'), 'utf8'), /'later'/)
    assert.equal(run('--check').status, 0)
  } finally {
    fs.rmSync(monorepo, { recursive: true, force: true })
  }
})

test('web-mobile: a mobile sample whose entity the web project lacks keeps hand-written types, and they compile', async () => {
  const monorepo = await generate('web-mobile')
  try {
    // The starter web project has tasks but no customers entity
    assert.equal(fs.existsSync(path.join(monorepo, 'web/entities/tasks')), true)
    assert.equal(fs.existsSync(path.join(monorepo, 'web/entities/customers')), false)
    const tasksTypes = fs.readFileSync(path.join(monorepo, 'mobile/src/entities/tasks/types.ts'), 'utf8')
    assert.match(tasksTypes, /from '@project\/contracts'/, 'tasks has an entity: its types are the generated ones')
    const customersTypes = fs.readFileSync(path.join(monorepo, 'mobile/src/entities/customers/types.ts'), 'utf8')
    assert.equal(customersTypes, MOBILE_SAMPLE_FALLBACK_TYPES.customers)
    assert.match(customersTypes, /SAMPLE: this project has no `customers` entity/)
    assert.doesNotMatch(customersTypes, /@project\/contracts'/)

    // Both fallbacks export what the template imports, and type-check on their own
    const ts = require('typescript')
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nextspark-fallbacks-'))
    try {
      const expected: Record<string, string[]> = {
        tasks: ['Task', 'TaskStatus', 'TaskPriority', 'CreateTaskInput', 'UpdateTaskInput'],
        customers: ['Customer', 'DayOption', 'CreateCustomerInput', 'UpdateCustomerInput'],
      }
      const rootNames: string[] = []
      for (const [slug, names] of Object.entries(expected)) {
        const file = path.join(dir, `${slug}.ts`)
        fs.writeFileSync(file, `${MOBILE_SAMPLE_FALLBACK_TYPES[slug as 'tasks' | 'customers']}\n`)
        fs.writeFileSync(path.join(dir, `${slug}.probe.ts`), `import type { ${names.join(', ')} } from './${slug}'\nexport type All = [${names.join(', ')}]\n`)
        rootNames.push(file, path.join(dir, `${slug}.probe.ts`))
      }
      const program = ts.createProgram(rootNames, { strict: true, noEmit: true, skipLibCheck: true, types: [] })
      assert.deepEqual(ts.getPreEmitDiagnostics(program).map((d: { messageText: unknown }) => ts.flattenDiagnosticMessageText(d.messageText, '\n')), [])
    } finally {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  } finally {
    fs.rmSync(monorepo, { recursive: true, force: true })
  }
})

test('nextspark prepare --contracts-only reaches core as --contracts-only [--check], without the auth readiness check', () => {
  assert.deepEqual(hostPreparationArgs({ contractsOnly: true }), ['--contracts-only'])
  assert.deepEqual(hostPreparationArgs({ contractsOnly: true, check: true }), ['--contracts-only', '--check'])
})
